### ISSUE TITLE
Bug: How to hide returns 404

### ISSUE THREAD

**Issue by hidde** [a11yproject/a11yproject.com#1000]
## Summary

1. Search for 'visually hidden class' on a search engine (yeah… 😄 )
2. One of the first results may be https://a11yproject.com/posts/how-to-hide-content/ 
3. This page returns a 404, but is available on https://www.a11yproject.com/posts/2013-01-11-how-to-hide-content/ 

### Expected result

There is redirect from old to new

### Actual result

Looks like there's no redirect, so there's a 404 returned.

### Additional Information

n/a

**Comment by hidde** [comment]
I'd be happy to submit something for this, will need to figure out if there's anything for redirects.

**Comment by ericwbailey** [comment]
Oh shoot, thanks for reporting this. I think this is something I can only do on Netlify's end of things, but I'll happily set up redirects for anything you find.

**Comment by ericwbailey** [comment]
@hidde I added some Netlify redirects in https://github.com/a11yproject/a11yproject.com/pull/1002. Can you confirm on your end?

**Comment by hidde** [comment]
Thanks for the super quick response, Eric! This looks good to me, but does not seem to redirect https://a11yproject.com/posts/how-to-hide-content/. I'm not sure why, I do see it is in the toml, so would expect it to work?

**Comment by hidde** [comment]
Oh, I think the issue may be that Netlify expects the `netlify.toml` in the project root rather than in `src`?

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/1010.
