### ISSUE TITLE
Feature: Add direct permalinks for each checklist item

### ISSUE THREAD

**Issue by andrewborstein** [a11yproject/a11yproject.com#1013]
## Background
I often link to https://www.a11yproject.com/checklist when I want to share concise and easily digestable documentation about accessibility with my teammates. But I would love if there were a way to easily share a link directly to a specific checklist item, instead of the entire list or a [section of the list](https://www.a11yproject.com/checklist/#headings).

Currently my workaround is to grab the unique `id` value from the `<summary>` element in the DOM and manually append it to the URL. For example, https://www.a11yproject.com/checklist#dont-skip-heading-levels will link directly to that checklist item. 

From A11y Project:

<img width="1337" alt="Screenshot of a specific checklist item scrolled to the top of the viewport at a11yproject.com" src="https://user-images.githubusercontent.com/7654254/88124410-09065200-cb9b-11ea-83af-60edffbb2799.png">

## Potential implentation

One related technique that could be a source of inspiration is linkable headings.

### Heading text wrapped in a link

From A11y Style Guide:

<img width="262" alt="Screensot of linkable heading at a11y-style-guide.com" src="https://user-images.githubusercontent.com/7654254/88166528-62936e80-cbe5-11ea-94c0-60c32b4685ec.png">

Underlying markup (simplified):
```html
<h2>
  <a href="#kssref-structure-lists">
    Lists
  </a>
</h2>
```

Example link: https://a11y-style-guide.com/style-guide/section-structure.html#kssref-structure-lists

### Heading with icon link appended

From Andy Bell's blog:

<img width="418" alt="Screen Shot 2020-07-22 at 6 29 20 AM" src="https://user-images.githubusercontent.com/7654254/88167863-7cce4c00-cbe7-11ea-8dbc-21bdb019ed9d.png">

Underlying markup (simplified):
```html
<h2 id="heading-size-scales-ftw">
  Size scales FTW
  <a href="#heading-size-scales-ftw">
    <span class="visually-hidden"> permalink</span>
    <svg aria-hidden="true" focusable="false"><path d="M9.199 ..."></path></svg>
  </a>
</h2>
```

Example link: https://hankchizljaw.com/wrote/fluid-scale-and-tokens:-a-match-made-in-heaven/#heading-size-scales-ftw

### Other implementation thoughts

If the anchor link approach is appealing, I think it might need to live outside of the `<summary>` element, so it doesn't interfere with the normal open/close behavior. Or maybe there's a simple progressively enhanced JS solution that would work here, too, where opening a checklist item appends the `#unique-id` to the URL and visiting said URL can automatically open the item details if JS is enabled.

***

Is there any interest in adding a feature like this? If so, I'd love to discuss potential implementation ideas and would also be happy to take the lead on a pull request! 

BTW, love [the redesign](https://www.a11yproject.com/announcements/2020-07-15-2020-redesign) 🙌

**Comment by ericwbailey** [comment]
Hey! I think this would be a great idea, thank you for suggesting it.

I also agree that it would have to live outside of the `<summary>`, both for the reason you suggested and for features suggested in https://github.com/a11yproject/a11yproject.com/issues/942.

I think Eleventy also provides the ability to do this kind of thing outside of Markdown files, but I'd have to double-check the documentation to make sure we can scope it just to this.

Would you like to take the lead on this feature?

**Comment by andrewborstein** [comment]
Hey @ericwbailey glad to hear you would find it useful, too! I'd love to take the lead.

Would it make sense for me to solicit more input on different approaches or just take a shot at one of them and submit a PR? I wanna for aim for whatever creates the least overhead/hassle for the maintainers. I could also connect with [Saptak](https://github.com/SaptakS) just in case he's already working in a similar part of the UI.

**Comment by ericwbailey** [comment]
I think the latter. I trust ya 🙂
