### ISSUE TITLE
Bug: Missing Redirects

### ISSUE THREAD

**Issue by aardrian** [a11yproject/a11yproject.com#1018]
## Summary

I have a link on my site that points to the following URL:
https://www.a11yproject.com/posts/operating-system-and-browser-accessibility-display-modes/

When I visit I get a 404 page. My automated 404 checker tells me this has been broken for 4 days.

### Expected result

I should be redirected (ideally with a 301) to the new address of the page:
https://www.a11yproject.com/posts/2020-01-23-operating-system-and-browser-accessibility-display-modes/

### Actual result

I get a 404. With no search feature, quick index, or suggested links, I am more likely to leave the page.

### Additional Information

I assume this issue is true across the site. Other posts also have their date pre-pended to the file name in the path (which is great, BTW) and I suspect it was not there.

During a site relaunch, content whose URL is going to change could be put into .htaccess (or equivalent) so the server can issue HTTP 301 Permanent Redirects to the new URLs.

This keeps inbound links from breaking, and helps with whatever search engine traction each page may already have.

I give an external link a pass in cases like this (where I can find the new URL relatively quickly), but usually I just link to a Wayback archive page instead, which is also not good for the site I was previously linking since it is one fewer inbound link and users will not discover new content.

**Comment by ericwbailey** [comment]
A fix for this and other post redirect issues is actually underway! The long and short of it is Netlify differs from GitHub pages with how it handles redirects. Thank you for reporting it.

**Comment by aardrian** [comment]
> A fix for this and other post redirect issues is actually underway! 

Awesome; what's your ETA?

**Comment by ericwbailey** [comment]
Around noon EDT, if the winds are favorable.

**Comment by aardrian** [comment]
May the winds ever blow at your backside.

**Comment by ericwbailey** [comment]
I believe I've solved the issue via https://github.com/a11yproject/a11yproject.com/pull/1019. Could I trouble you to verify on your end? I'm assuming there's a little bit of server nonsense that happens, so you may want to give it a bit.

**Comment by aardrian** [comment]
Through a different network than this morning, and then with a VPN, still no luck:

![image](https://user-images.githubusercontent.com/1376607/88413496-47715c00-cda9-11ea-90d0-b767ef5fb03b.png)

Caching is my guess.

**Comment by ericwbailey** [comment]
Ugh. I'll try a VPN as well in a bit. Looks like the copy email address buttons broke as well, fun times.

**Comment by ericwbailey** [comment]
Think I got it via https://github.com/a11yproject/a11yproject.com/pull/1022 🤞

**Comment by aardrian** [comment]
404. Using a different VPN, different connection, different browser.

**Comment by ericwbailey** [comment]
I think I found the culprit, an accidental redirect to `/posts/posts/`. I'll sneak a fix into the PR for https://github.com/a11yproject/a11yproject.com/issues/1026.

**Comment by ericwbailey** [comment]
Seems to be working on my end of things now. Does it now redirect properly for you, @aardrian?

**Comment by aardrian** [comment]
All good!

**Comment by ericwbailey** [comment]
PHEW

**Comment by aardrian** [comment]
This URL from a thing I found:
https://www.a11yproject.com/posts/never-use-maximum-scale/

Should probably point to:
https://www.a11yproject.com/posts/2013-01-14-never-use-maximum-scale/

Perhaps some mappings were missed.

**Comment by ericwbailey** [comment]
>Perhaps some mappings were missed.

That's generous of you 😬 

I just merged https://github.com/a11yproject/a11yproject.com/pull/1090. Can you verify?

**Comment by aardrian** [comment]
That did it.

Are you adding these one-by-one or do you have some automagic mapping?

**Comment by ericwbailey** [comment]
It's manual as they're caught, unfortunately. The previous version hosted on Jekyll and GitHub pages had a tangled ball of Markdown metadata-level redirects that couldn't be moved forward to Eleventy cleanly.

**Comment by aardrian** [comment]
In that case, I look forward to re-opening this issue.

If you are running some form of analytics, the 404 view can be handy. If you aren't, setting up a script to phone home with URL whenever the 404 page is draw could be handy.

I _know_ you do not need my feedback, but as a dude on the internets I cannot stop myself from offering advice you do not need. I mostly want to avoid pestering you every 404 I find.

**Comment by ericwbailey** [comment]
The pestering is appreciated. I check Netlify's analytics daily to see top not found resources, but it's not all not found resources. Getting a outage/404 reporter solution is on my mental checklist, but it's honestly been lower priority dealing with some other issues.

More to the point, thank you for taking the time and effort to let me know what you uncover.
