### ISSUE TITLE
“Creating valid and accessible links” returns 404

### ISSUE THREAD

**Issue by hidde** [a11yproject/a11yproject.com#1026]
## Summary

1. Search for ‘accessible link cards’ on a search engine
2. One of the first results may be https://a11yproject.com/posts/creating-valid-and-accessible-links/ 
3. This page returns a 404. I'm not sure if this post still exists on the new website

### Expected result

There is redirect from old to new

### Actual result

Looks like there's no redirect, so there's a 404 returned.

### Additional Information

n/a

**Comment by ericwbailey** [comment]
I believe https://github.com/a11yproject/a11yproject.com/pull/1028 restores this post and sets up applicable redirects. @hidde, can I trouble you to verify on your end?

**Comment by hidde** [comment]
@ericwbailey Hi Eric, the post was restored, but it did not yet redirect, have addresses this in https://github.com/a11yproject/a11yproject.com/pull/1030, would that work?

**Comment by ericwbailey** [comment]
Wonderfully so. Thank you.
