### ISSUE TITLE
Article: Basic ARIA Roles

### ISSUE THREAD

**Issue by duncanjimbo** [a11yproject/a11yproject.com#1031]
## Description

Derived from the list of post ideas (https://github.com/a11yproject/a11yproject.com/issues/12), this article would be a dive into ARIA roles, looking at the different categories of roles and then detailing some of the more commonly used ARIA roles, including code examples.

## Would you like to write the article or request that it be written?

I would like to write the article.

**Comment by ericwbailey** [comment]
Thanks for volunteering, we'd love that!

**Comment by duncanjimbo** [comment]
PR opened: https://github.com/a11yproject/a11yproject.com/pull/1070
