### ISSUE TITLE
Definition list (dl/dt/dd) styling

### ISSUE THREAD

**Issue by missmatsuko** [a11yproject/a11yproject.com#1037]
Please review our Contributing guidelines:
https://a11yproject.com/contributing-guidelines/

## Summary
I suggest adding more styling to definition lists (dl/dt/dd elements) since it currently doesn't clearly look like a list of definitions or list at all:
<img width="287" alt="Screenshot of list of numeronyms and their definitions." src="https://user-images.githubusercontent.com/17884198/89233198-f548eb80-d59d-11ea-934f-cb3403b33b4b.png">

I think the simplest approach would be to bold the definition term (dt) and maybe add space after the definition data (dd) so the dt and dd pairs look more grouped together.

> Brief description of the issue. Please identify specific steps.
>
> 1. Check out the definition list at [QUICK TIP a11y and a brief numeronyms primer, other numeronyms](https://www.a11yproject.com/posts/2017-08-26-a11y-and-other-numeronyms/#other-numeronyms).

### Expected result

It should be clear that the definition list is a list, and which lines are pairs of terms and data.

### Actual result

The definition list looks like any other text, with line breaks.

### Additional Information

> To help us try and reproduce the issue, please provide the following information:
> 1. What device were you using? (laptop, phone, tablet, etc.)
> 2. Operating System version.
> 3. Browser(s) and version(s).
> 4. Assistive technology used (if applicable)

### Additional Information

Note anything else you think would be important to know that didn't fall into an above category.

**Comment by ericwbailey** [comment]
So, a funny thing happened: the styling for this and some other inline content accidentally got blown away by https://github.com/a11yproject/a11yproject.com/pull/968, then fixed just now in https://github.com/a11yproject/a11yproject.com/pull/1039 😅

How does the updated version look to you? You might have to force refresh to clear the cached version.

**Comment by missmatsuko** [comment]
Ooh, looks much better! Thanks! 😊

**Comment by ericwbailey** [comment]
Thanks for reporting it 🙂
