### ISSUE TITLE
Create color utility classes

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#1046]
Color utility classes will help us consolidate some layout styles by decoupling color from layout logic. For starters, we'll need to create:

- [ ] Text color classes
- [ ] Background color classes
- [ ] Fill color classes

Colors should utilize [our color variables](https://github.com/a11yproject/a11yproject.com/blob/main/src/css/brand/_colors.scss).

**Comment by danielmatthew** [comment]
@ericwbailey May I take this?

**Comment by ericwbailey** [comment]
@danielmatthew That'd be great, thank you!
