### ISSUE TITLE
Add better form validation for our newsletter and contact pages

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#1057]
Currently, we rely on the `required` attribute for our [newsletter signup](https://www.a11yproject.com/newsletter/) and [contact page](https://www.a11yproject.com/contact/) forms. While this does provide basic validation for user input, it is a less than ideal experience.

The public email address we were using was failing to deliver email, so we prioritized speed in getting a replacement up and running. We can do better, however. We need:

- [x] JavaScript validation logic for empty required input on form submission.
- [x] Clear and concise error messaging associated with each input via ARIA.
- [x] A summary area at the top of the form if more than one error is present, linking to each relevant input field.
- [x] A designed error state that does not rely on color alone.

**Comment by ericwbailey** [comment]
@jendowns is this something you'd be interested in helping out with?

**Comment by jendowns** [comment]
Hey @ericwbailey! Yes I'd love to work on this.

**Comment by ericwbailey** [comment]
Heck yes! Let me know if there's anything I can help you out with 😀

**Comment by jendowns** [comment]
Hey @ericwbailey! I had a quick question about link / error message styling & messaging --

Here's an in-progress screenshot, showing the top of the Contact page form with errors:

<img width="515"  alt="Screenshot of error messages for a contact form saying 'There was a problem with the form. Please provide your name. Please provide your email. Please provide your message." src="https://user-images.githubusercontent.com/9057921/90342060-cb92ba00-dfca-11ea-8472-560af5bacf2a.png">

And I was curious if you had any preferences with regards to (1) link styling, and (2) error messaging.

I was thinking of styling these links similar to some of the dark links on the resources page? For example:
<img width="359" alt="Screen Shot 2020-08-16 at 2 16 22 PM" src="https://user-images.githubusercontent.com/9057921/90342098-288e7000-dfcb-11ea-9663-dd9d9e4b9cb0.png">

And then just on the topic of the error messaging in general, what do you think of the messaging in general?
- Summary message: "There was an issue with the form."
- Error for empty field: "Please provide `{field label}`."
- Error for invalid field (email only): "Please provide a valid entry for `{field label}`."

What do you think?

**Comment by ericwbailey** [comment]
I think both your idea for an approach for link styling and for copy sound good to me 🎉
