### ISSUE TITLE
Load CSS asynchronously

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#1075]
Our current CSS payload weighs in at 60kb, which is above the size of a single roundtrip HTTP request.

That being said, our site is fast. Let's experiment with [Filament Group's async CSS loading technique](https://www.filamentgroup.com/lab/load-css-simpler/) to see if it improves things.

**Comment by SaptakS** [comment]
The only thing we will probably need to test is whether it causes Flash Of Unstyled Content (FOUC). I think we might need to separate critical CSS from the rest to avoid some nasty FOUC

**Comment by ericwbailey** [comment]
@SaptakS Agreed. I'm in the process of shifting some of our component declarations over to utility styles, which should (hopefully) help with this. Trouble is our layout is kind of finicky :\

**Comment by ericwbailey** [comment]
I am closing this based on [this very lovely tweet](https://twitter.com/eleven_ty/status/1302948833626918912). 

I think utility styles will continue to help improve on performance, and I am now a little more comfortable with the CSS weight given that we seem to be, er, performing pretty well!
