### ISSUE TITLE
the local copy won't start

### ISSUE THREAD

**Issue by zwiastunsw** [a11yproject/a11yproject.com#1092]
## Summary

After installation, I receive a Cannot GET /
(Env: Windows 10, 64bit)

**Comment by ericwbailey** [comment]
I am unable to reproduce this issue on my machine (macOS 10.15.6). Can you verify you're using the right version of node? Minimum version is 12.13.1.

**Comment by zwiastunsw** [comment]
thx, I reinstalled node and it's OK
