### ISSUE TITLE
Post collections

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#1096]
Some posts benefit from being read in sequence. For example, our ARIA [roles](https://www.a11yproject.com/posts/2020-08-20-an-indepth-guide-to-aria-roles/), [states](https://www.a11yproject.com/posts/2018-07-30-aria-states/), and [properties](https://www.a11yproject.com/posts/2018-07-30-aria-properties/) posts.

I'm thinking a collection is a lot like a learning track, where it can tie together content from different categories, so long as it all builds towards teaching an overall concept.

We'll need to:

- [ ] Identify some initial collection bundles
- [ ] Set a reading order for each bundle's collection of posts
- [ ] Create and add the metadata to our posts
- [ ] Design a visual treatment to indicate a post is part of a collection

We may also need to create landing pages for collections, to show each post and its reading order.

**Comment by SaptakS** [comment]
I really like this idea. I think landing page would be great to point to the different resources in an orderly fashion. Something similar that immediately comes to my mind is: https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world

**Comment by nchan0154** [comment]
I'd like to try tackle this one if that's okay, @ericwbailey!

**Comment by ericwbailey** [comment]
@nchan0154 Heck yeah!

**Comment by nchan0154** [comment]
I have added an initial draft of the collections!

Each collection should be a file in the `src/collections/` folder. Each collection has a layout of 'collection', title, an optional author, an optional description, and an optional post body, and should be named a slugified version of the title.

```
---
layout: collection
title: Introduction to ARIA
description: Description here!
author: Author Here (whoever drafted the collection intro/proposed it?)
---

Collection Text here!
```

To assign a post to a collection, add the slug and order metadata to a post. I've incremented the order by 10 so there's some wiggle room, but it just has to be incrementing (larger numbers are later in the series)!
```
collection:
  slug: introduction-to-aria
  order: 10
```

Things I would like input/help on:
- I've only created one collection thus far (Introduction to ARIA), if anyone has suggestions for any collections, please feel free to post!
- I have not created a page/layout at '/collections/', but I think it would probably be useful to have a list for all of them somewhere. I can spin one up based on other template pages if someone makes me an SVG that says "Collections" in the style of the other hero SVGs and tells me what colors to use. 
- Tangentially related to the previous point, is 'Collections' too long for a header? We could consider other names like 'Series', taking suggestions here. 
- Is the current display within a post too verbose? Right now I just have a full post card, I was planning to pass in an aria-current attribute to the card pending a refactor in #1220 (please let me know if you need help on this @ericwbailey) to apply styling to the current post. 

[Screenshot of how the individual collection pages look](https://user-images.githubusercontent.com/12852862/113503753-53333600-9566-11eb-82e9-30cdc46b48a2.png)
[Screenshot of the how the collection is listsed at the end of a post](https://user-images.githubusercontent.com/12852862/113503751-52020900-9566-11eb-9d3c-dad5eb7e974d.PNG)

**Comment by SaptakS** [comment]
The first draft looks great! Thanks for the work! 

> I have not created a page/layout at '/collections/', but I think it would probably be useful to have a list for all of them somewhere. I can spin one up based on other template pages if someone makes me an SVG that says "Collections" in the style of the other hero SVGs and tells me what colors to use.

I agree. There needs to be a page either at `/collections/` and should probably add a link in the navbar as well. As of colors to use, since both /posts/ and /checklist/ page focus styles are primarily blue, and only /resources/ page is green based, I think it's fine to maybe use a green color scheme for `/collections/`? I will leave the final decision on this to @ericwbailey and also he will probably need to help you with the hero SVGs

> Is the current display within a post too verbose?

I was also thinking that if a collection has quite some posts, it will be too long. So few things I think might make sense is:
- just to mention which collection this post is part of with a link to the collection
- first 2-3 posts in the collection, along with like a "More posts in this collection" linking to the collectionpage
- the previous and the next post in the collection, with a link to the entire collection (my preference)

I prefer the 3rd option since if I am reading through a collection I would want to directly go to the next post, but it kind of collides with the already existing previous and next post. I won't be against removing current previous/next post if the post is part of a collection.

**Comment by nchan0154** [comment]
Thank you for the feedback! One more option for display on the aritcle pages I'd like to present is an example from CSS tricks, where they have a callout box and a list of links:
![Capture](https://user-images.githubusercontent.com/12852862/113526606-47d71d80-95ed-11eb-8ec6-aca5360e9f9a.PNG)

**Comment by SaptakS** [comment]
Yes. I like this idea too compared to a more verbose display of all posts in a series/collection.

**Comment by ericwbailey** [comment]
I really like the CSS-Tricks approach as well (also I may be biased 😅).

**Comment by nchan0154** [comment]
Thanks for your patience! I've added the tweaks requested by @SaptakS and @ericwbailey  as well as created a new page for all collections.

The collection display within posts is now condensed down to a format more like the CSS-Tricks screenshot above.
[Screenshot of collection display within a post](https://user-images.githubusercontent.com/12852862/116799345-2b1a0100-ab2b-11eb-9c18-11825b3d8469.PNG)

I've created a new (green) page for listing all collections and their content and added it to the nav. I need some help creating an appropriate SVG for the hero if possible. 😂 
[Screenshot of Collections page](https://user-images.githubusercontent.com/12852862/116799342-28b7a700-ab2b-11eb-8ec8-8a78109c35b9.png)

**Comment by ericwbailey** [comment]
Love, love, love it 😍

**Comment by nchan0154** [comment]
Updated the PR to account for all the recent changes in the A11y Project, got my Figma skills to an acceptable level to make a new hero SVG. The only work left should be editorial (adding more appropriate copy for the existing collection & coming up with existing collections).
Paging my dear friend @mxmason

**Comment by mxmason** [comment]
This is going on my todo list for tomorrow, but things look great at a glance! Thank you, Nic!

**Comment by mxmason** [comment]
@nchan0154, @ericwbailey: 

would it help to descope this work a little bit, then follow up with a separate PR? I think we could call this the Logic PR, and ship without exposing the "collections" link in the navbar; then we could follow up by creating collections and critiquing some copy.

the alliteration is free, you're welcome

**Comment by SaptakS** [comment]
I agree that we should merge this as a feature PR, and then create separate PRs for creating collections. That sounds like a good plan to me.

**Comment by ericwbailey** [comment]
@nchan0154 This is incredible stuff, thank you so much for doing the work, as well as running incorporating our Eleventy update work! I seriously cannot thank you enough.

@SaptakS, @mxmason I'm also on board with merging this as feature work, the building from there. I'll merge https://github.com/a11yproject/a11yproject.com/pull/1235 in with a co-approval. I also hope y'all feel empowered to merge work in when there's consensus amongst maintainers 🙂
