### ISSUE TITLE
Understanding vestibular disorders - "Page not found"

### ISSUE THREAD

**Issue by rileyorr** [a11yproject/a11yproject.com#1109]
Please review our Contributing guidelines:
https://a11yproject.com/contributing-guidelines/

## Summary

I navigated to the ["Understanding vestibular disorders"](https://www.a11yproject.com/posts/understanding-vestibular-disorders/) webpage from an outside resource and see a "Page not found" error. 

### Expected result

I expected to see a page with content relating to vestibular disorders.

### Actual result

The resulting webpage shows a 404 error (screenshot attached below).
<img width="1088" alt="Screen Shot 2020-09-17 at 11 45 00 AM" src="https://user-images.githubusercontent.com/46329147/93494619-393c4980-f8db-11ea-904a-b0eb7129855c.png">

### Additional Information

> To help us try and reproduce the issue, please provide the following information:
> 1. What device were you using? (laptop, phone, tablet, etc.)
   Macbook Pro
> 2. Operating System version.
   macOS Catalina
> 3. Browser(s) and version(s).
   Google Chrome
> 4. Assistive technology used (if applicable)
   N/A

**Comment by ericwbailey** [comment]
@rileyorr Thanks for the head's up! I think we've fixed this via https://github.com/a11yproject/a11yproject.com/pull/1110. Please re-open the issue if that's not the case.
