### ISSUE TITLE
Article wanted: CSS that affects the accessibility tree

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#1112]
This is something that's not commonly known. The post does not have to get too deep into the details, just centralize CSS properties that can affect assistive technology.

**Comment by matuzo** [comment]
I'd love to write that article.

I'm on vacation now for 2 weeks. When I come back, I'll post some ideas, ok?

**Comment by ericwbailey** [comment]
Heck yeah, thank you!

**Comment by ericwbailey** [comment]
Closed for inactivity.
