### ISSUE TITLE
The A11Y Project is not participating in Hacktoberfest

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#1117]
Due to [the phenomenon of high volume, low quality PRs being generated from Hacktoberfest](https://blog.domenic.me/hacktoberfest/) in order to get free teeshirts, we will be marking all obvious attempts to game the system as spam and reporting them to [Digital Ocean](https://hacktoberfest.digitalocean.com/).

Attempts include, but are not limited to:

- Creating unnecessary or unwanted files, especially ones that don't map back to [an existing issue](https://github.com/a11yproject/a11yproject.com/issues).
- Commits that add extraneous words in existing files, especially site documentation.
- Files uploaded via GitHub with no context.
- Minor cosmetic changes and self-described improvements to documentation that don't actually improve our content.
- Localization attempts that fork the site and do not provide mechanisms for our team to ensure translated content is up to date.

Rejections are in-line with policies outlined in our existing [Contributing Guidelines](https://www.a11yproject.com/contributing-guidelines/#promotions-partnership-deals-and-seo-scams).

We hope that this does not affect new participants interested in making constructive contributions to our project. Issues labeled labeled as a ["Good First Issue"](https://github.com/a11yproject/a11yproject.com/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22) are a great starting point for working with the project in a meaningful way. If you are looking for a good resource for contributing effectively to a project that participates in Hacktober, [Monica Powell has a great guide](https://www.aboutmonica.com/blog/set-yourself-up-for-success-open-source-contributions).

Tagging @digitalocean as a datapoint for future considerations on the impact of Hacktoberfest. It is our hope that they provide better mechanisms for future versions of the event as to not cause undue stress on Open Source maintainers.

**Comment by isatrio** [comment]
Hi @ericwbailey and @davatron5000 ,

So, it's me Yudhi who contacted you @davatron5000 at Twitter. I'm one of the maintainer a11y-id community (Indonesia-based). So we planned to have resources in our local language, Bahasa Indonesia. I fully understand if a11y-project did not participate on Hacktoberfest, yes I felt this too.

If possible, we're in Indonesia will translate all content inside a11y-project to Bahasa Indonesia. We have a small group to do this. Like one day hackathon and it's collective. We will host the site to our own server and our own domain. We will fork the repo and start from there to translate to our language.
