### ISSUE TITLE
Focused state of highlighted resources card has insufficient contrast

### ISSUE THREAD

**Issue by hidde** [a11yproject/a11yproject.com#1127]
Please review our Contributing guidelines:
https://a11yproject.com/contributing-guidelines/

## Summary

When a user tabs to the highlighted card in the resources page, the background turns light, while the text colour stays light. This results in insufficient contrast.

### Expected result

Text colour has plenty of contrast with background colour.

### Actual result

Text colour has little contrast with background colour. 

### Additional Information

I am happy to add a fix.

**Comment by ericwbailey** [comment]
Ah, great catch, thank you. Closed via https://github.com/a11yproject/a11yproject.com/pull/1128.
