### ISSUE TITLE
Font rendering on macOS pre-11 has a bug, so it would be worth updating the Recursive font files

### ISSUE THREAD

**Issue by arrowtype** [a11yproject/a11yproject.com#1137]
## Summary

Love the site!

However, I’ve noticed that Recursive is rendering with an issue caused by the way overlaps macOS renders static fonts with overlaps, pre macOS 11.

![Font rendering issue on the A11Y project website](https://user-images.githubusercontent.com/45946693/97086930-5cea6200-15f4-11eb-89c4-a7a5046204a2.png)

A fuller explanation for font nerds is here: https://twitter.com/ArrowType/status/1311716316320018438

### Expected result

Would it be possible to update the fonts to ones without overlaps?

If you have an existing way of generating woff & woff2 subsets, running it on OTFs from here is your best bet:

https://github.com/arrowtype/recursive/tree/af83e68ef717debf50f914fc07605f43bea3a7dd/fonts/ArrowType-Recursive-1.066/Recursive_Desktop/separate_statics/OTF

If you would need some help making these subsets, I am happy to help out, too! I could match the existing subset, or adjust it if needed. I don’t want to duplicate your effort, but can do this fairly quickly if that would help. Let me know.

P.S.: Can I ask where/how you got the existing woff2 fonts with overlaps? Google Fonts, probably? I know they are still working on their scripts to generate static files from core variable fonts. But, if it’s another place, I’m happy to know so I can potentially help get updates into place to fix this. :)

Thanks!

**Comment by ericwbailey** [comment]
Thanks for the great issue description, @arrowtype. I'm a designer by trade, so this sort of info is really interesting to me! To answer your questions:

>Would it be possible to update the fonts to ones without overlaps?

Yup, definitely. I'll see what I can do about working with the link you provided. As for conversion, I use fontplop. Any objections to this form of conversion? I'm specifically trying to avoid the variable font to keep the payload size down.

>Can I ask where/how you got the existing woff2 fonts with overlaps? Google Fonts, probably?

I think I got it from [Google Webfonts Helper](https://google-webfonts-helper.herokuapp.com/fonts/recursive?subsets=latin). I believe they link to Google's font CDN, but am unsure.

**Comment by arrowtype** [comment]
Thanks for the reply, @ericwbailey!

No worries about fontplop (I'm not familiar with it, but Recursive has an OFL license, so you can do almost whatever you want to with it). If it works; sounds good! And yes, the full Recursive VF is definitely too big if you only need a style or two.

Thanks for letting me know about the origin of the statics; that makes sense. Google Fonts is still working to improve their static font generation process, but the ones in the recursive repo are less experimental and should work better here.

Let me know if any questions come up!

**Comment by ericwbailey** [comment]
So, the good news is I was able to fix this issue using static weights from your repo. The less good news is we've moved away from using Recursive. 

Thank you for such a detailed issue report, and for all your hard work on the typeface.
