### ISSUE TITLE
Wrong Link, Cross-Cultural Design book

### ISSUE THREAD

**Issue by Z33** [a11yproject/a11yproject.com#1142]
Under Resources, the book Cross-Cultural Design has the incorrect link. Is currently linked to Color Accessibility Workflows which is prior to it. 

https://www.a11yproject.com/resources/#cross-cultural-design

**Comment by ericwbailey** [comment]
Ah, thanks for finding this! Fixed via https://github.com/a11yproject/a11yproject.com/pull/1144.
