### ISSUE TITLE
Code blocks in ToC

### ISSUE THREAD

**Issue by aardrian** [a11yproject/a11yproject.com#1150]
## Summary

On mobile, inline code in the table of contents does weird wrapping.

1. Use Firefox or Chrome on Android mobile,
2. Go to https://www.a11yproject.com/posts/2019-02-15-creating-valid-and-accessible-links/,
3. Scroll down to the _Table of Contents_,
4. Admire.

### Expected result

The text flows like normal text.

### Actual result

Items with a piece of code cause wrapping of all text before the code, then the code (which also wraps), then more wrapping.

![Screenshot_20201112-212508](https://user-images.githubusercontent.com/1376607/99021116-f5a63a80-252d-11eb-9051-bea9e472a688.png)

**Comment by aardrian** [comment]
Back on a real computer, saw it affects desktop resolutions, and came back to report that _removing_ the following fixes the issue:
```
.v-toc__nav a {
    display: flex;
}
```

Then you can change the `margin` on the `<li>` from `0` to something else:
```
.v-toc__nav li {
    margin-bottom: 1em;
}
```

Whether or not you use it is up to you, but the fix in #1151 retains the flex, which may have other unforeseen consequences and is weird for inline text. It also makes for text when the code leads the new line on a wrap looks like it is indented, which is inconsistent with other items in the list and implies some different purpose.

I made screen shots of each.

With the code change from #1151:
![2020-11-13 (2)](https://user-images.githubusercontent.com/1376607/99095445-24122d00-25a3-11eb-93d9-c5e8ca14928c.png)

With the code change proposed above:
![2020-11-13 (3)](https://user-images.githubusercontent.com/1376607/99095571-4c9a2700-25a3-11eb-971a-4db14ea69f67.png)

Note how the baselines match and the wrapped text does not have the indent.

**Comment by SaptakS** [comment]
> Back on a real computer, saw it affects desktop resolutions, and came back to report that removing the following fixes the issue:

Removing flex would actually change the hover effect. The display is kept flex because of the hover effect itself. So technically I can wrap the text content inside a span or something.

> Also, when the code leads the new line on a wrap looks like it is indented, which is inconsistent with other items in the list and implies some different purpose.

This I didn't notice. Thanks for pointing that. I will look a little more to check what might work best keeping all the things intact.

**Comment by aardrian** [comment]
> Removing flex would actually change the hover effect.

I did not notice the focus effect; my bad.

**Comment by SaptakS** [comment]
https://github.com/a11yproject/a11yproject.com/pull/1151#issuecomment-727803067 should address the issues with indent and baseline for most browsers. @aardrian let me know if that seems good to you.

**Comment by aardrian** [comment]
@SaptakS Sadly I have been tied up on deadlines, so I have been unable to review.

I am assuming since you closed this that the change has been deployed. If so, I am seeing scrollbars on the <code>&lt;code&gt;</code> when using Chrome 86 and Firefox 82 on Windows 10. I did not check on my Mac nor any other device.

Chrome 86:
![2020-11-18 (2)](https://user-images.githubusercontent.com/1376607/99609478-fdf2ef80-29dd-11eb-9855-f1194c5827e7.png)

Firefox 82:
![2020-11-18 (3)](https://user-images.githubusercontent.com/1376607/99609558-267ae980-29de-11eb-9ffe-161f3d0c77bf.png)

**Comment by SaptakS** [comment]
@aardrian I don't see it in my linux machine or mobile. I will try reproducing it in a windows VM

**Comment by aardrian** [comment]
macOS 11 / Safari
![image](https://user-images.githubusercontent.com/1376607/99670210-2dd1df80-2a3e-11eb-8e01-04c2fda725b6.png)

**Comment by SaptakS** [comment]
@aardrian let me know if the above changes look better.

**Comment by aardrian** [comment]
See comment on PR. Only tested in dev tools in one browser based on my understanding of what the Sass is doing to the CSS.
