### ISSUE TITLE
Table of Contents is all-caps

### ISSUE THREAD

**Issue by aardrian** [a11yproject/a11yproject.com#1152]
## Summary

The Table of Contents that appears for some posts uses all-caps text.

1. Navigate to https://www.a11yproject.com/posts/2019-02-15-creating-valid-and-accessible-links/#further-reading
2. Scroll until you see the TABLE OF CONTENTS
3. Observe the all-caps

### Expected result

I expect mixed case or title case or sentence case, based on whatever the site's style/writer's guide defines (and or what the author wrote).

### Actual result

The text is all-caps.

### Additional Information

Generally all-caps can pose problems in the following scenarios:
* Screen readers sometimes read shorter all-caps words letter by letter, ruining meaning;
* For users who do not get the site typeface, default system font letterforms may not be  sufficient for easy reading (the 1 I L | O 0 conundrum);
* Many (most) users with dyslexia report problems with all-caps text;
* Some browsers still copy text styled with CSS to be all-caps as if it were really all-caps.

### Additional Information

Consider striking these styles completely:

```
.v-toc__nav li {
   text-transform: uppercase;
}
.v-toc__summary {
   text-transform: uppercase;
}
```

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/1154. Thanks for reporting this.
