### ISSUE TITLE
Add a license for content

### ISSUE THREAD

**Issue by faraixyz** [a11yproject/a11yproject.com#1161]
I was wondering if there's a plan to add a clear content license for the post's on the website? The AGPL seems to cover the code and it would be good to have something like a creative commons license to help folk understand how they can use the site's content.

Looks like this issue in #283 was brought up long ago, but hasn't been addressed.

**Comment by ericwbailey** [comment]
I don't feel comfortable making adjustments to a license of a website that isn't mine. I am cautious about a license that could be misconstrued as letting our content be republished elsewhere, with regards to content scrapers and other for-profit scam sites. 

Tapping @davatron5000 for his input.

**Comment by faraixyz** [comment]
Oh that makes sense. I guess it'll do fine without an explicit license then.
