### ISSUE TITLE
WW2 is not a numeronym ( nor is P2P )

### ISSUE THREAD

**Issue by nickperkinslondon** [a11yproject/a11yproject.com#1167]
Your website says that WW2 and P2P are examples of numeronymns -- but they are not.  In WW2 the "2" represents the number "2" ( not 2 missing letters ).  In P2P, the 2 is used because it is a homonym of "to", not because it replaces 2 missing letters.  P2P could only be considered a numeronym by accident.  So the only real precedent for this "numeronym" idea is "i18n" -- that's it.  ( and I always hated that form ).  In fact, I have a very hard time looking at "a11y" and seeing the work "accessibility".  It just looks like the word "ally".  Get a proper name.

**Comment by ericwbailey** [comment]
Nah.
