### ISSUE TITLE
Typographical error on Resources page.

### ISSUE THREAD

**Issue by whitingx** [a11yproject/a11yproject.com#1175]
Please review our Contributing guidelines:
https://a11yproject.com/contributing-guidelines/

## Summary

On the Resources page (https://www.a11yproject.com/resources/) there is a predominant spelling of the word ‘Accessible’ (96 matches). However, there are 5 uses of the word ‘Accessibile’.

### Expected result

To see a consistent spelling of the word ‘Accessible’.

### Actual result

A mixture of ‘Accessible’ and ‘Accessibile’ used on the page.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/1176. Thank you so much for catching and fixing this, @whitingx!
