### ISSUE TITLE
Article: [ Getting Started With Github Gists ]

### ISSUE THREAD

**Issue by Emilsone** [a11yproject/a11yproject.com#1177]
## Description

Most times we as developers might be applying for a role or so, or maybe you have a bug on your code and you want to create an issue or share your code with others to help figure out, well there is a way to work it out without

## Would you like to write the article or request that it be written?

Yes I would like to write the article

**Comment by ericwbailey** [comment]
Hey @Emilsone, thanks for volunteering to write this. While I like your idea, our site is focused on disability and accessibility. Unfortunately, I don't think it's a good fit for the kind of content we publish. 

I might suggest [dev.to](https://dev.to/) as a place to publish this.
