### ISSUE TITLE
Bug: Broken footnotes

### ISSUE THREAD

**Issue by rmleg** [a11yproject/a11yproject.com#1205]
## Summary

I noticed that the footnotes haven't been parsed from markdown [in this article](https://www.a11yproject.com/posts/2013-02-09-how-to-use-application-role/). I'm not sure if this is a site-wide problem or only for this article because none of the other articles I checked used footnotes.

### Expected result

`[^focusmode]` and `[^html]` in the article linked above should be links to footnotes at the bottom of the page.

### Actual result

The raw text of the footnote markdown syntax (e.g. `[^focusmode]`) is displayed instead, as in the screenshots below.

<img width="760" alt="Screenshot of text that should contain a footnote link but instead says [^focusmode]" src="https://user-images.githubusercontent.com/7571219/110408082-02a5e700-8053-11eb-9c1c-6caa80da8178.png">

<img width="751" alt="Screenshot of text that should contain a link back to the footnote reference but instead says [^focusmode]" src="https://user-images.githubusercontent.com/7571219/110408673-f4a49600-8053-11eb-9741-315ddb6b4270.png">

**Comment by ericwbailey** [comment]
Ah, nice catch, thank you! I think this might have broke when we moved from Jekyll to Eleventy and the Markdown parser changed. I'll take a look at it.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/1216. Thank you again for reporting this!
