### ISSUE TITLE
Article: Why Learning Experience Designers should champion accessibility 

### ISSUE THREAD

**Issue by maryvillela** [a11yproject/a11yproject.com#1214]
## Description

>A brief description (2-3 sentences) of your proposed article. Why should this article be written, and how does it fit on The A11Y Project? I want to encourage Learning Experience Designers and Instructional Designers to learn about accessibility and start applying accessibility practices in their trainings and learning components ASAP. Many large companies are investing in UX research and deliver accessible products to their customers. However, we still have a long way to go in making our corporate learning experiences accessible. I am looking for a platform where I can write about this topic as an experienced LXD and share with people in my field. 

## Would you like to write the article or request that it be written? I'd like to write it, but if anyone from your organization feels more qualified to do so, perhaps I can just send my ideas for consideration. I don't code, so I would understand if you'd like to go for that route. 

>Are you posting this as a means to look for help on the topic or do you have a method you've developed/tested to solve the issue/topic? Yes, I am a Sr. Learning Experience Designer at Amazon currently working in standardizing practices for accessibilities particularly in eLearning authoring.

**Comment by ericwbailey** [comment]
Hi @maryvillela, sounds like an interesting subject! If you prefer to work in Word, Google Docs or the like, we can work with that. Can you please [send us a message](https://www.a11yproject.com/contact/) so we can figure out how to work together?

**Comment by ericwbailey** [comment]
Messaging with @maryvillela to create and edit this article via email/Google Docs. Closing.
