### ISSUE TITLE
Rendering issue on checklist page on mobile

### ISSUE THREAD

**Issue by devinjameson** [a11yproject/a11yproject.com#1218]
## Summary

1. Go to https://www.a11yproject.com/checklist/ on mobile
1. Scroll down to the Animation section

### Expected result

The "prefers reduced motion" section renders like the other sections.

### Actual result

The section renders differently, perhaps because of the long string of characters in "prefers-reduced-motion."

![image](https://user-images.githubusercontent.com/39350030/112002912-c4023900-8af6-11eb-9af1-b1d9a7182fbc.png)

### Additional Information

iOS, Safari, iPhone 12 Pro

**Comment by SaptakS** [comment]
I am taking a look at this.
