### ISSUE TITLE
Inaccurary: readme mentions info about Jekyll instead of Eleventy

### ISSUE THREAD

**Issue by clottman** [a11yproject/a11yproject.com#1229]
## Summary

The readme mentions that after you run `npm start`, you'll see some output from Jekyll, but it should say you'll see some output from Eleventy. 

### Expected result
The readme should say: 
> Your command line application will then display some information about Jekyll,

### Actual result
The readme currently says:
> Your command line application will then display some information about Jekyll,

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/1230, thank you for submitting the fix! We're also always looking to make the setup process as easy as possible, so definitely let us know if you run into any obstacles while setting things up.
