### ISSUE TITLE
Article: Section 508 for Web Designers

### ISSUE THREAD

**Issue by davatron5000** [a11yproject/a11yproject.com#123]
Started writing an article on Section 508 and how it specifically relates to web design.

https://gist.github.com/f2b8ad70543a95018d9f

Looking for feedback over there on the `??` questionable things (like I wouldn't even recommend these in modern web design) or I can't find a clever way to simplify what they're talking about.

**Comment by svinkle** [comment]
![](https://user-images.githubusercontent.com/1392632/29992910-fd2cb9fc-8f74-11e7-8aac-00820b8572b2.gif)

This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @davatron5000, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
