### ISSUE TITLE
Article Feedback: How to create accessible forms

### ISSUE THREAD

**Issue by nchan0154** [a11yproject/a11yproject.com#1234]
I was just catching up on recent commits in my Github feed and found the [how to create accessible forms article](https://www.a11yproject.com/posts/2020-09-19-how-to-write-accessible-forms/) by @HarcourtHamsa (thank you for writing this excellent primer!) I was wondering if it may be a good idea to add a section on [Understanding Success Criterion 1.3.5: Identify Input Purpose](https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose) and the use of [autocomplete](https://www.w3.org/WAI/WCAG21/Techniques/html/H98) attributes as a technique to achieve it as it tends to be a bit lesser known of a success criterion. Happy to help draft if you are busy, just let me know!

**Comment by HarcourtHamsa** [comment]
Sure I can add a few more sections. But it’ll have to be sometime next
week. Is that ok?

**Comment by Victorybrown** [comment]
Is this issue open?

**Comment by mxmason** [comment]
Hi, @Victorybrown! I'm glad you're interested in this issue; I was just thinking about it, myself. If you'd like to tackle this feedback, please go go ahead!

**Comment by Victorybrown** [comment]
Alright, thank you. If I understand correctly, the article https://www.a11yproject.com/posts/2020-09-19-how-to-write-accessible-forms/ is written and all I have to do is add the new sessions written there to the last part?

**Comment by ericwbailey** [comment]
@Victorybrown Yup!

**Comment by ericwbailey** [comment]
Closed for inactivity.
