### ISSUE TITLE
Checklist data: add headings and information into the JSON

### ISSUE THREAD

**Issue by shawnthompson** [a11yproject/a11yproject.com#1238]
I would like to add the section headings and paragraph information from the [Checklist](https://www.a11yproject.com/checklist/) page into the [checklists.json](https://github.com/a11yproject/a11yproject.com/blob/main/src/_data/checklists.json).

See if there's a way to pull as much data into with a nunchucks `for`.

```	
	<h2 id="content" class="c-heading-large">
		Content
	</h2>
	<p class="c-preface">
		Content is the most important part of your site.
	</p>
	<div class="c-card__wrapper">
		{% set checklist = checklists.content %}
		{% for checklist in checklist %}
			{% include "checklist.njk" %}
		{% endfor %}
	</div>
```

**Comment by ericwbailey** [comment]
Sounds great! Go for it!

**Comment by mxmason** [comment]
Hey, @shawnthompson! I think we had similar ideas right around the same time! If I understand correctly, my work in #1268 implements the changes you're describing here. We now generate the heading and preface for each part of the checklist by reading `checklist.json`!

**Comment by shawnthompson** [comment]
Yeah this is exactly what I was thinking... great work!
