### ISSUE TITLE
Question: Accessible Boilerplate

### ISSUE THREAD

**Issue by m0bileDev** [a11yproject/a11yproject.com#125]
I really like the idea, the project and the everything it stands for. I look forward to contributing but I have one question. Do you think it would serve the developer / community better if A11 Project has a Section 508 Boilerplate?  Similar to HTML5Boilerplate? Just how each line of code is explained in the HTML5 Boilerplate so can lines of code be explained in section 508 Boilerplate.

The site http://www.w3.org/WAI/demos/bad/   show annotations and side-by-side comparisons which helped me convey the point to other developers unfamiliar with WCAG 2.0. 

I just think having a Section 508 Boilerplate would be an awesome tool in anyone's toolkit. Help other developers retrofit their website. Lead the charge in best practices for accessibility. Include things such as "Skip to Content" skip links that only show on :focus, or hidden TOCs or other practices developers do when making a 508 accessible site.

Perhaps also incorporate practices from http://webaim.org/.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @m0bileDev, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
