### ISSUE TITLE
`npm install` script fails on npm@7

### ISSUE THREAD

**Issue by mxmason** [a11yproject/a11yproject.com#1252]
## Summary
Starting with npm version 7, npm is stricter about peer dependencies. This causes problems in our build scripts.

### Expected result
Running `npm start` in the dev console successfully starts the dev environment for the project.

### Actual result
The script throws an error.
```bash
Error: ENOENT: no such file or directory, scandir '/Users/elias/Projects/a11yproject/node_modules/node-sass/vendor'
```

The [gulp-sass install instructions](https://github.com/dlmanning/gulp-sass#install) specify to install node-sass as a direct peer dependency, so we should do that. This will have no impact on environments running npm 6, but will future-proof us for later.

**Comment by SaptakS** [comment]
I would actually have prefered that we move away from node-sass to dart-sass maybe since the sass team has deprecated the use of node-sass: https://sass-lang.com/blog/libsass-is-deprecated

**Comment by mxmason** [comment]
Just saw this, @SaptakS! Thanks for that link; I didn’t know about the deprecation.

I can see about migrating to dart-sass!
