### ISSUE TITLE
Article: Quick Tip: Check mobile accessibility

### ISSUE THREAD

**Issue by thomassjogren** [a11yproject/a11yproject.com#126]
This idea came to me after I went into my iPhones accessibility options and started to try some of them out. The VoiceOver works really good and I think (as a quick tip) to let people know that accessibility is still important for mobile web pages.

You can read and leave feedback here : https://gist.github.com/4633248

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @thomassjogren, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
