### ISSUE TITLE
Bug: Table of Contents is generated when no headings are present

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#1267]
Example: https://www.a11yproject.com/announcements/2021-04-04-ten-dollars-for-ten-k/

Currently, the Table of Contents heading is listed, even if there are no headings in the post content. We need to update this to not be shown, as there is no content present to navigate to using this component.

**Comment by mxmason** [comment]
I'd like to claim this, if that's alright. I realized recently that we could (and, IMO, should) generate the table of contents during build, rather than on the client. I have ideas about how we can do this, but it may take some work

**Comment by ericwbailey** [comment]
Go for it, I'd love to do this on build and spare the client the work.
