### ISSUE TITLE
Bug: When "table" tab is clicked on table of contents, it navigates to "content" section.

### ISSUE THREAD

**Issue by D-Antonelli** [a11yproject/a11yproject.com#1274]
> "Tables" tab on the table of contents navigate to the "content" section instead of the "tables" section. 
>
> Example:
> 1. Go to https://www.a11yproject.com/.
> 2. Find the "tables" tab on the table of contents.
> 3. Click tables
> 4. Link navigates to https://www.a11yproject.com/checklist/#content 

### Expected result

> Link should navigate to the "tables" section.

### Actual result

> Link navigated to the "content" section.

### Additional Information

> 1. Browser: Google Chrome Version 90.0.4430.93 (Official Build) (64-bit)

**Comment by danielmatthew** [comment]
True for all generated links. "Success criteria", "Does this checklist…", "Next Steps", and "Further Reading" are unaffected.

**Comment by danielmatthew** [comment]
I suspect https://github.com/a11yproject/a11yproject.com/issues/1271 will resolve this

**Comment by mxmason** [comment]
Closing as resolved in #1271. Thank you for reporting, @D-Antonelli!
