### ISSUE TITLE
Resource link is directing to an adult website

### ISSUE THREAD

**Issue by jaredcunha** [a11yproject/a11yproject.com#1278]
Please review our Contributing guidelines:
https://a11yproject.com/contributing-guidelines/

## Summary

The last link in the resources section, "Web Accessibility Guide," might either be hacked or its URL is now owned by an adult website. In either case, might be worth removing the link.

<img width="791" alt="Screen Shot 2021-05-12 at 2 48 12 PM" src="https://user-images.githubusercontent.com/1094951/118029106-d26c1480-b331-11eb-8146-295a4890be77.png">

### Expected result

An accessibility guide.

### Actual result

An adult website.

**Comment by ericwbailey** [comment]
Thanks for reporting this. The site was removed in https://github.com/a11yproject/a11yproject.com/pull/1276/files#diff-f3710cf394b62ec86dc5f637281e383050f7a3552ff48271238fc7d1a2a17a86L1940, you may need to refresh the page to see an update.
