### ISSUE TITLE
Article: Accessibility and SEO

### ISSUE THREAD

**Issue by chollma** [a11yproject/a11yproject.com#1286]
## Description

> This topic is on the list of posts you'd like to see written. I'm a technical SEO by trade and someone who's passionate about developing digital products that are fast, sustainable and accessible by default. This article would cover the intersection of SEO and Accessibility work and how breaking the cycle of exclusion will also lead to durable and long-lasting SEO performance.

## Would you like to write the article or request that it be written?

I'm happy to write the article.

**Comment by ericwbailey** [comment]
Sounds great! Looking forward to reading it 🙂

**Comment by chollma** [comment]
@ericwbailey, I'm about 75% done with this. It's taking me extra time to ensure my writing aligns with your contribution style guide.

**Comment by ericwbailey** [comment]
@chollma Thanks for the head's up—I'm happy to wait until you think its in a good place. Is there anything with the Contribution Guide you need help or clarification with?

**Comment by chollma** [comment]
Nope! It is very well written. It's just been hard to find the time and space lately.

Article is written and edited down. I want to polish it a bit more, but it will be in your hands by the weekend.

I appreciate your patience.

- CH
