### ISSUE TITLE
Article:  HOW TO: Accessible heading structure

### ISSUE THREAD

**Issue by rianrietveld** [a11yproject/a11yproject.com#1287]
## Description
How to set up an accessible heading structure in a web page.

Addressing:
- Headings are the framework of the content of a web page
- Screen reader navigation by headings
- Why only one H1, and what should it be (also referring to the always reoccurring outline-HTML5 discussion)
- A heading should represent the content below and not stand alone
- Don't skip a heading level
- Good heading text
- Debunking some headings and SEO myths.
- Browser add-ons to quickly check heading structure

## Would you like to write the article or request that it be written?

I would like to write the article.

Link to pull request with the content: [#1391](https://github.com/a11yproject/a11yproject.com/pull/1391)

**Comment by ericwbailey** [comment]
Looking forward to this one 🙂

**Comment by ericwbailey** [comment]
@rianrietveld Is this something you're still interested in writing?

**Comment by rianrietveld** [comment]
@ericwbailey It took some time, but here it is, the How-to on headings is ready for review.
https://github.com/a11yproject/a11yproject.com/pull/1391

**Comment by rianrietveld** [comment]
Published : https://www.a11yproject.com/posts/how-to-accessible-heading-structure/

**Comment by rianrietveld** [comment]
@ericwbailey, I wrote an update for this post in https://github.com/a11yproject/a11yproject.com/pull/1456
