### ISSUE TITLE
Article: Firefox and Accessibility

### ISSUE THREAD

**Issue by colabottles** [a11yproject/a11yproject.com#1291]
## Description

The reasons why Firefox is a great tool for testing for accessibility, what features there are (and can be added), great experimental features, and reasons to incorporate Firefox as an automated testing tool in one's accessibility testing toolkit. 

I use Firefox in my auditing and I think it's very under-utilized, overlooked as a valid testing tool. I also have not seen it written about and saw it on a checklist of items that would be good topics.

## Would you like to write the article or request that it be written?

I would write it.

>Are you posting this as a means to look for help on the topic or do you have a method you've developed/tested to solve the issue/topic?

I have a method to solve the issue/topic.

**Comment by colabottles** [comment]
Will be starting this after my travel day.

**Comment by ericwbailey** [comment]
@colabottles Is this something you're still interested in writing?

**Comment by colabottles** [comment]
@ericwbailey Yes. I have the article halfway done. There's just been a lot going on personally that has pulled me away from it.

I'll keep working on what I have and share it with you soon.

**Comment by colabottles** [comment]
Just leaving an update @ericwbailey that I am working on this and am halfway through the content I'll have for this.

**Comment by colabottles** [comment]
@ericwbailey Do we want to close this issue now or after the announcement?

**Comment by ericwbailey** [comment]
@colabottles I'll close it now. Thank you for the nudge, and also for the fantastic article! 🎉
