### ISSUE TITLE
Desktop - Chrome - site can't be reached

### ISSUE THREAD

**Issue by AliciaJarvis** [a11yproject/a11yproject.com#1312]
## Summary

> Brief description of the issue. Please identify specific steps.
>
> 1. Open Chrome.
> 2. Go to a11yproject.com.

### Expected result

> Site to appear.

### Actual result

> Error - site cannot be reached
![image](https://user-images.githubusercontent.com/13350810/126727536-b544b7f2-0e07-4f08-b4e5-0e14f8526d30.png)

### Additional Information

> To help us try and reproduce the issue, please provide the following information:
> 1. What device were you using? (laptop, phone, tablet, etc.) - Desktop
> 2. Operating System version. - Windows 10
> 3. Browser(s) and version(s). - Chrome version 91.0.4472.164 (Official Build) (64-bit)
> 4. Assistive technology used (if applicable) - N/A

### Additional Information

Note anything else you think would be important to know that didn't fall into an above category.

**Comment by scottaohara** [comment]
might have encountered a hiccup in service?   i can't reproduce in any browser.
are you still encountering this?

**Comment by SaptakS** [comment]
I would guess the same. It works in all browsers I checked.

**Comment by ericwbailey** [comment]
Likewise. This is troubling, though. [Netlify is showing no issues for the past few days](https://www.netlifystatus.com/), so maybe it's an ISP issue?

**Comment by SaptakS** [comment]
ISP or DNS is my guess 🤔
