### ISSUE TITLE
Article Follow-up: Everyday Accessibility

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [a11yproject/a11yproject.com#1321]
I now have posters and a video version of the article. 
Posters: https://mawconsultingllc.files.wordpress.com/2021/07/everyday-accessibility-posters.pdf
Video: https://www.youtube.com/watch?v=xPU-dJPumnc

I've posted them to my blog (https://mawconsultingllc.com/2021/07/29/everyday-accessibility/) but figured they could also be linked on the article here.

**Comment by ericwbailey** [comment]
Hi @MicheleAWilliams-A11y! I just merged in both a YouTube video embed and a link to download the poster set. We're using the URL you provided for the download, so let us know if it ever changes.

Also more than happy to move things around or rephrase them for your post, if you want.
