### ISSUE TITLE
Article: using NFTs to democratise the art sector

### ISSUE THREAD

**Issue by avahal** [a11yproject/a11yproject.com#1324]
Hi, I'd like to an article on how using new technologies such as NFTs can be a valuable tool for disabled artists and collectors to make the art world more accessible. I would draw on my experience as the founder of ARTXV, a collective that assists disabled artists to sell their work as NFTS, the ways that NFTs increase accessibility and security for disabled artists through blockchain technologies but also the improvements that need to be made with NFT platforms and procedures to increase accessibility.

I have experience with explaining these topics to people who are both new to NFTs and blockchain and who have a variety of technical experience and cognitive abilities. I usually do this 1:1 so I think it would be nice to have this on a public forum for others to read and learn about.

**Comment by ericwbailey** [comment]
Thanks for the article pitch, @avahal. This idea seems more inline with artist monetization, not digital accessibility and feels out of scope of content we'd cover. If you are looking for alternate publications, the [dev.to](https://dev.to/) community might be a good fit.
