### ISSUE TITLE
Article: Reviewing a design for accessibility

### ISSUE THREAD

**Issue by SteveBarnett** [a11yproject/a11yproject.com#1327]
## Description

A short checklist to use when reviewing a design for accessibility (to help designers), and ideas for annotating it (to help developers).

Probably these things:

1) The **page title** is unique and describes page content.
2) All **images** (including icons) have alt text.
3) **Headings** are used liberally and no levels are skipped.
4) **Links or buttons** with the same text, repeated on a page have a longer accessible name that's unique (e.g. 'View details of Quarterly review Q1' instead of just 'View details').
5) **Groups of related forms controls** (e.g. multiple choice, data selector) have a name (visible or not) that provides context for the individual questions in the group (e.g. a legend).
6) **Form controls** (one input plus one label) have a name (visible or not).
7) Any **error messages** are clear and helpful.
8) **Standard controls** are much better for accessibility.

(I've previously posted this to my current employer's [public dev docs](https://help.totaralearning.com/display/DEV/UX+a11y+summary))

## Would you like to write the article or request that it be written?

I would like to write it :)

**Comment by ericwbailey** [comment]
We'd love this! Thank you for pitching it. Do you have everything you need to get started?

**Comment by SteveBarnett** [comment]
Yay, that's great news!
Yes, I'm all set, thank you. I'll get going on it! :)

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/1332.
