### ISSUE TITLE
Article: Introduction to Orca on Gnome Desktop Environment

### ISSUE THREAD

**Issue by nibble0101** [a11yproject/a11yproject.com#1335]
## Description

I have been toying with Orca screen reader on Gnome desktop Environment for a while. I have realized not much has been written about it apart from the official documentation. I believe a short Introductory article on how to start using Orca on Gnome and Ubuntu will be useful on https://www.a11yproject.com.

## Would you like to write the article or request that it be written?

I would love to write the article.

**Comment by ericwbailey** [comment]
This would be amazing, thank you!
