### ISSUE TITLE
Article: Using focus style for accessibility

### ISSUE THREAD

**Issue by Emilsone** [a11yproject/a11yproject.com#1347]
Hi @ericwbailey, I would love to write on this topic - Using focus style for accessibility
## Description

While accessing any digital interface, a focus indicator is important it highlights the active intractable component in a webpage. In this article, you will learn how to make your website accessible with a focus style

A focus indicator is necessary because some people use a mouse or a touch device to access a website, some rely on using a keyboard to navigate on a website. having a focus indicator will improve the usability of your website and make it accessible

## Would you like to write the article or request that it be written?

I would love to write this article

**Comment by Emilsone** [comment]
Hi, @ericwbailey please can you kindly review the changes I made?

**Comment by ericwbailey** [comment]
@Emilsone You have pushed this PR to your own fork of the repo, and not this one. Additionally, I am still seeing the issues that I commented on present. I will review this post once it is pushed up to the appropriate location and the issues are addressed.

**Comment by ericwbailey** [comment]
Closed for inactivity.
