### ISSUE TITLE
Article: [Nested interactive elements accessibility]

### ISSUE THREAD

**Issue by gaurav5430** [a11yproject/a11yproject.com#1348]
## Description

>A brief description (2-3 sentences) of your proposed article. Why should this article be written, and how does it fit on The A11Y Project?

The article would discuss why having nested interactive elements in the markup is a problem for accessibility. This article would mostly talk about this issue in the web (HTML + js) context
- what is the issue?
- why /when can it happen?
- some proposed solutions with links to existing resources / discussions.

This article should be written to apprise developers / designers about issues with nested interactive elements, and how they can solve them by paying a bit more attention initially.

## Would you like to write the article or request that it be written?

I would like to write an article (but also get the discussed solutions verified by other people)

>Are you posting this as a means to look for help on the topic or do you have a method you've developed/tested to solve the issue/topic?

I have a few patterns /exmaples which can solve the issue

**Comment by ericwbailey** [comment]
Sounds great! Looking forward to reviewing it.

**Comment by ericwbailey** [comment]
Closed for inactivity.
