### ISSUE TITLE
Safari 15.0 inherits harsh/failing UI Theme-color

### ISSUE THREAD

**Issue by coburnicus** [a11yproject/a11yproject.com#1349]
## Summary

The updated Safari (15.0) allows for the app UI color to be set by the website. Currently on a11yproject.com this is a pretty harsh Magenta with white type. That would seem to be pretty harsh to look at, and seems to fail WCAG contrast tests.

### Expected result

Something the passes WCAG contrast tests while adhering to A11yProject branding.

### Actual result

A lot of hot hot pink.
![pretty_in](https://user-images.githubusercontent.com/743929/135323126-777a8467-2a1c-4380-85d2-5932c491ea9f.png)

### Additional Information

This would seem to affect safari on desktop and mobile, and chrome on android. 
I'm created a fork with a potential fix. Hope I am being helpful. I really appreciate the work people put into this website. I kind of suck at git, so bear with me.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/1350
