### ISSUE TITLE
Inaccuracy: Link to Alex Brenon's Site is Inappropriate

### ISSUE THREAD

**Issue by fizzboop** [a11yproject/a11yproject.com#1385]
The website link for Alex Brenon on the Authors page leads to a pornographic site.

**Comment by SaptakS** [comment]
I am able to confirm the behaviour. @alexroseb  is http://alexroseb.com still the correct link? cc @ericwbailey

**Comment by alexroseb** [comment]
Oh no!! I’m not sure what happened but please take it off the site for now. I’ll update when I know what’s going on.

**Comment by fizzboop** [comment]
@alexroseb: Thank you for looking into it. I just happened to notice this and didn't want others to stumble on it either.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/1386. 

@fizzboop Thank you for reporting this, and apologies for the experience.
