### ISSUE TITLE
Page not found - An in-depth guide to aria roles

### ISSUE THREAD

**Issue by heyitstay11** [a11yproject/a11yproject.com#1395]
## Bug description

> Twitter handle The A11y Project posted a tweet with link to post Background : an in-depth guide to aria roles, Duncan Jimbo 
Link to the post redirects to 404 page 
the link : 
https://www.a11yproject.com/posts/indepth-guide-to-aria-roles/

## Expected outcome

>  Post: In-depth guide to aria roles

## Steps to reproduce

> Navigate to link: https://www.a11yproject.com/posts/indepth-guide-to-aria-roles/

## Technical info
Maybe the link is not right

###  What device were you using when you encountered the bug?
> Phone (Chrome)

## Terms

- [ * ] I have read, and agree to follow this project's [Code of Conduct](https://www.a11yproject.com/code-of-conduct/)

**Comment by heyitstay11** [comment]
Found the Working link: https://www.a11yproject.com/posts/an-indepth-guide-to-aria-roles/

**Comment by ericwbailey** [comment]
Thanks for reporting this, and for locating the working link! I've just pushed up a fix via https://github.com/a11yproject/a11yproject.com/commit/f0b450ad9a010d0f945d4d33cca513bce2dc7422.
