### ISSUE TITLE
Article: Accessible HTML structure using ARIA landmark regions

### ISSUE THREAD

**Issue by GeorgeArgyrousis** [a11yproject/a11yproject.com#1403]
## Your idea

How to introduce an accessible HTML structure using semantic landmark tags.

Topics analysed:
- Explain the importance of landmarks
- How they are used in conjunction with assistive technologies
- Identify the exhaustive list of HTML landmarks tags along with their implicit role attribute
- Enhanced screen reader announcements and identification of regions using landmarks (`role="..."`) in combination with `aria-label`

I've written an [article with a similar name on Medium.com](https://levelup.gitconnected.com/build-an-accessible-html-structure-using-aria-landmark-regions-and-headings-4647d22c2cc7) regarding the correct usage of semantic HTML landmark regions.

I would be more than happy to further enhance the original article with additional details. The aforementioned article also includes correct usage of the HTML heading (`h1` - `h6`) that will not be included in this article since it is already addressed (#1391).

## Terms
- [x] I have read, and agree to follow this project's [Contributing Guidelines](https://www.a11yproject.com/contributing-guidelines/)
- [x] I have read, and agree to follow this project's [Content Style Guide](https://www.a11yproject.com/content-style-guide/)
- [x] I have read, and agree to follow this project's [Code of Conduct](https://www.a11yproject.com/code-of-conduct/)

**Comment by scottaohara** [comment]
The a11yproject already has this post: https://www.a11yproject.com/posts/aria-landmark-roles/ which covers landmarks.  Have you reviewed that yet to compare overlaps / potential information that might need to be updated?

**Comment by GeorgeArgyrousis** [comment]
> The a11yproject already has this post: https://www.a11yproject.com/posts/aria-landmark-roles/ which covers landmarks. Have you reviewed that yet to compare overlaps / potential information that might need to be updated?

You are correct. The information in the post is relevant and clear. Closing issue.
