### ISSUE TITLE
Recent posts are no longer being displayed on the homepage

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#1404]
Prior to our Eleventy update a list of the latest 3 posts was listed on the homepage. Post update that functionality appears to be not working.

**Comment by ericwbailey** [comment]
@mxmason My brain is a little mush and the source of the bug is lost on me. Would you be up for pairing on this at some point?

**Comment by mxmason** [comment]
I can take a look tonight, and if the issue takes me more than 10 minutes, we can absolutely put our heads together. Once again, sorry for the mess.

**Comment by ericwbailey** [comment]
No rush on my account. I'm more burnt to the point where I'm mad at myself that I can't put 2 and 2 together.
