### ISSUE TITLE
Post: A Beginner's Guide to ADA Web Compliance

### ISSUE THREAD

**Issue by jasonmartinez1** [a11yproject/a11yproject.com#1405]
Thank you for your interest in writing a post! Please fill out the following information:

A Beginner's Guide to ADA Web Compliance

> Please describe the post you'd like to write in 2–4 sentences, and how that post would be a good match for The A11Y Project.
I wasn't able to find a beginner's guide on the topic and I believe it's a much needed post for A11y Project. It isn't a cutting edge blog topic but fundamental to A11y's mission. Without a beginner's guide to ADA Web Compliance on the A11y site, the organization may not be able to reach to users who are new to the space or users who are just being introduced to accessible web design.
## Additional information (optional)

> Is there anything else we should know?

## Terms
- [X] I have read, and agree to follow this project's [Contributing Guidelines](https://www.a11yproject.com/contributing-guidelines/)
- [X] I have read, and agree to follow this project's [Content Style Guide](https://www.a11yproject.com/content-style-guide/)
- [X] I have read, and agree to follow this project's [Code of Conduct](https://www.a11yproject.com/code-of-conduct/)

**Comment by ericwbailey** [comment]
Hey @jasonmartinez1! Thanks for your interest in writing for us. Could you share a little more detail about your definition of what ADA Web Compliance is? 

I do think a beginner's perspective on the topic would be a lovely addition to the site.

**Comment by jasonmartinez1** [comment]
@ericwbailey Of course! ADA Web Compliance is the guideline/framework for making websites and other digital properties accessible to users with disabilities. This framework must closely align with ADA legislation; otherwise, it can result in significant penalties for businesses in the US. Some examples of compliance would be good color contrast between web elements, descriptive alt-text, and legible headings/text. There's so much more to making a website accessible, but those are just a few key examples of accessible implementations. Let me know what you think and if you are still interested.

**Comment by ericwbailey** [comment]
@jasonmartinez1 Excellent, thank you for the clarification. I have seen people sometimes confusing the distinction between Section 508, WCAG, and the ADA. We're definitely still interested in the post, especially if you can speak to helping to explain away this confusion!

**Comment by jasonmartinez1** [comment]
That's an excellent point, and I think making the distinctions between each is something that can fit naturally within the theme of the article!

**Comment by ericwbailey** [comment]
Closed for inactivity.
