### ISSUE TITLE
[Bug] Footer - Incorrect Year

### ISSUE THREAD

**Issue by sarah-peacock** [a11yproject/a11yproject.com#1413]
Thank you for reporting a bug. Please fill out the following information:

## Bug description

> Date in footer is not current. Says "2013–2021"

## Expected outcome

> Current date, 2013–2022

## Steps to reproduce

> Scroll to bottom of the page ;)

###  What device were you using when you encountered the bug?

> Laptop

### What operating system were you using? What version is the operating system?

> Ex: Mac 12.1 (21C52)

### What web browser were you using? What version is the web browser?

> Chrome 98.0.4758.80 (Official Build) (x86_64)

### Assistive technology and version (optional)
> no

## Additional information

> NA

## Terms

- [yes] I have read, and agree to follow this project's [Code of Conduct](https://www.a11yproject.com/code-of-conduct/)

**Comment by ericwbailey** [comment]
Thanks for reporting this, @sarah-peacock!
