### ISSUE TITLE
[Bug] Scrolling with Vimium browser extension not working

### ISSUE THREAD

**Issue by SimonEggert** [a11yproject/a11yproject.com#1416]
At first, I want to say thank you for the great work on a collection about this important topic!

## Bug description

When trying to navigate the site with vimium, scrolling does not work as intended, i.e. pressing `J` or `K` are not doing anything.

## Expected outcome

The page should scroll down/up.

## Steps to reproduce

1. Install vimium ([Chrome](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb) / [Firefox](https://addons.mozilla.org/de/firefox/addon/vimium-ff/))
2. Press `J` or `K` on a11yproject.com

###  What device were you using when you encountered the bug?

Desktop

### What operating system were you using? What version is the operating system?

macOS 12.2.1

### What web browser were you using? What version is the web browser?

Occurs in Chrome and Firefox.

## Additional information

I did a little digging and this seems to happen because of the following line:
https://github.com/a11yproject/a11yproject.com/blob/46e5c5e379ea704ae9e2df23a45d563ba15ca1e7/src/css/base/_html.scss#L16

It was added in 2015 via https://github.com/a11yproject/a11yproject.com/commit/82a9ae928b292b475c705e8adb7970434a419201 to
> keep page centred in all browsers regardless of content height.

Is this workaround still necessary or can we get rid of it to fix the above issue? In my understanding the `<body>` will be the scrollable container on the page, so setting it on `<html>` feels hacky and counterproductive.

## Terms

- [x] I have read, and agree to follow this project's [Code of Conduct](https://www.a11yproject.com/code-of-conduct/)

**Comment by ericwbailey** [comment]
Hey @SimonEggert, thanks for the kind words, and the thorough issue report! I have a potential fix up in https://github.com/a11yproject/a11yproject.com/pull/1417, but cannot get it to scroll using the <kbd>J</kbd> and <kbd>K</kbd> keys. I'm also not an experienced Vimium user, although I understand its significance in this context 😅

I'm using the latest macOS, Firefox, and Chrome. Would you mind pulling down the branch and confirming one way or the other on your end?

**Comment by SimonEggert** [comment]
@ericwbailey Thanks for looking into the issue. I checked out #1417 and it fixes the problem on my side :+1:

Weird that it is not working for you, though. Maybe my description was a bit ambiguous: the shortcuts are actually lowercase (`j` and `k`). Let me know if I can assist any further :slightly_smiling_face:

**Comment by ericwbailey** [comment]
If it works for you, I'll consider me the x-factor, then 😅

Thanks again for reporting this!
