### ISSUE TITLE
Update the information architecture

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#1425]
Now that the site's been live for a bit, I'd like to shift around some of our content. Looking at our analytics, there (sadly) isn't a lot of activity with our [Contribute](https://www.a11yproject.com/contribute/) page.

I'd like to remove Contribute from the primary navigation and replace it with the [Spotlight](https://www.a11yproject.com/spotlight/), as it has a decent amount of content now. It's my hope that we can keep pushing the Spotlight as a way to feature people doing good work in the digital accessibility space who typically aren't covered. 

I'm also advocating for the deletion of the Contribute page itself, since without it in the primary navigation it would push everyone towards our [Contributing Guidelines](https://www.a11yproject.com/contributing-guidelines/), which is the one-stop-shop for all the different ways someone can contribute. The original intent for the Contribute page was to be a way to quickly explain how to engage with the project, and then deep link to the relevant detail bits, but I think that the reality is the experience is now confusing on where to go (see https://github.com/a11yproject/a11yproject.com/issues/1360).

I'd also like to deprecate the [Changelog](https://www.a11yproject.com/announcements/#changelog), as the release notes are not automated, and they take a lot of time to make for something with not a lot of return. The original idea was we'd be highlighting external contributors more, but that doesn't seem to be the case.

**Comment by tatianamac** [comment]
1. Agree to replacing `Contribute` with `Spotlight`, which is such a lovely section that brings me joy!
2. Agree with removing `Contribute` page altogether in favour of `Contributing Guidelines`. Would we want to forwaard /contribute to /contributing-guidelines as a permanent redirect?
3.` Changelog` From an equity standpoint I see changelog as an accountability tool, so I agree with @SaptakS to keep it. I'm curious if there's a way to make it more automated though, as I hear the pain of this sort of update!

(Also hi hoping to contribute more actively again!)

**Comment by ericwbailey** [comment]
That's two votes for, awesome. I'm also hearing that the changelog is worth keeping. I'll try and be a better steward of it.

The other IA thing I forgot was also exposing our [Collections](https://www.a11yproject.com/collections/), that @nchan0154 so nicely added.

**Comment by ericwbailey** [comment]
PR is here: https://github.com/a11yproject/a11yproject.com/pull/1442

**Comment by nchan0154** [comment]
I've removed placeholder text from the Collections since we'll go live with it :) I do like the Changelog, but if it become such a burden that it presents a barrier to getting stuff done, I'm also ok with losing it.

**Comment by ericwbailey** [comment]
Thanks for the update, Nic! 

And yeah, I know I said we could keep it, but I think I need to scrap it to better focus my efforts and well-being. It's a buried feature that takes a lot of work. I'd rather save my spoons for prominent parts of the site.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/1442.
