### ISSUE TITLE
Variable-ize colors

### ISSUE THREAD

**Issue by nchan0154** [a11yproject/a11yproject.com#1426]
## Overview

I'd like to propose that we migrate from using SASS variables to use CSS Variables instead. This can be a part of larger efforts to rewrite the overall CSS using more modern techniques, but I think this can potentially take priority as a way to set up the ground work for making #1423 viable (but also, not sure how much is in scope for Andy!) and reducing some of our technical debt. 

## Implementation details
Since the site uses different color schemes for each page, we'll likely need several layers of abstractions. I'm using [Hylia](https://github.com/hankchizljaw/hylia/blob/master/src/scss/_theme.scss) and Andy Bell's previous work as a major source of inspiration here. The initial layer should likely be similar to how our colors are currently set up, named colors that correspond to the actual value being described.

```scss
--color-black: #000000;
--color-gray-tint: #e6e6e6;
--color-white: #fff;
```

The second layer should represent the purpose of the color. Our components should only ever reference these kinds of variables, and not directly.
```scss
// Color definitions
--color-card-background: var(--color-white);
--color-card-focus-background: var(--color-light-green);

// Component example
.card {
  background-color: var(--color-card-background);

  &:focus {
      background-color: var(--color-card-focus-background);
  }
}
```

I'm thinking that all definitions for these variables should be set in a single place, if not a single file, at least a single folder where each file represents a particular color theme. I think we can consider seperating themes out from the pages that they represent, so as the site grows, new pages can opt into different color schemes that exist via YAML, rather than us having to copy and paste the variables for a different page into the theme, or [extend current selectors in many different places](https://github.com/a11yproject/a11yproject.com/blob/9e903cec9f392fbda9912f708fe3ca4fc4172dc0/src/css/components/_c-hero.scss).

All this will set us up up for being able to override colors in one place to create dark mode/other color schemes, as we can see in [Hylia.](https://github.com/hankchizljaw/hylia/blob/master/src/scss/_theme.scss)

### Extra considerations
I've thought briefly about the below aspects, but there are likely things that I'm missing, so feel free to weigh in!
- IE11 compatibility. EJ has mentioned to me that we do still want to support IE11. I'm thinking we can either just set a nice, reasonable fallback on each of the components, so that IE11 gets a single color scheme across the whole site, or we use a SASS mixin in order to provide color schemes within IE11. This approach is more fully outlined in [this blog post.](https://vgpena.github.io/winning-with-css-variables/)
- SVG headers. Would be good to inline them so that we can use currentColor in order to style them.
- Right now I've laid everything out in terms of template level color theming but, but I'm not sure if we actually need component level color themes as well since I don't have a full mental map of every component on the site.

Feedback on any of these aspects is welcomed!

**Comment by ericwbailey** [comment]
Big-picture, I really like this approach and the thinking behind it. In my professional work I'm a big fan of an external token file as a source of truth, then ingesting it and declaring it in the `:root` selector as CSS Custom Properties. I also really like having components ingest these tokens as component-scoped custom properties, then redefining those for stuff like state and mode.

For our site, we have components like hero, card, and person that do a lot of context-based color updates (sometimes too much 😅), so this feels like it'd be a natural fit.

My main concern right now is around IE support, in that do we want the current design to be the fallback experience? I am wondering if a dark or muted color experience would be better, to avoid issues mentioned in https://github.com/a11yproject/a11yproject.com/issues/964. Or is it better to keep things as-is now, and then update the fallback color values with a muted theme once we, you know, create one.

>SVG headers. Would be good to inline them so that we can use currentColor in order to style them.

I love this idea!

>Right now I've laid everything out in terms of template level color theming but, but I'm not sure if we actually need component level color themes as well since I don't have a full mental map of every component on the site.

This is a ton of scope creep, but I know more about Eleventy and theming now than I did when I did the initial development effort. I'd likely want to refactor a lot of our components so they're less on the bad end of DRY. The main thing that's causing a lot of stress is "context queries", where components are adapting to a class declared on the `body`. 

Custom Properties could do a lot of good here, but I don't want this refactoring idea to hold up other work.

**Comment by ericwbailey** [comment]
@nchan0154 and I chatted about this, and I've just [pushed up my dark mode work](https://twitter.com/andylevy/status/1506748105735159818?s=20&t=CGVPtye-yymBH168gq_Z4w) to build on. The reasoning is that Dark Mode that does not honor user preference (i.e. light mode website on a dark mode OS) wouldn't be a good experience.

Moving the color variables to CSS Custom Properties will blend really nicely with what Nic's proposing, so we think it makes sense for her to build from this effort.

**Comment by nchan0154** [comment]
I've basically completed a first pass version of this in open PR. I've essentially followed the approach outlined in the first post, with some creative use of mixins to make colors work with different 'themes'.  Some notes below:

- The core idea is that there is a base 'scheme' that draws upon the main pink and green color scheme on the homepage/the colors that most components are.
-  For pages that have a different color scheme, we override parts of that global color scheme selectively as needed (because it does add a lot of bulk to the CSS to add unused themes!), and tried to abstract things where it would make sense. This should help a lot with maintainability, so for work like the collections page that added a new page, we can opt into an existing color scheme via yaml instead of trying to track down every single component override and setting the color there. 
- The color schemes are also nestable, so for example, if we decide we always want posts to be blue and resources to be green, and we want to display them on the same page, we can nest a `[data-color-scheme="green"]` on a resource wrapper within a posts page for green resources. 
- Each color scheme respects dark mode preferences, of course! 
- IE11 defaults to a singular green and pink color scheme.
- I've tried to keep parity to the existing look and feel wherever possible, but have made some very slight changes for a more uniform look across different components, and for improving color contrast across all states, including hover, focus, etc.

I think this is quite tricky to sum up in words, so I encourage folks to play around and ask any questions you might have.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/1433.
