### ISSUE TITLE
[Post] New post: On respecting preference for reduced motion

### ISSUE THREAD

**Issue by burnhc** [a11yproject/a11yproject.com#1439]
## Your idea

I will be writing a post on how we can consider peoples' preference for reduced motion in web development. Specifically, I will be discussing the prefers-reduced-motion media query, why it is important, and how to incorporate it in code.

## Outline (optional)

1. History of reduced motion, overview on vestibular disorders
2. What is the prefers-reduced-motion media query
3. Code snippets on how to use prefers-reduced-motion
4. How to test prefers-reduced-motion media query

## Additional information (optional)
@ericwbailey has approved of my topic proposal in this [thread](https://github.com/a11yproject/a11yproject.com/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22).

## Terms
- [x] I have read, and agree to follow this project's [Contributing Guidelines](https://www.a11yproject.com/contributing-guidelines/)
- [x] I have read, and agree to follow this project's [Content Style Guide](https://www.a11yproject.com/content-style-guide/)
- [x] I have read, and agree to follow this project's [Code of Conduct](https://www.a11yproject.com/code-of-conduct/)

**Comment by ericwbailey** [comment]
Closed for inactivity.
