### ISSUE TITLE
[Bug] Link to Keyboard Navigation in Mac Browsers - weba11y.com is broken

### ISSUE THREAD

**Issue by rianrietveld** [a11yproject/a11yproject.com#1457]
## Bug description

The link to Keyboard Navigation in Mac Browsers - weba11y.com is broken on the page 
[Browser keyboard navigation in macOS](https://www.a11yproject.com/posts/macos-browser-keyboard-navigation/ ). 

The site [weba11y.com is taken down](https://who.is/whois/weba11y.com)?

## Terms

- [x] I have read, and agree to follow this project's [Code of Conduct](https://www.a11yproject.com/code-of-conduct/)

**Comment by ericwbailey** [comment]
Thanks for reporting this, @rianrietveld. It has been removed in https://github.com/a11yproject/a11yproject.com/pull/1458

As an aside, the link was from 2014! Sometimes I forget how long this site has been around for 😅
