### ISSUE TITLE
Inaccuracy: include aria-describedby in recommendations for alt attributes article

### ISSUE THREAD

**Issue by ckundo** [a11yproject/a11yproject.com#146]
For instance, if there is a user avatar on the page and profile details including name directly adjacent, point to that content using aria-describedby to avoid redundant content.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @ckundo, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
