### ISSUE TITLE
[Post] Article: A brief a11y guide to troublesome UI components 

### ISSUE THREAD

**Issue by martinlex** [a11yproject/a11yproject.com#1494]
## A brief a11y guide to troublesome UI components 

Throughout my career as a frontend developer, I have constantly seen designers sketch out components without talking to the developers. This will ever so often result in flawed accessibility, shitty code, and a list of bugs in the backlog.

This article will cover how to handle complicated UI componentes, like:

- Modals
- Carousels
- Autosuggests
- Date pickers
- Custom selects

This article is not a guide how to code these components, it's rather providing real arguments for not implementing them.
The whole team should be aware of the complexity of these components when it comes to:

- Keyboard interactions
- Audio feedback to AT
- Valid and semantic html

Almost anything is possible if you have a lot of time and money. But no client ever said: "we have a lot of time and money".
To save time, developers will use npm packages. I will touch on that too.

## Outline

I have Google Docs document and I can send you a link if sounds interesting.

## Terms
- [x] I have read, and agree to follow this project's [Contributing Guidelines](https://www.a11yproject.com/contributing-guidelines/)
- [x] I have read, and agree to follow this project's [Content Style Guide](https://www.a11yproject.com/content-style-guide/)
- [x] I have read, and agree to follow this project's [Code of Conduct](https://www.a11yproject.com/code-of-conduct/)

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/1512.
