### ISSUE TITLE
Article: Tips for accessible text

### ISSUE THREAD

**Issue by mathalete** [a11yproject/a11yproject.com#150]
Pending - some tips for making text more accessible.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @mathalete, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
