### ISSUE TITLE
Ensuring that your site conforms to Success Criteria 1.4.5 (Images of Text)

### ISSUE THREAD

**Issue by peternjugunamwaura** [a11yproject/a11yproject.com#1507]
Thank you for your interest in writing a post! Please fill out the following information:

## Testing  for images of text manually.

> I was going through the AIIY website and noticed an issue with images of text. My concern is that this success criterion cannot be tested via automated tools and requires manual testing. I would therefore be interested in addressing the topic and dispensing some knowledge on how images of text affect accessibility and how they are actually tested.

## Outline (optional)
> The outline would be as follows:- What are images of text, How images of text affect Users with disabilities, How to test for images of text, How to fix errors associated with images of text. Exceptions to the success Criteria images of text.

## Additional information (optional)

> This would be my first time contributing. I have a background in android and would like to contribute to mobile accessibility as well.

## Terms
- [x] I have read, and agree to follow this project's [Contributing Guidelines](https://www.a11yproject.com/contributing-guidelines/)
- [x] I have read, and agree to follow this project's [Content Style Guide](https://www.a11yproject.com/content-style-guide/)
- [x] I have read, and agree to follow this project's [Code of Conduct](https://www.a11yproject.com/code-of-conduct/)

**Comment by ericwbailey** [comment]
Hi @peternjugunamwaura! Is this issue related to [this comment](https://github.com/a11yproject/a11yproject.com/issues/12#issuecomment-1402490806)?

**Comment by peternjugunamwaura** [comment]
Hi @ericwbailey , Yeah, the issue is related to the comment above. I wanted to do an article on it also.

**Comment by ericwbailey** [comment]
Great, thank you! Looking forward to reading your work 🙌

**Comment by Peter-Peter254** [comment]
Thanks!

**Comment by peternjugunamwaura** [comment]
@ericwbailey please go through this PR https://github.com/a11yproject/a11yproject.com/pull/1514. It is a post related to this issue.

**Comment by ericwbailey** [comment]
@peternjugunamwaura If you are reporting an issue with the site, I would ask that you follow [the contribution guidelines](https://www.a11yproject.com/contributing-guidelines/#reporting-issues). 

Following our listed processes allows maintainers to quickly and accurately address issues, as well as treat their volunteer time and effort with respect.

**Comment by peternjugunamwaura** [comment]
@ericwbailey PR https://github.com/a11yproject/a11yproject.com/pull/1514 is actually a post. Although I believe the site https://www.a11yproject.com/ violates Success Criterion 1.4.5 , the PR does not act as a way of reporting the issue. I intend to report the issue at some later times. If possible treat the PR https://github.com/a11yproject/a11yproject.com/pull/1514 as a post meant to dispense knowledge on success criterion 1.4.5. Let me know your thoughts on the same. Thanks.

**Comment by ericwbailey** [comment]
So, to clarify you:

1. Ignored our public-facing process for both posts and issues, and
2. Are willfully withholding an unspecified potential access issue for an unknown future date.

Is that a correct read of the situation?

**Comment by peternjugunamwaura** [comment]
No, @ericwbailey  this is what is happening.

1.  Went through the a11y project's website.
2. Found out that the site could have some images of text. (Decided to make a comment on the same asking if I could do more research about images of text). While doing the research, I came up with an article for the same. Here is the comment https://github.com/a11yproject/a11yproject.com/issues/12#issuecomment-1407475521
3. Waiting for a review of the research I did from the team to determine if actually what I had raised was a violation.
4. After review of research (which was documented in a post) , discuss with the team if what I think is a violation is actually a violation. The reason for creating a post with this research info https://github.com/a11yproject/a11yproject.com/issues/1507#issuecomment-1409573090
5. If its not a violation based on the research, drop the issue. If it is, add it to issues for it to be remediated. This means am not willfully withholding an unspecified potential access to an issue. The post I created revolves around the research I did on the issue.

This is my first time contributing here. I might have missed a few procedures though. But am willing to work within the given guidelines and regulations to correct anything I might have missed. Thanks.

**Comment by ericwbailey** [comment]
This is how it looks from my perspective:

>2. Found out that the site could have some images of text. (Decided to make a comment on the same asking if I could do more research about images of text). While doing the research, I came up with an article for the same. Here is the comment https://github.com/a11yproject/a11yproject.com/issues/12#issuecomment-1407475521

You mentioned finding an access violation, and then never replied to [my comment in the issue where I asked for clarification](https://github.com/a11yproject/a11yproject.com/issues/12#issuecomment-1407475521).

>3. Waiting for a review of the research I did from the team to determine if actually what I had raised was a violation.

I am unaware of your research efforts, or which team you are referring to. The only awareness we have of work being undertaken is [the posting of this issue](https://github.com/a11yproject/a11yproject.com/issues/1507) a month ago, where you're signing up to write a post.

>4. After review of research (which was documented in a post) , discuss with the team if what I think is a violation is actually a violation. The reason for creating a post with this research info https://github.com/a11yproject/a11yproject.com/issues/1507#issuecomment-1409573090

Again, I am unaware of what team you are referring to for your research. The only manifestation I have seen of your efforts here is [your post submission](https://github.com/a11yproject/a11yproject.com/pull/1514).

>5. If its not a violation based on the research, drop the issue. If it is, add it to issues for it to be remediated. This means am not willfully withholding an unspecified potential access to an issue. The post I created revolves around the research I did on the issue.

It feels to me like you're unsure of SC 1.4.5 and are using the post as a way to determine if your perceived issue on the site is valid. This is tantamount to asking for free labor outside of the scope of what we consider, as outlined in our Contribution Guidelines.

>I might have missed a few procedures though. But am willing to work within the given guidelines and regulations to correct anything I might have missed. 

I will also note that your PR indicates you were cognizant of our Contributing Guidelines, Content Style Guide, and Code of Conduct, in that you checked all three boxes to acknowledge. This differs from your statement:

The aforementioned points also don't take using two different accounts to coordinate communication, which immediately makes people such as myself suspicious.

---

The reason we have extensive documentation for contributing is that it helps to ensure people who willingly spend their free time and expertise don't have to waste it navigating things like this. This fact was mentioned previously, but seems to have been ignored.

I am rejecting this post submission based on this interaction, and [our Contributing Guidelines](https://www.a11yproject.com/contributing-guidelines/#rejection). If you are still interested in publishing your post, I recommend a platform such as [DEV.to](https://dev.to/).
