### ISSUE TITLE
[Post] Getting Started with TalkBack

### ISSUE THREAD

**Issue by chollma** [a11yproject/a11yproject.com#1509]
Thank you for your interest in writing a post! Please fill out the following information:

## Your idea

I don't feel that there's enough content for working with Android-based assistive technologies. I've written a post to get folks started using TalkBack.

## Outline (optional)
- Intro to TalkBack (who, what, when)
- Getting Started (activating/turning on TalkBack)
- Navigation Modes (touch, swipe, voice controls)
- Basic TalkBack Commands (table with command and description)

## Additional information (optional)

> N/A

## Terms
- [x] I have read, and agree to follow this project's [Contributing Guidelines](https://www.a11yproject.com/contributing-guidelines/)
- [x] I have read, and agree to follow this project's [Content Style Guide](https://www.a11yproject.com/content-style-guide/)
- [x] I have read, and agree to follow this project's [Code of Conduct](https://www.a11yproject.com/code-of-conduct/)

**Comment by ericwbailey** [comment]
Hey @chollma! Excited to review this. We have one post currently submitted outside of GitHub that is in the middle of the editorial process, and then this one is up next.
