### ISSUE TITLE
Deprecate GitHub Discussions

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#1517]
Our GitHub Discussions feature does not get a ton of engagement, and when it does it oftentimes subverts [our existing, established way of getting issues discussed and dealt with](https://www.a11yproject.com/contributing-guidelines/#fixing-things).

This serves to not only muddy the waters of how to effectively engage with the project, but also lower the chance issues raised get dealt with. 

Because of this, I am proposing we close all Discussions. It was an interesting experiment, but ultimately does not work for the project's needs.

**Comment by p2635** [comment]
I'm new here, but I don't mind as long as my recent post is converted to an issue: https://github.com/a11yproject/a11yproject.com/discussions/1516

**Comment by ericwbailey** [comment]
Discussions have been removed.
