### ISSUE TITLE
Bug: Incorrect link to edx/W3C Intro to Web Accessibility resource

### ISSUE THREAD

**Issue by sareg0** [a11yproject/a11yproject.com#1535]
The link to "Introduction to Web Accessibility" is incorrect: https://github.com/a11yproject/a11yproject.com/blob/b6f694b07b977f4cc93b3bf08035b51bf2115bf7/src/_data/resources.json#L855

Currently: https://egghead.io/courses/start-building-accessible-web-applications-today

Should be: https://www.edx.org/course/web-accessibility-introduction

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/1536.
