### ISSUE TITLE
[Bug] Typo in posts category ID

### ISSUE THREAD

**Issue by Ashenfactory** [a11yproject/a11yproject.com#1543]
Thank you for reporting a bug. Please fill out the following information:

## Bug description

The site consistently uses the internal name "experience" for the "Experiences" category, but on the posts overview page, the ID attribute is pluralized, making links pointing to the category instead direct to the top of the posts page.

## Expected outcome

The ID attribute value should matched the internal name of the category

## Steps to reproduce

Navigate to any post in the "Experiences" category and click the category name link next to the header.

###  What device were you using when you encountered the bug?

Desktop

### What operating system were you using? What version is the operating system?

KDE neon 5.27

### What web browser were you using? What version is the web browser?

Firefox 112.0

### Assistive technology and version (optional)
No

## Additional information

N/A

## Terms

- [x] I have read, and agree to follow this project's [Code of Conduct](https://www.a11yproject.com/code-of-conduct/)

**Comment by ericwbailey** [comment]
Hey there, thanks for reporting this. Closed via https://github.com/a11yproject/a11yproject.com/pull/1544, and thank you for your first contribution to The A11Y Project!
