### ISSUE TITLE
Idea: contribution from people with disabilities

### ISSUE THREAD

**Issue by pentzzsolt** [a11yproject/a11yproject.com#157]
I got this idea after listening to ShopTalkShow's episode with Derek Featherstone.

Recently, there was a heated argument about whether or not it is a good practise to mark up your navigation in an unordered list. As most of you may remember, the origin of the argument was a person who was actually blind, talking at a conference, stating that unordered lists for navigations were bad.

Derek, in this podcast I mentioned, said that it is just one person's personal preference how they like a navigation in a screen reader.

That argument kind of lead me to the realization that most of the accessibility best practises that we, as a community accept as good, are actually based on assumptions. You can't really go wrong with following these guidelines of course and there is a huge research behind it, but still.

I believe that if there was a project, a website namely, dedicated to accesibility, that was actually built and maintained by developers with disabilities and other people with disabilities, we could see what they come up with and we could examine the code produced by them, we could jump to conclusions that we might not be able at the moment and we could learn so much from that.

Do you think this is a good idea? If so, how would you execute it, any ideas, comments, opinions are very welcome.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @pentzzsolt, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
