### ISSUE TITLE
[Bug] "our roadmap" link is 404 from "Contributing Guidelines" page 

### ISSUE THREAD

**Issue by yzzhuo** [a11yproject/a11yproject.com#1599]
## Bug description
The “Our Roadmap” link on the “Contributing Guidelines” page results in a 404 error (Page Not Found). The link appears to be broken or outdated, and the roadmap cannot be accessed through the provided link.

## Expected outcome
The “Our Roadmap” link should direct users to a valid page that outlines the project’s roadmap. Users should be able to access the roadmap to understand the project’s future plans.

## Steps to reproduce

1. Go to the[ “Contributing Guidelines” page ](https://www.a11yproject.com/contributing-guidelines/#reporting-issues)on the A11y website.
2. Scroll down and locate the “our roadmap” link.
3. Click on the link.
4. [The page](https://github.com/a11yproject/a11yproject.com/projects/1) displays a 404 error instead of the expected roadmap.

###  What device were you using when you encountered the bug?

laptop computer

### What operating system were you using? What version is the operating system?

macOS 14.5

### What web browser were you using? What version is the web browser?

Google Chrome 128.0.6613.137

### Assistive technology and version (optional)
None used

## Additional information
N/A

## Terms

- [x] I have read, and agree to follow this project's [Code of Conduct](https://www.a11yproject.com/code-of-conduct/)

**Comment by ericwbailey** [comment]
Thanks for flagging this. We removed the roadmap, so I've removed the reference to this in https://github.com/a11yproject/a11yproject.com/commit/32d09df6551c4c316f64354f7c4ce84d789461e2.
