### ISSUE TITLE
Guest Post Contribution

### ISSUE THREAD

**Issue by andersonok02** [a11yproject/a11yproject.com#1605]
Hi,

I went through your website and read several blogs and I feel they touch the realm of my work and expertise. I genuinely appreciate the awareness you are creating with the meaningful content on your website.

I would like to introduce myself as a tech enthusiast and a consultant. In my ideal time, I prefer to write on various subjects. I would like to be a part of it through guest posting.

I will cover all the fundamentals that will be very useful to your audience.

Here are a few topics that I think readers would get a ton of value from

#Topic 1: Unit Testing in .NET: Tools, Techniques, and Best Practices

#Topic 2: Dependency Injection in .NET Core: A Beginner’s Guide

#Topic 3: Deploying .NET Applications to Azure

#Topic 4: Using Docker for Containerizing .NET Applications

In case you don’t like these topics, we can always switch to the
topics and make them more suitable.

I’m excited about your response!

**Comment by ericwbailey** [comment]
https://www.a11yproject.com/contributing-guidelines/#promotions-partnership-deals-and-seo-scams
