### ISSUE TITLE
Ideas: "legal" section on the resources page

### ISSUE THREAD

**Issue by ckundo** [a11yproject/a11yproject.com#186]
It may be useful to have a section with links to legal subject matter around accessibility. I can see that it may be out of scope of the goals of the site, which are primarily technical, but I thought it'd be an idea worth posing. What do folks think?

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @ckundo, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
