### ISSUE TITLE
Where do I find chapter about Section 508 Compliance - US Government Requirement

### ISSUE THREAD

**Issue by stefek99** [a11yproject/a11yproject.com#190]
Dear All,

I just tried to find chapter about Section 508: http://en.wikipedia.org/wiki/Section_508_Amendment_to_the_Rehabilitation_Act_of_1973

> In 1998 the US Congress amended the Rehabilitation Act to require Federal agencies to make their electronic and information technology accessible to people with disabilities

Some time ago I was working on Section 508 and here is the list of resource I've populated: https://docs.google.com/document/d/146H-d12F62AUocFX494qJ11ybWLp-GWnZgPeu-3scYM/edit 

^^^ Anyone with link can comment, if you like it I can give you edit rights or even better - **I can add an extra page about section 508**.
### Why Section 508 is important?
- Money drive change.
- Corporations have money _([Apple: 150$ billion](http://qz.com/61653/apple-cash-plan-* stock-buyback-or-more-dividends-likely-coming-this-spring/))_ BTW: [see their form](http://img607.imageshack.us/img607/4056/appleaccessibilitybreac.png)
- If we want to get a slice we need to make products meeting their specs.

I know that some items on the list are heavily outdated - see http://www.buyaccessible.gov/ - but this is the law. 
##### Is there a general consensus to add section about Section 508?

Will greatly appreciate any feedback and comments.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @stefek99, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
