### ISSUE TITLE
Article: How to create accessible sprites 

### ISSUE THREAD

**Issue by Piderman** [a11yproject/a11yproject.com#194]
Idea for getting sprites to show up in high contrast mode without an image in the DOM. 

https://gist.github.com/Piderman/5589083

Thoughts?
Cheers

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @Piderman, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
