### ISSUE TITLE
Accessibility Means Search Engines Too…Right?

### ISSUE THREAD

**Issue by grayghostvisuals** [a11yproject/a11yproject.com#198]
Anyone use schema? micro-formats? Does the use of them expanding a site's visibility with a search engine make them relevant to accessibility? Should we start including more articles on this topic? If so, what topics should we start with? Am I asking too many questions?

**Comment by jpdevries** [comment]
Yes! SEO is part of a11y. People can't access content if they can't find it.

I've been starting to tell my clients who are hesitant to "invest" in accessibility that they already do.

> You already invest in accessibility. 
SEO is a significant aspect of accessibility. 
People can’t access what they can’t find.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @grayghostvisuals, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
