### ISSUE TITLE
aria-label and aria-labelledby

### ISSUE THREAD

**Issue by grayghostvisuals** [a11yproject/a11yproject.com#199]
Came across these two ARIA attributes which confused me a bit especially the documentation explaining them. I've noticed in bootstrap that they use the attributes on their modals and wanted to bring to light exactly why we use them and their meaning.

Hoping that before I write the article I can spark some convo with thoughts and ideas and then incorporate them.

This is the doc link I have so far…
[http://www.w3.org/TR/2010/WD-wai-aria-20100916/states_and_properties#aria-label](http://www.w3.org/TR/2010/WD-wai-aria-20100916/states_and_properties#aria-label)

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @grayghostvisuals, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
