### ISSUE TITLE
Feature accessibility support table

### ISSUE THREAD

**Issue by shaundunne** [a11yproject/a11yproject.com#201]
There's a table on [html5accessibility](http://www.html5accessibility.com/) which checks which of the HTML5 features are supported in which platform and in which browser - but its about a year out of date and doesn't in any form show mobile platforms / browsers.

Thought that this might be a good thing to have here, an easily updatable table that can provide quickly digestible info.

**Comment by davatron5000** [comment]
No movement on this in over two years. I'm going to close it. If someone feels passionate we can re-open.
