### ISSUE TITLE
Article: How to detect when images are disabled

### ISSUE THREAD

**Issue by grayghostvisuals** [a11yproject/a11yproject.com#207]
At work they're making me replace everything under the sun with an image. This made me curious about what to do to take care of this scenario. I stumbled upon this article by Steve Faulkner. Thought it might be a good candidate. [http://blog.paciellogroup.com/2011/10/detecting-if-images-are-disabled-in-browsers/](http://blog.paciellogroup.com/2011/10/detecting-if-images-are-disabled-in-browsers/)

Also as a side note one of these items I had to replace was a submit button for a form. If the images are disabled you no longer see anything because the text is being bumped off the screen. Would be nice if there was a fallback where I could bring the text back into view if the image was disabled.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @grayghostvisuals, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
