### ISSUE TITLE
Article: Don't Use Links as Buttons

### ISSUE THREAD

**Issue by patocallaghan** [a11yproject/a11yproject.com#208]
Just came across this article which was pretty enlightening [http://www.karlgroves.com/2013/05/14/links-are-not-buttons-neither-are-divs-and-spans/](http://www.karlgroves.com/2013/05/14/links-are-not-buttons-neither-are-divs-and-spans/). Any objections to an article about this (apologies if there's one already)?

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @patocallaghan, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
