### ISSUE TITLE
Article : Quick Tip - Avoid -webkit-text-adjust-size: none;

### ISSUE THREAD

**Issue by clarehyam** [a11yproject/a11yproject.com#217]
I've started a gist (https://gist.github.com/clarehyam/7639811) for this one.  Let me know any amends and I'll update it.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @clarehyam, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
