### ISSUE TITLE
"How to hide content" 2 comments

### ISSUE THREAD

**Issue by karlgroves** [a11yproject/a11yproject.com#218]
I'd like to recommend a specific mention that 'visibility:hidden' doesn't "hide" from screen readers.  I guess the best analogy is how the :visible selection filter in jQuery works: it does consume space in the layout.  Anyway, some screen readers still read that content. Problem is, some don't.  TL;DR: visibility:hidden is unreliable if what you want is to truly hide content.

2nd comment: 
The article says: "And for good measure you could consider adding the ARIA attribute aria-hidden="true" to the element."
I like that, especially for stuff that toggles visibility.   To that end, I actually like using it as a selector:

```
[aria-hidden="true"]{ 
/* cool clip pattern hidey stuff here */
}
```

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @karlgroves, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
