### ISSUE TITLE
"Navigate using just your keyboard"

### ISSUE THREAD

**Issue by karlgroves** [a11yproject/a11yproject.com#220]
Can you add some notes on what should be expected during keyboard interaction?

```
Can you interact with all controls, links, and menus using only the keyboard?
Can you see what item has focus at all times?
Does the visual focus order match the intended interaction order?
```

Source: http://www.karlgroves.com/2013/09/05/the-6-simplest-web-accessibility-tests-anyone-can-do/

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @karlgroves, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
