### ISSUE TITLE
Using alt text properly: add resource

### ISSUE THREAD

**Issue by karlgroves** [a11yproject/a11yproject.com#221]
http://www.w3.org/TR/html-alt-techniques/

Since its a W3C resource, its bloody painful to read, but Steve Faulkner's pretty much covered all the bases

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @karlgroves, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
