### ISSUE TITLE
link-to/reference relevant WCAG sections in the post about `outline: none` ?

### ISSUE THREAD

**Issue by cvrebert** [a11yproject/a11yproject.com#229]
Like http://outlinenone.com does.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @cvrebert, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.

**Comment by cvrebert** [comment]
Refiled as #522
