### ISSUE TITLE
Article Idea: Making Accessible Links

### ISSUE THREAD

**Issue by grayghostvisuals** [a11yproject/a11yproject.com#235]
Based on this article ([http://www.sitepoint.com/15-rules-making-accessible-links](http://www.sitepoint.com/15-rules-making-accessible-links)) over at Sitepoint. I think we can make this topic into a very short summary of do's.

**Comment by RachelRVasquez** [comment]
I like this idea - is this open to be picked up? Are we sticking to writing it as a checklist?

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @grayghostvisuals, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
