### ISSUE TITLE
Make license/permissions clearer

### ISSUE THREAD

**Issue by equivalentideas** [a11yproject/a11yproject.com#283]
I think the license/copyright situation of this project could be a little clearer. Currently the website footer says: 

> © 2014 The Accessibility Project

Obviously the code on the site is open source, and I'd guess that as the text/content is intended as a community resource, contributors would like to remove any ambiguity about whether they, or others can use the text in other resources, documentation, presentations, citations etc. .

As someone who has contributed text to the website, I would like to see a creative commons license on the text, to remove any ambiguities about how it can be used.

The project has somewhat similar aims to Wikipedia, in trying to make reliable, shared knowledge on this topic freely available. We could draw on their thinking and use one of the two they use: [Creative Commons Attribution-ShareAlike 3.0 Unported License](http://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License) or [GNU Free Documentation License](http://en.wikipedia.org/wiki/Wikipedia:Text_of_the_GNU_Free_Documentation_License). I think I'd fall with CC-BY-SA because it's a bit easier to understand.

Code wise, in [CONTRIBUTING it has](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md):

> By contributing your code, you agree to license your contribution under the terms of the APLv2.

That's clear, but maybe it could be in the readme and a license file could be included?

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @equivalentideas, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
