### ISSUE TITLE
Pattern: Accessible HTML5 Audio Player

### ISSUE THREAD

**Issue by joe-watkins** [a11yproject/a11yproject.com#284]
Howdy everyone!! :)

Here's a pattern that seems pretty handy: http://codepen.io/joe-watkins/pen/BCEbg

What do you all think?

**Comment by svinkle** [comment]
@joe-watkins, since this is using a native audio player, I'm curious as to how well the accessibility would be across other browsers? Or are you getting around this by providing the custom `listen` and `pause` buttons?

**Comment by svinkle** [comment]
@joe-watkins Any update on this?

**Comment by joe-watkins** [comment]
@svinkle Ha! This pattern is crazy old :) More native HTML5 players are becoming keyboard/SR friendly but not all. I guess this pattern still holds up as an example of custom controls & transcript link for an audio player.

**Comment by svinkle** [comment]
@joe-watkins The `button`s are announced as a "toggle button," but they only serve a single function. It would make more sense to combine the play/pause functionality into a single control.

I'd say the transcript control is more like a expanded/collapsed situation. Thoughts? 🤔

**Comment by joe-watkins** [comment]
@svinkle closing -- I can revisit this pattern in the future when time permits. We could attack it better and differently :)
