### ISSUE TITLE
Article: Myth - screen readers don't use JavaScript: Update needed

### ISSUE THREAD

**Issue by MarcusJT** [a11yproject/a11yproject.com#285]
This article should be updated to reflect the newer results available at http://webaim.org/projects/screenreadersurvey5/#javascript

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @MarcusJT, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
