### ISSUE TITLE
Article: Accessibility is a Constant

### ISSUE THREAD

**Issue by michaelspellacy** [a11yproject/a11yproject.com#288]
Whoa! What a wonderful endeavor this is! I would like to contribute if i can, so I wrote a quick draft on going into accessibility with the right attitude and plan. Something I don't hear too often! Please let me know your thoughts. Thanks!

https://gist.github.com/michaelspellacy/ec3ffc42454cc62da2d6

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @michaelspellacy, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
