### ISSUE TITLE
Bower components

### ISSUE THREAD

**Issue by svinkle** [a11yproject/a11yproject.com#308]
Wondering if there's a place for bower components? Over the break I forked [this bit of code](http://www.karlgroves.com/2014/11/24/ridiculously-easy-trick-for-keyboard-accessibility/) from @karlgroves and made it into a bower component: https://github.com/svinkle/a11yclick. 

Any thoughts on where this could be placed on the site? I also have a pen handy: http://codepen.io/svinkle/pen/VYKVbd.

Feedback appreciated.

**Comment by karlgroves** [comment]
@svinkle I once went through all of my JSFiddles, Gists, and JSBins and tried to see if I could assemble a library of accessibility out of them. What I came up with was mostly a bunch of special purpose functions, like auto-fixing things with JS that should've been done right in the first place. If you're interested in taking a look, it is at https://bitbucket.org/karlgroves/a11y_utils.js/src

There are probably plenty of other things that could be added to something like that, though they'd be pretty heavy-handed - like removing table summaries that are empty, setting tabindex to 0 in any cases where they're > 1, or stuff like that. 

I also have this: http://jsfiddle.net/karlgroves/sf9n79d5/ which I've been meaning to add the CSS to right in with the function to reduce consumer idiocy.

I guess the big question is what the intended purpose would be. The a11yclick function is awesomely general purpose, as would be the addOffScreen function. Other than that, most everything else is questionable.

What do you think?

**Comment by svinkle** [comment]
@karlgroves Fantastic idea! I thought of something similar, somehow bringing together all these patterns in to one library of sorts. Though perhaps individual components would be equally useful as folks could include as needed, thinking perf here.

I'll take a look through your a11y_utils.js. I like the addOffScreen concept. Makes me think of when I drop in visually hidden spans for 'read more' links (giving more context). I think this could be improved by using data attributes, exposing the link to a CMS for content insertion, for example. The tabindex nomalization is also a good idea.

I'd like to see quality components/helper functions come together on the site, maybe build a library of those later on.

**Comment by joe-watkins** [comment]
@svinkle sweet! I like the idea of coming up with a home for JS gizmos.. I have a silly one I use for toggling aria attribute states: https://gist.github.com/joe-watkins/00a1bd83fec29048f4ed
