### ISSUE TITLE
Markdown version of a11y checklist

### ISSUE THREAD

**Issue by chris-dura** [a11yproject/a11yproject.com#310]
Hello,

I work on a huge enterprise development team, and we make heavy use of GitHub issues, gists and wikis. In an effort to mitigate some of the headaches when managing all the Pull Requests from a gargantuan team, we've instituted a "PR template" that all contributors have to use when they open a PR. 

Basically, it's a boilerplate markdown file that has standard tasks the developer needs to complete before the PR is eligible to even be reviewed or considered a merge candidate. For example, things like "Unit tests pass", "Lint free", etc. Anyway, as the mouthpiece for a11y around the office, I'd like to start making basic accessibility one of those minimum requirements to get a PR merged.

I'm still pretty new to accessibility myself, but I've found your checklist seems like a good starting point. Obviously, a truly accessible project would need focused effort, but I think your checklist represents very simple things that _any_ developer could implement without being an "accessibility expert" and it would improve our project immeasurably and be an "easy win".

I think others might find it useful to have a markdown version of the checklist for a variety other reasons, but for me, I'd especially like a version that I could embed in Pull Requests. This way, it would save the dev's progress and serve as a running progress report on the PR, e.g. 10 tasks (3 completed, 7 remaining).

**Comment by bartveneman** [comment]
What a great idea! I think I'll give that list a try myself. Thanks!
