### ISSUE TITLE
Edit on GitHub Button for Articles

### ISSUE THREAD

**Issue by grayghostvisuals** [a11yproject/a11yproject.com#314]
see screenshot attached for a better understanding [http://cl.ly/image/0h3f2v2R1G1F](http://cl.ly/image/0h3f2v2R1G1F)

**Comment by patrickodacre** [comment]
Hi a11yproject/a11yproject.com,

Thank you for contacting me. I've received your email and will get back to you with a response as quickly as possible.

Cheers,

**Comment by davatron5000** [comment]
@patrickodacre Would you mind either turning off your auto-responder for Github or unwatching this project. Thanks.

**Comment by patrickodacre** [comment]
@davatron5000  ack. I'm sorry about that everyone. Will do.
