### ISSUE TITLE
Resource: Text Contrast

### ISSUE THREAD

**Issue by grayghostvisuals** [a11yproject/a11yproject.com#319]
My Jaw dropped when I saw this to help find the right contrast for text.
[http://jxnblk.com/colorable/demos/text](http://jxnblk.com/colorable/demos/text)

**Comment by webuxr** [comment]
@grayghostvisuals: Similar to my [comment here](https://github.com/a11yproject/a11yproject.com/issues/420#issuecomment-275222959), why not edit, add this link to the same sections on the Resources page, and submit another pull request?

I would think both links (to [Colorable](http://jxnblk.com/colorable/demos/text) and [Frend](https://frend.co/)) would be welcome additions to the Resources page.

FWIW, I also like the link to [clrs.cc/a11y](http://clrs.cc/a11y/) from here jxnblk.com/colorable/demos/ ... and it's already (sort-of) namespaced too.

Good stuff either way.

Cheers,
_rs

**Comment by davatron5000** [comment]
@webuxr Feel free to commit whatever here. When @grayghostvisuals initially submitted these issues it was an uglier, HTML addition and he had recently taken a break from the project. Feel free to add these and make a PR. 

There are a few more issues about resources. I'll try to go through and add labels or merge all of those. If we end up with too many, we can always prune them back.

**Comment by webuxr** [comment]
@davatron5000 Will do! Please tag me on those merged Resources-related issues.
