### ISSUE TITLE
Revisiting the footer

### ISSUE THREAD

**Issue by svinkle** [a11yproject/a11yproject.com#320]
I love the footer, the concept and how it looks. The problem is all the images are adding a whopping 3Mb to each page load. Not sure what future plans are for the footer but this is a big problem.

My first instinct would be to implement a lazy-load feature for these images, only download to the client if the user reaches the footer area.

Any other thoughts?

**Comment by grayghostvisuals** [comment]
@svinkle Agree with you 110%

**Comment by joe-watkins** [comment]
I can handle this :)
