### ISSUE TITLE
adding a tooltip pattern

### ISSUE THREAD

**Issue by mpiotrowicz** [a11yproject/a11yproject.com#322]
I had some great feedback about this tooltip pattern for form inputs, any objections to my adding a "tooltips" section to the pattern library?
http://codepen.io/mpiotrowicz/pen/PwQYMd

**Comment by grayghostvisuals** [comment]
WUUUT!!!! Amazing! Drop it in right this minute! \o/

**Comment by jenstrickland** [comment]
That tooltip pattern isn't an ideal experience for mobile, and the CodePen broke on my iPhone. 

Look at http://fidelity.com > click Log In > click the ?. See the tooltip slide down, attached to the input field it is associated with? That was extensively tested and works well on all platforms and browsers. Only the ? icon needs revisiting, once the brand's visual standards can be updated.

**Comment by mpiotrowicz** [comment]
ah, I have a link to a mobile version of the pattern within the pen. What happened when you loaded the pen on your phone? If it's not working I'd like to do what I can to improve it

**Comment by mpiotrowicz** [comment]
The pattern in the Fidelity example is slightly different in that it requires a click rather than the hover behavior. Do we want to advocate one approach over another? Perhaps both can be showcased

**Comment by heitzke** [comment]
@mpiotrowicz  very cool, seems to work well. What screen reader did you get to test this with? I'm not appropriately setup for accessibility testing right now, so Chrome vox is about all I have right now haha. I'm all for sticking with the focus/hover action you have here, I don't see much in the way of accessibility work on the Fidelity example 

@jenstrickland although true, this example is more about the structural markup and attributes than the actual visual implementation here.

**Comment by mpiotrowicz** [comment]
I was able to test using NVDA and VO on desktop, and iOS VO on iPhone (for mobile version).

**Comment by heitzke** [comment]
Nice! Thanks. Looks like I have a few new things to setup over here on my end

**Comment by jenstrickland** [comment]
For mobile you can't use hover, which is one of two reasons why the Fidelity one I designed/developed is preferred. The modal layer is also something to avoid for mobile.

I tried to click the mobile link in your pen — that was what didn't load on my iPhone.

**Comment by mpiotrowicz** [comment]
@jenstrickland ah, Codepen tries to open that link within the iframe, hence the breakage! Updated to open in a new window

**Comment by mpiotrowicz** [comment]
there are multiple examples under categories for other patterns, so no reason we can't include another tooltip implementation as well if you create the demo!

**Comment by jenstrickland** [comment]
I'm brand spankin' new to this project and not sure what to do to help, or how. So, learning by fire? :)

**Comment by grayghostvisuals** [comment]
@jenstrickland My suggestion is to contribute where you have a desire to. This could be the following…

- Updating Code
- Design
- Write an Article
- Submit a great resource
- Make an awesome A11Y pattern on CodePen for our patterns section

Just a few ideas for you :)
