### ISSUE TITLE
Suggested additions to the a11y checklist

### ISSUE THREAD

**Issue by elliotekj** [a11yproject/a11yproject.com#329]
Hey,

Some suggested additions to the a11y checklist:
- “Use SVGs wherever possible” under the images heading
- “Provide a ‘Skip to main content’ link” under the links heading
- “Ensure no non-decorative content is provided via `:before` or `:after` psuedo elements” under the document outline heading

**Comment by davatron5000** [comment]
Hey @ElliotEKJ,
Thanks for improving this! Just a couple things from me:

1. Do you have any links to support the SVG argument? I can kinda infer the goal, but it doesn't seem super critical.
2. Also "Ensure no non-decorative" is a slightly confusing double-negative. I wonder if that could be worded more clearly.

**Comment by ElliotEKJ** [comment]
Hey @davatron5000,

Sorry about the delay on this. To answer your questions:

1. My SVG argument was based off of this article on Sitepoint: http://www.sitepoint.com/tips-accessible-svg/

2. You’re right. “Ensure that only decorative content is added with the `:before` and `:after` pseudo elements.” might be a better way of phrasing it.

**Comment by jfc3-dol** [comment]
In the FORMs section, you talk about INPUT fields LABEL. The default INPUT type is TEXT, so you don't need:

type="text" 

on the following line.

<label for="name">Name:</label><input id="name" type="text">

You could also add

name="name"

to your example for those using a database so the information can be added or updated depending on the function of the page.

**Comment by jfc3-dol** [comment]
What about adding :active to the link section where you have :focus for an older version of IE that some people might have to support.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @elliotekj, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
