### ISSUE TITLE
Screen reader issues

### ISSUE THREAD

**Issue by samueljseay** [a11yproject/a11yproject.com#333]
Hi, I'd like to ask whether you think a11yproject could host a list of known screen reader issues.

In my company we are serious about screen reader support so we've started collecting a list of screen reader bugs with supporting JSFiddle examples. The reason we've done this is because JAWS support is basically non-existent (no proper bug tracking) and sourcing Voiceover bugs in Apple's issue tracking is a nightmare.

When you say that you "support" a screen reader to your clients, then confirming that support is so difficult when you have no grounded understanding of where your code is misbehaving or where the screen reader is misbehaving.

I'd feel like a11yproject hosting something like this would be incredibly useful to developers doing accessibility. Perhaps a11y is not the place for that, and if so I'd love to hear some feedback about whether this belongs in a separate project somewhere.

Thanks :)

**Comment by joe-watkins** [comment]
HI @samueljseay - sounds interesting. 

1. Can you give us a couple examples of the types of bugs you were thinking about having on the site?
2. Do you have ideas about how these bugs could be presented to the user at all screen sizes?
3. For consistency,.. I'd like to see the code examples in CodePen. See [Contributors Doc](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md)
4. How do you suggest this content stay up-to-date if there are no solid bug tracking solutions for JAWS/VoiceOver

**Comment by samueljseay** [comment]
Thanks for prompt reply :)

1. Here's a couple of example issues with supporting fiddles (we only just started a few days ago collecting this information and have found these already)

Voiceover supports aria-labelledby but not aria-describedby: https://jsfiddle.net/uvzxkLrg/embedded/result/ (I know there is an Apple issue somewhere for this. can't find it for the life of me)

VoiceOver not reading dropdown options after password field: https://jsfiddle.net/x0jmn5xw/4/embedded/result/

JAWS + IE(9,11) not reading aria-label on menu 
https://jsfiddle.net/przquuvt/light/

2. Do you mean you'd like a UI design of some sort for responsiveness? I could investigate something like this. (I've only just considered that I could contribute to this project so I'll have to look at whats already present in the codebase)

3. Codepen sounds absolutely fine, I would suggest using fullscreen mode on the examples to ensure that the behaviour is consistent with an isolated example in the browser.

4. Thats something I'm not sure of, as someone who doesn't have a lot of experience with this kind of effort and having never maintained an issue tracker outside of a commercial organisation. I thought maybe it would make sense to rely on github issues for updates (ie community contribution), but that may be too slow turnaround for these kinds of things.

I really wanted to fire these ideas against someone because I haven't maintained an OSS project before so I don't know what works and what doesn't. If this seems like something people are interested in then I'd like to contribute effort to it.

**Comment by svinkle** [comment]
This sounds a lot like https://www.powermapper.com/tests/screen-readers/aria/.

To try and accurately maintain this type of data would be a large effort, much more so than suits the purpose of this project. We can add links to data sources such as the above resource, but I'm not sure about maintaining data here.
