### ISSUE TITLE
Open source web application for accessible higher ed syllabi

### ISSUE THREAD

**Issue by idbygeorge** [a11yproject/a11yproject.com#334]
Hi All,

I would like the project to consider adding Salsa--http://salsa.usu.edu/ --to the a11yproject.com Resources page under the Software section.

Salsa was developed at Utah State University with a grant from the Utah Science Technology and Research initiative--http://ustar.usu.edu/. The code is 100% open source and available on GitHub: https://github.com/idbygeorge/salsa. 

During the Fall 2014 semester Salsa delivered accessible syllabi to 5,000+ students, and for Fall 2015 the Salsa project is on track to serve 10,000 students.

Thank you,
## George

George Joeckel, MS
The Salsa project

**Comment by svinkle** [comment]
Closed via #338.
