### ISSUE TITLE
Implicit ARIA Roles

### ISSUE THREAD

**Issue by Charlotteis** [a11yproject/a11yproject.com#335]
Hi team!

I'm a relatively new developer who swears by your a11y checklist.
However; reading this '[ARIA in HTML](https://specs.webplatform.org/html-aria/webspecs/master/#document-conformance-requirements-for-use-of-aria-attributes-in-html)` spec it says to *not* put roles on an element that already has that role implicitly:

EG. Don't give an `aside` a role of `complementary` because that role is already implicitly on the `aside`.

So I guess my question is; does a lot of the the landmark checklist items in the a11y checklist need to be removed? I'm relatively new to this and confused by the conflicting suggestions :)

Thanks for this project, I have learnt so much from it.

**Comment by joe-watkins** [comment]
Hi @Charlotteis 

This is a great question and often confusing. Some [Assistive Technology](http://webaim.org/articles/motor/assistive) isn't as good with HTML5 markup and enjoys the extra role applied to it. So `<main role="main">..</main>` feels redundant but is a safe bet for now. 

You can [learn more about roles at the W3C](http://www.w3.org/TR/WCAG20-TECHS/aria#ARIA11).

**Comment by Charlotteis** [comment]
That makes sense to me. Thank you for the clarification: I'll just keep using it until the checklist tells me not too, heh.
