### ISSUE TITLE
Article: Getting started with NVDA

### ISSUE THREAD

**Issue by svinkle** [a11yproject/a11yproject.com#336]
I wrote up some basic notes on how to use NVDA and presented them to the Shopify FED team. Seemed to go over well. Thought we could add it as an article here.

https://gist.github.com/svinkle/a4efd704837e90adc928

**Comment by davatron5000** [comment]
I :heart: it! Publish this please! I sorta wonder if we create an "Assistive Technology" category for articles like these.  It would be pretty easy to smash out "Getting started with..." articles on things like: 

- Chrome Vox
- High Contrast Mode
- iOS Accessibility Tools

**Comment by mpiotrowicz** [comment]
Very happy to see this moved here :)

Good idea @davatron5000, that categorization makes sense to me!

**Comment by svinkle** [comment]
Published! Could really use some table style love.

**Comment by davatron5000** [comment]
Yeah. We can maybe do something quick, but probably want to add that as a requirement in #324. (I may have some bandwidth to pick that back up again).
