### ISSUE TITLE
Other Sensory Disabilities

### ISSUE THREAD

**Issue by MarjaE2** [a11yproject/a11yproject.com#341]
I have sensory processing issues. From personal experience, more intense senses, and less intense senses, can both be disabling, and loud noises and flashing lights can be incapacitating. While the problems with web accessibility aren't as urgent as the problems with safety devices so loud or so bright they incapacitate people through multiple layers of hearing protection, they are problems.

I think it would help to have a wider sense of what visual accessibility, auditory accessibility, etc. may involve. For example, flashing lights and animated gifs can be an issue for people with sensory processing disorder, in some cases for people with epilepsy, in some cases for people suffering migraines, and so on.

**Comment by davatron5000** [comment]
Thanks @MarjaE2 for bringing this up! It'd be great to have an article like this. We've got a couple "Primer" articles already:

- [A Primer To Vestibular Disorders](http://a11yproject.com/posts/understanding-vestibular-disorders/)
- [A Primer To Visual Impairment](http://a11yproject.com/posts/understanding-visual-impairment/)

... And we'd definitely welcome one about Sensory Processing Disorders (like light sensitivity, sensory disruption, etc). We could maybe even put an article together and ask for your feedback. 

I'd be curious about your experiences when you navigate the Web and what you find difficult.

- How do you avoid animated gifs (on sites like Buzzfeed)?
- Are auto-playing Audio and Video problematic?
- Do you lower the brightness on your devices?
- Do you use High Contrast Mode to darken your screen?

**Comment by MarjaE2** [comment]
I don't think I could write a primer.

I run Firefox, with media.autoplay.enabled=false [although this preference no longer works], QuickJava, Toggle Animated Gifs, AdBlockPlus, Stylish, etc. Unfortunately, I can't block all autoplaying animation, I don't have the tools. I definitely have trouble when I hit sites with auto-zooming maps. If I'm not using the map, I try to scroll past, can't scroll, and have it flash-zoom instead. If I am trying to use the map, I try to scroll to the right part, and have it flash-zoom instead.

Yes, auto-playing is problematic for me.

I lower the brightness, and I try to find devices where I can lower the brightness to an acceptable level. Unfortunately, it's something hard to test in loud, brightly-strobingly-lit stores. I have also used software tools to lower brightness when hardware won't cooperate.

**Comment by MarjaE2** [comment]
Lately, I've been having trouble with flashing menus in Firefox, including on this site, with expanding/shrinking elements, like on the Internet Archive, etc. as well as zooming, sheering, animation, etc. on many sites and built into some browsers I've tried.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @MarjaE2, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
