### ISSUE TITLE
Include Voice Over Accessibility Inspector

### ISSUE THREAD

**Issue by JLLeitschuh** [a11yproject/a11yproject.com#344]
This tool is incredibly powerful and allows the developer to very easily spot problems in dom layouts.
https://developer.apple.com/library/mac/documentation/Accessibility/Conceptual/AccessibilityMacOSX/OSXAXTestingApps.html
This tool provides a hierarchical view what the cursor is seeing at a given point on a page.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @JLLeitschuh, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
