### ISSUE TITLE
Suggested addition to Development tools under Resources

### ISSUE THREAD

**Issue by indrekpaas** [a11yproject/a11yproject.com#345]
I've created [ARIA attribute and role completions for Sublime Text](https://packagecontrol.io/packages/ARIA%20attributes%20and%20roles). Might be worthwhile adding it to Development Tools under Resources.

Cheers!

**Comment by grayghostvisuals** [comment]
@indrekpaas Might I suggest a demo or even some screenshots?

**Comment by indrekpaas** [comment]
![Demo of ARIA attribute and role completions for Sublime Text](http://i.imgur.com/FIx5E56.gif)

**Comment by grayghostvisuals** [comment]
This is great thanks, but I meant one that is displayed in your README of the project itself :+1:

**Comment by indrekpaas** [comment]
Sure thing!

**Comment by svinkle** [comment]
@indrekpaas This is rad! Make a PR and we'll get this merged in.

**Comment by svinkle** [comment]
Added via #463.
