### ISSUE TITLE
Checklist: Roles - inaccuracy

### ISSUE THREAD

**Issue by hmig** [a11yproject/a11yproject.com#357]
The section of the checklist regarding roles is not accurate anymore per the w3c spec: http://www.w3.org/TR/html-aria/#rules-wd.

"Setting an ARIA role and/or aria-* attribute that matches the default implicit ARIA semantics is unnecessary and is not recommended as these properties are already set by the browser." 

Steve Faulkner wrote about it as well: http://html5doctor.com/on-html-belts-and-aria-braces/. 

The w3c validator already sets warning flags on such usage.

**Comment by joe-watkins** [comment]
Hi @hmig 

Unfortunately not all browsers are on the same page yet with the w3c thinks in terms of specs. Some handle HTML5 features differently or not at all. IE is still working on it for key structural elements: [https://dev.modern.ie/platform/status/htmlsectionsinaccessibilityapi/](https://dev.modern.ie/platform/status/htmlsectionsinaccessibilityapi/) So for keeping them around for these large structural elements isn't a bad idea.

Take a peek at browser usage in WebAim's [recent survey](http://webaim.org/projects/screenreadersurvey6/#browsers).

You are correct.. the validator will throw the warnings but in the name of wider accessibility I'd disregard them. Eventually one day we can shed the extra attributes.

**Comment by hmig** [comment]
Hi @joe-watkins,

I don't think iOS, currently maps the html5 elements, yet, either. So, it's fair to say that these should stay on the checklist.

However, I think it's worth providing a note on the checklist under the title for roles that the use of roles are polyfills for now, but are redundant for supported browsers and won't be needed in the future. It's confusing when you follow one list that tells you to do certain things and then validators say it's wrong.

Just a thought. Thanks!

Heather

**Comment by joe-watkins** [comment]
Thanks again @hmig those are good thoughts.. feel free to create a PR for that addition to the checklist.

**Comment by joe-watkins** [comment]
@hmig Been giving this issue some more thought..this is a good test from Deque showing [positive side effects](https://dequeuniversity.com/assets/html/jquery-summit/html5/slides/landmarks-example.html) of aria for landmarks w/AT and older browsers. 

Steve Faulkner's article is very 'ahead of the curve'.. he even admits that in the comments. He repeatedly mentions  "where implemented" through the article that should be noted.

**Comment by hmig** [comment]
@joe-watkins - love that list from deque! Any idea what year that is from?

**Comment by davatron5000** [comment]
Re-opening for discussion. More thoughts on "Are ARIA landmarks needed or not?" from Accessibility Weekly:

http://us11.campaign-archive1.com/?u=884d5f16016183c67252bd18c&id=8ed47bfc93&e=9d10b3e8aa

I wonder, if in the spirit of this site -to make accessibility easier to understand- we don't advise adding ARIA landmarks in modern browsers. In the checklist and updating http://a11yproject.com/posts/aria-landmark-roles/

Thoughts?

**Comment by joe-watkins** [comment]
Thanks for reopening this one @davatron5000 It does need more thought on how we handle text copy around this topic.

I personally really love the "Robust" part of the [POUR principles](http://www.w3.org/TR/UNDERSTANDING-WCAG20/intro.html#introduction-fourprincs-head).  Adding those roles to landmarks today spreads the support out to more browsers and users. I've yet to learn about any super-negative results from having them in the markup from AT users. The HTML validator barks out warnings.

I'd personally consider this a requirement to meet [Guideline 4.1 Compatible](http://www.w3.org/TR/2008/REC-WCAG20-20081211/#ensure-compat): Maximize compatibility with current and future user agents, including assistive technologies.

When reviewing the latest [WebAIM survey](http://webaim.org/projects/screenreadersurvey6/#browsers) we see that we'd be leaving out a large percentage of users by not having the roles present.

Sooo.. with that being said how can we guide folks without adding confusion. I feel like a simple refresh to the content on that quick tips page would help.

**Comment by hmig** [comment]
I think adding a note to the checklist under the heading for roles regarding what browser support would be helpful. 

Example: 

Note: Landmark roles are only needed if you support IE version [whatever is the highest that doesn't support the proper mapping] & below and/or iOS [version] and below. 

Thoughts?

Heather

**Comment by davatron5000** [comment]
I totally support the Landmark Disclaimer idea. 

1. Update Quick Tip Page.
1. We'd probably want to move the Landmarks section down in the checklist
1. How does this affect #365 `role="search"`? Maybe that rolls under the Forms section?

Side feelings: I don't know if I'm :smile: or :angry: that in two years things have gone from USE LANDMARKS to DON'T USE LANDMARKS.

**Comment by hmig** [comment]
@davatron5000 - currently working on pr for items 1-3 on your list and adding the disclaimer the landmarks on the checklist. :D

**Comment by davatron5000** [comment]
Thanks @hmig! :trophy: You win COMMIT OF THE YEAR. That clears out LOTS of issues. I really like how we're reflecting the "current state" of Accessibility, and it's easy enough to update and fix when Safari and IE update. WOoooo!

**Comment by hmig** [comment]
W00t! And on my first commit of the year. :dancer:
