### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by fletcher91** [a11yproject/a11yproject.com#359]
I stumbled across [this article](http://alistapart.com/article/designing-safer-web-animation-for-motion-sensitivity) today, it suggested adding ['pause' buttons](http://codepen.io/gregtarnoff/pen/JoMxpK/) to (carrousel) elements. However I can imagine it becoming quite cumbersome and since more animations are being javascript driven.

So to prevent another cookie warning hell, I came up with the following (pardon if it's already suggested/implemented somewhere, I've done a quick search but couldn't find it);

In a global namespace for user configured accessibility options, e.g. `window.a11y`, add the variable `animations` which can hold an integer with predefined values and cooperate with animation frameworks (jQuery, ReactTransitionGroup, Boostrap) to disable animations based on those values.

I've no experience with which kinds of animations cause trouble but let me draft a naive example;
- 0; all animations are off
- 1; only fade-in/out, movement up to 1em (e.g. dropdowns)
- 2; no background movements, no parallax
- 3; full animations (same as undefined)

Or, a version which is a bit harder to implement, an options array for disabling specific animation types;
`window.a11y.animations = ['no-carrousel', 'no-parallax];`

Implementing the preferences on the user side can be easily done with an extension.

Hope this idea has some substance :) (or even better, if a standard already exists it can be closed avoiding [competing standards](https://xkcd.com/927/) ;) ).

**Comment by davatron5000** [comment]
http://codepen.io/gregtarnoff/pen/JoMxpK/

If you see the demo @gtarnoff created and is linked in the article, an opt-in or on/off switch is the proposal being made. IMHO an on/off switch would be more likely since graduated values are more difficult for developers to learn (read: if it's hard, developers won't do it).

This would take quite an effort to get cross-browser support. It could also maybe be a browser extension first. Maybe that's what [Google Accessibility was going for here](https://chrome.google.com/webstore/detail/animation-policy/ncigbofjfbodhkaffojakplpmnleeoee)

**Comment by fletcher91** [comment]
Yeah, you're right on the implementation level stuff. Requiring every website to modify their system by integrating animation pause toggles however is a lot of work; every website will have to change their GUI. By using a common place to store that boolean setting, we can get a whole lot of goodness without additional complexity.

By just using a namespaced variable:
`window.y11a.animations.disabled = true/false`

Making the given example complaint in just a few lines http://codepen.io/fletcher91/pen/jbbvPY
Which doesn't really change anything, but it gives some advantages;

* Not opinionated, by utilizing a common namespace, developers can still use/build their custom switches.
* Every switch made by a developer can be controlled by either their own switch, extensions or the browser/screenreader.
* We can built extensions to gap the time until it might be implemented by browsers, so that people don't have to click the same button on every website they visit.
* If JS (graphics) library devs are on board, many sites will be able to support this without any changes to their codebase, the user just has to set the one know boolean to disable animations.
* Because `window.y11a.animations` is an object, its future-proof. E.g. jQuery might introduce `window.y11a.animation.maxLength` to automatically limit animation length.

**Comment by gtarnoff** [comment]
Wow, someone actually forked my Codepen :) @fletcher91 that's awesome. If you don't mind I have some time off coming up so I plan on getting back to https://github.com/gtarnoff/omrijs which is intended to be a library for this. I'd love help.

Also, not sure why I never got pinged on this.

**Comment by MarjaE2** [comment]
The Chrome webstore has animation, though.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @fletcher91, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
