### ISSUE TITLE
Alphabetizing links on resources page

### ISSUE THREAD

**Issue by AllThingsSmitty** [a11yproject/a11yproject.com#361]
As the list of resources grows would there be any advantage/benefit to ordering the resources in each list alphabetically?

**Comment by joe-watkins** [comment]
I'd be into that :+1:

**Comment by AllThingsSmitty** [comment]
If we can get a consensus that would be nice but I may submit a PR for this, too.

**Comment by davatron5000** [comment]
Totally down. Thanks, Matt.

**Comment by AllThingsSmitty** [comment]
Submitted PR https://github.com/a11yproject/a11yproject.com/pull/362. Should we document this so contributors will know to follow the alphabetical pattern?

**Comment by davatron5000** [comment]
Merged #362. Might be good to document our decision in `Contributing.md`

**Comment by AllThingsSmitty** [comment]
@davatron5000 I'll work on adding a blurb about it there.

**Comment by AllThingsSmitty** [comment]
Submitted PR https://github.com/a11yproject/a11yproject.com/pull/363 with this information.
