### ISSUE TITLE
Inaccuracy: Search Landmark in Accessibility Checklist

### ISSUE THREAD

**Issue by JasonNeel** [a11yproject/a11yproject.com#365]
In the [Web Accessibility Checklist](http://a11yproject.com/checklist.html), under the landmark section, the example of using the search role is inaccurate, per [this blog post on Adrian Roselli’s website](http://adrianroselli.com/2015/08/where-to-put-your-search-role.html) (found via [Aaron Gustafson](http://www.aaron-gustafson.com/notebook/links/where-to-put-your-search-role/)):

> A proper form already has the form role thanks to its own native semantics…The reason you don’t want to override the native role is that the search role doesn’t replicate the form role,…

Currently, the checklist has `<form role="search">`. I think maybe something like `<div role="search"><form>…</form></div>` or `<form><div role="search">…</div></form>` would be more advisable.

Thoughts?

**Comment by davatron5000** [comment]
Yeah. We should definitely change it (and maybe provide a link to that blog post?). 

```
<form><div role="search">…</div></form>
```

^^ That would probably be my preference. Kind of a bummer the extra DOM node is necessary. :(

**Comment by davatron5000** [comment]
Updated to `div[role="search]"`. Fixed in ffac06953aec99d73988ad66d97b738f6256c52d
