### ISSUE TITLE
Additional resources

### ISSUE THREAD

**Issue by prettydiff** [a11yproject/a11yproject.com#368]
I am putting together a list of any accessibility tools I come across on Github that are written in either JavaScript and/or HTML. https://github.com/prettydiff/a11y-tools/

Several of the items on the list came from your resources page, but there are some handy looking tools in this list not mentioned in the resources page.

**Comment by davatron5000** [comment]
Nice list! Maybe we should merge efforts :wink: Our Resouces page is getting an overhaul and will be a lot clearer once the Redesign ships (#324 )

**Comment by prettydiff** [comment]
Absolutely.  I just compiled this list because I don't want to have to lookup accessibility resources in the future.  It doesn't matter where the list lives.  I am just happy to contribute.

**Comment by jfc3-dol** [comment]
Under the "Blog" section, I would  suggest adding Karl Groves blog - http://www.karlgroves.com/, which contains a lot of business reasons for accessibility articles, along with Denis Boudreau's accessibility tips blog - http://dboudreau.tumblr.com/

Under the "Professional Help" section you should add SSB Bart Group - http://www.ssbbartgroup.com/.

Under "Further Reading" I would add Anne Gibson's Pastry Box Project post "An Alphabet of Accessibility Issues" https://the-pastry-box-project.net/anne-gibson/2014-July-31.
Along with:

WebAIM's

"Skip Navigation" - http://www.webaim.org/techniques/skipnav/
"Using ARIA to Enhance Web Application Accessibility" - http://webaim.org/presentations/2012/ahgaria/
"Hierarchy for Motivating Accessibility Change" - http://webaim.org/blog/motivating-accessibility-change/

2014 - 24-Hour Online Community Event Celebrating Global Accessibility Awareness Day - videos - http://www.inclusivedesign24.org/

Roger Johansson - "Accessible Tables" - http://www.456bereastreet.com/archive/200410/bring_on_the_tables/

**Comment by webuxr** [comment]
@davatron5000 I have a small PR open #452 that I could update with the suggestions @jfc3-dol has mentioned above. Would that make things easier for you/maintainers (i.e.: to help close #452 and #368 at the same time)?

**Comment by davatron5000** [comment]
@webuxr Let's do it separate. I'll merge #452 now. Make another PR and reference this here. Thanks so much!

**Comment by webuxr** [comment]
@davatron5000 and @jfc3-dol I'm on it!

**Comment by davatron5000** [comment]
@webuxr Also, I went thru and tagged all issues and PRs with a "Resources" label. 

https://github.com/a11yproject/a11yproject.com/labels/Resources

Most of the PRs are out of date (old HTML format), so they're un-mergeable. If you want to roll those up into one big commit that replaces all of those that'd make you an open source hero 🥇

**Comment by webuxr** [comment]
@jfc3-dol ...couple questions:

1. The content within the [Using ARIA to Enhance Web Application Accessibility](http://webaim.org/presentations/2012/ahgaria/) link is a [bit cheeky](http://webaim.org/presentations/2012/ahgaria/captcha), seems dated, and [may not be around much longer](http://weba.im/). **Thoughts on why we should still list it?**
2. The [2014 - 24-Hour Online Community Event...](http://www.inclusivedesign24.org/) link also seems dated. **Perhaps we should link to the main [Global Accessibility Awareness Day](http://globalaccessibilityawarenessday.org/) site instead?**
3. The Accessible Tables link is great, but so is most of Roger Johansson's _456 Bera Street_ site. **Why not [link there](http://www.456bereastreet.com/) instead?**

Everything else looks great.

**Comment by webuxr** [comment]
@davatron5000 That'll make things easy. I'll chip away at them as I have time.

**Comment by jfc3-dol** [comment]
My responses to your questions @webuxr.

1. The slides still gets the points across about ARIA. The shortened URL might be gone but the rest of Web AIM's content is still there. I assume Web AIM's website is listed as a resource?
2. Why not point to all of the 24-Hour videos by year because they separate from Global Accessibility Awareness Day website and both are good resources.

- Main Website and 2016 videos - http://www.inclusivedesign24.org/
- 2015 Videos - http://www.inclusivedesign24.org/2015/
- 2014 Videos - http://www.inclusivedesign24.org/2014/

I would list the main 24-hour website, each years, video page, and the Global Accessibility Awareness Day website.

3. I think you could point to Roger Johansson's 456 Bera Street website along with the tables article. Why not make it easier to help people find good specific articles and websites that have more.

**Comment by webuxr** [comment]
Also, I'm wondering if I can add a `description` token to the resources.html and resources.yml assets? Adding this new token would be a small amount of work for me and would make the resources page a lot easier on the eyes. Here's what I'm thinking.

# Add Description Token
## Existing Code
### Snippet from resources.yaml
```
resources:
    - url: https://chrome.google.com/webstore/detail/accessibility-developer
      title: "Chrome Accessibility Tools (Chrome Mac/Win)"
```

### Snippet from resources.html
```
<a href="{{ resource.url }}" rel="external">{{ resource.title }}</a>
```
### As currently implemented, produces this
* [A link example with a description - Etc, etc, etc.](#)
* [Chrome Accessibility Tools - Extension (Chrome Mac/Win)](https://chrome.google.com/webstore/detail/accessibility-developer)
* [A link example without a description](#)

## Proposed Changes
### Changes to snippet from above (resources.yaml)
```
resources:
    - url: https://chrome.google.com/webstore/detail/accessibility-developer
      title: "Chrome Accessibility Tools"
      description: "Extension (Chrome Mac/Win)"
```

### Changes to snippet from above (resources.html)
```
<a href="{{ resource.url }}" rel="external">
          {{resource.title}}
</a>{% if resource.description %}<span> - {{ resource.description }}</span>{% endif %}
```

### If proposal is implemented, would produce this
* [A link example with a description](#) - Etc, etc, etc.
* [Chrome Accessibility Tools](https://chrome.google.com/webstore/detail/accessibility-developer) - Extension (Chrome Mac/Win)
* [A link example without a description](#)

I think breaking out a short description from the title of the link would greatly help to make these lists much more readable (easier to scan) and more consistent as well.

@davatron5000 what do you think?

**Comment by davatron5000** [comment]
@webuxr 👍 :shipit:
