### ISSUE TITLE
Bug: Update README.md to reflect current local development workflow

### ISSUE THREAD

**Issue by michaelck** [a11yproject/a11yproject.com#369]
Since Rakefile has been removed from the redesign branch, should the **Rake Commands** section just be replaced with instructions for getting a local view up and running, like ``` jekyll serve ```?

**Comment by davatron5000** [comment]
Definitely! We can roll out the redesign branch and patch this up real quick.

**Comment by ttimsmith** [comment]
Maybe I could tackle this? I'd like to contribute something

**Comment by michaelck** [comment]
I think this was closed back in January thanks to @davatron5000 - 5f24e9d
