### ISSUE TITLE
Article: Choosing between a Button or a Link

### ISSUE THREAD

**Issue by RachelRVasquez** [a11yproject/a11yproject.com#376]
Hi there!

Wrote up another thing! I didn't find this one on the a11y project site, and it's shorter than my last attempt. Basically it's the quick way to decide when to use a link and when to use a button element instead. Based on Karl Groves article about it as well. Open for feedback. :-)

https://gist.github.com/RachelRVasquez/d405e61de05551586509

Reference: http://www.karlgroves.com/2013/05/14/links-are-not-buttons-neither-are-divs-and-spans/

**Comment by davatron5000** [comment]
This is also super great @RachelRVasquez! My only suggestion for the code block of links is to include some HTML comment so people don't just skip to the code and copy/paste ;)

```
<!--- THE FOLLOWING HAVE TERRIBLE A11Y CODE SMELL -->

<a href=""> /// etc
```

Or something along those lines.

**Comment by thierryk** [comment]
fwiw, I would not include the last example as there is very little chance people go this route since the lack of `@href` makes that `<a>` as "useful" as a `<span>`&mdash;meaning it does not create a link/_tab stop_ (the reason why people usually abuse that). 

Also, I'm not sure about the `button` example:
```
<button role="button" ...
```

In my opinion, the `<button>` element - by itself - implies this role, so I'm not sure you should include it in your example.

**Comment by hmig** [comment]
I agree that <button> should not have the role on it because the role is implicit for button. For more info on this: [On HTML belts and ARIA braces On HTML belts and ARIA braces](http://html5doctor.com/on-html-belts-and-aria-braces/) by Steve Faulkner.

**Comment by hmig** [comment]
I'd also suggest focusing on coding for semantics and styling for look. 

Example:

*If your element is a link to another page (or part of the current page), use the <code>`<a>`</code> element.
*If your element performs an action, such as submitting a form or triggering some javascript event, then use a  <code>`<button>`</code> element.

Use styles like .btn and .link to ensure the elements look the way you want, but code them according to their purpose.

**Comment by RachelRVasquez** [comment]
Thanks @thierryk @davatron5000 @hmig for the feedback! It's super helpful. Going to make edits now. Now that it's been mentioned, it is redundant to use the role of button on a button element. I did this out of habit - now's the time for me to stop doing that haha. As for using the `<a>` without an href, I'd still like to keep the example whether it's "useful" as a span or not, semantics wise, it shouldn't be used that way. We want to convince people it's either a button or a link without a grey area. Meaning it's probably confusing to explain it like: 

"Never use the `<a>` element if it doesn't have a destination - except in this case if you want to use it like a span."

Versus setting a clear line between using the element or not. It's an action, then it's a button, it's a destination, then it's a link. No in betweens. No "cheating" so to speak semantically. At least that's what's helped me stick to the habit as a developer and avoid using the `<a>` elements in cases where I shouldn't. I'll make some edits to be more clear about semantics if it helps.

**Comment by RachelRVasquez** [comment]
@thierryk @davatron5000 @hmig 

The gist has been updated with changes based on everyone's feedback. Thanks again! :-)

**Comment by thierryk** [comment]
@RachelRVasquez 

> "Never use the <a> element if it doesn't have a destination - except in this case if you want to use it like a span."

This is not what I said. I mentioned `span` to point out that that example was not "realistic"&mdash;unlike the 3 other with a `@href`. Anyway, you could say something like this instead:

"Never use the `<a>` element with a `href` attribute if it doesn't have a _destination_.

Also, I'm not sure of the `<button>` example:
```
<button name="newsletter-modal-trigger" class="modal-trigger">
    Sign up for our newsletter!
</button>
```
because I think one could argue that this could as well be a **jump link** (the title of the modal could be a named anchor). It may be better to use a more straightforward example. May be something like:
```
<button class="larger-font">
    Increase text-size
</button>
```

As a side note, the button example should not show a `name` attribute since there is no form submission.

**Comment by RachelRVasquez** [comment]
@thierryk Ah sorry, I re-read that and misunderstood. You're saying it's an unlikely example because without the href, it's pretty much the equivalent of a span. Not that it *should* be used like a span. I'm not sure how many people have attempted it, but just for the sake of showing various versions of "bad examples" we can leave it there? When I started out in development I didn't use elements semantically either. It was basically "Build it and if it looks good on the front-end, then it's a wrap!" Learning how to use everything properly was a learning progression. So in the event that someone like myself years ago, reads this, they'll get a head start and *not* write anything that resembles our bad examples. :-)

I've also used the "modal" example because it's the case I've seen most in the wild. I've seen this *so* much in code, that once I stopped doing it myself, when I'm sharing a project with someone else, I go in and correct it for them as well. It's like my senses are already honed to check how modals are being triggered and if it's a dead link, change it to a button haha! 

Perhaps some more context for the modal example will help? Or perhaps we can include a few mini examples including your suggestion? 

Regarding the `name` attribute on elements, I've been using it out of habit "in case" but now feeling like I should really [research this attribute more](http://www.w3.org/TR/html4/interact/forms.html#h-17.13.2) so I can truly understand it. W3C says we need it for forms (as you stated) to be a successful control, but I'm wondering if `name` attributes outside forms can be useful if they're needed when writing JS?

**Comment by mattdistefano** [comment]
So I'm new here, but I hope you don't mind some feedback.

1. The `role="button"` is superfluous, but it might be worth getting into the `type` attribute a bit. I don't know that it's an a11y concern per se, but the behavior of untyped buttons in forms can be a little unpredictable for devs unaccustomed to using them.
2. In the modal example, I think the choice of `a` or `button` would depend on how the modal is implemented. I've used both in the past, but thinking about it some more now, IMO `a` would only be appropriate if there was actual navigation happening. That is, if you could enter/exit the modal by changing the URL or using the back/forward buttons. Ideally the modal itself will be a familiar paradigm and users wouldn't be confused, but I think `a` implies "I'm going somewhere new, but I can hit back to return to where I am now", and most modals in the wild won't work that way.

**Comment by nattarnoff** [comment]
@mattdistefano There is a solid argument around progressive enhancement for `a` over `button` if it behaves like you described, example:

The contents of the modal are a container of the page with it's own ID `<div id="modal">....</div>` and if the JS loads, this is hidden. Then the `a` drives you to the container if the JS doesn't load as it is a valid URL.

However, I don't think I've ever seen a modal work this way.

**Comment by mattdistefano** [comment]
I think it's fairly common to clone/move an existing DOM node vs. building a new one, but actually handling the navigation so you have `#modal` in the URL seems much less common (though I want to say I've seen some SPAs that have dedicated modal routes, for example). 

TBH I'm not sure if navigability jives with the semantics of the "dialog" role, though.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @RachelRVasquez, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
