### ISSUE TITLE
Implicit ARIA-Roles

### ISSUE THREAD

**Issue by pstonier** [a11yproject/a11yproject.com#378]
> Web developers should not set the ARIA role and aria-* attributes to values that match the default implicit ARIA semantics defined in the table.

http://www.w3.org/TR/html-aria/#document-conformance-requirements-for-use-of-aria-attributes-in-html

This should be explained when covering ARIA Landmark Roles.
 
For example: 
> `header`:  Default Implicit ARIA semantics - should not be used — If not a descendant of an article or section element role=banner is applied by the browser, otherwise no corresponding role

**Comment by joe-watkins** [comment]
Hi @pstonier This sure is a hot topic on this project :) As a team we are still of the camp to include the role attributes on landmarks until browser support is wider. The W3C takes a fairly aggressive approach when recommending no need for attribute these attributes. They don't do the best job explaining the fact that only modern web browsers and AT are going to jive with this recommendation. 

With little to no negative side effects, that I've ran into, including the attributes widens browser support making the experience more robust.

now.. with that being said we are in the progress of trying to address this in the Landmark Roles page.. it just needs to be worded well to not create even more confusion. We encourage a PR on it :)

Anyone else have thoughts on this? I still feel like we are in the 'aria polyfill' stage.

**Comment by joe-watkins** [comment]
I should clarify that 'wider browser support' means.. 'while we still must support some old fart browsers & AT' :)

Pinging @RachelRVasquez because she's been contributing some great writing to the project.

**Comment by pstonier** [comment]
Ah. That makes sense. Thanks for the clarification. I hadn't thought about the repercussions of this on older browsers.

**Comment by hmig** [comment]
I think I'll give a stab at trying to write up some clear instructions/verbiage. ;)

**Comment by pstonier** [comment]
@hmig  I just found some additional background in case you do want to write something about this. https://github.com/Automattic/_s/issues/786

**Comment by hmig** [comment]
I had posted a bug here as well, but to the checklist. ;)

**Comment by RachelRVasquez** [comment]
@joe-watkins Thanks! I've been writing a whole lot for this project. Looks like this topic has been tackled though - I'm still open for other topics. I've got some time today before my vacation hits and looking for contributions to make. ;-)

**Comment by hmig** [comment]
Shoot. Forgot to mention this issue in my pr. https://github.com/a11yproject/a11yproject.com/pull/380

**Comment by davatron5000** [comment]
Verbiage about HTML5 Implicit Roles merged in ffac06953aec99d73988ad66d97b738f6256c52d
