### ISSUE TITLE
Articale: How to configure the Firefox browser for high color contrast

### ISSUE THREAD

**Issue by msuberrivs** [a11yproject/a11yproject.com#379]
Hi There,

I would like submit an article that is a mini tutorial on the configuration of the Firefox browser for high contrast viewing.

I am new to the site and I am not sure if an article on this subject would be beneficial. 

Any comments or suggestion would be most welcome.

Moshe

**Comment by davatron5000** [comment]
Hi, Moshe! Sounds interesting. Could you maybe start with an outline or rough draft in a [GitHub Gist](http://gist.github.com)? That's probably the best way to go forward. Any screenshots might need to be on imgur.com for now.

Thanks.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @msuberrivs, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
