### ISSUE TITLE
Article: Testing Your Designs at Various Font Sizes

### ISSUE THREAD

**Issue by JasonNeel** [a11yproject/a11yproject.com#381]
Hi all!

I've been following this project for some time now, and am happy to see that it has come back to life in recent months!

I’ve not contributed in the past, but I thought that I would maybe throw my hat into the ring and offer to write something. I was browsing through the list of unclaimed topics for articles, and picked one I thought was kind of low-hanging-fruit: “Test text at 200%” under the “HOWTOs” heading. I’ve written a quick draft of my idea for a post, if you wanted to look it over and give me some feedback:

https://gist.github.com/JasonNeel/5366602cf79633b4a636

I wasn’t sure if this was the direction that was intended by the suggest topic or not. Instead of just writing towards testing designs at 200%, I thought I’d go a less specific route and talk about font resizing in general.

Is it in-depth enough? Does it need more? Let me know!

**Comment by joe-watkins** [comment]
@JasonNeel This is a great addition nice work. I love how simple it is but so important :) 

A small suggestion could be to encourage the user to do this test in multiple browsers and also perhaps add link to the AA WCAG 2.0 Guideline on [Resizing Text](http://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-scale.html). 

http://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-scale.html

**Comment by JasonNeel** [comment]
Thanks for the compliments and suggestions, @joe-watkins! I've incorporated those ideas into my gist.

**Comment by davatron5000** [comment]
> Make sure text remains legible at the various zoom levels. 

Maybe extend that to:

> Make sure text remains legible at the various zoom levels. Key User Interface elements (like navigation dropdowns) should still be usable with mouse and/or keyboard.

**Comment by JasonNeel** [comment]
Oh, nice suggestion @davatron5000. I’ve updated my gist with that language added. Thanks!

**Comment by MarjaE2** [comment]
Is the percentage the right answer? If things start at 6 pt, 200% zoom may not be enough to make things readable.

To minimize my migraines, I set a minimum font size of 24 pt, but I have to drop that sizes to use certain Firefox preferences.

**Comment by JasonNeel** [comment]
Hi @MarjaE2, I'm not sure what you're asking about here. Could you explain a little more about your question?

**Comment by MarjaE2** [comment]
I think it would help to test with minimum font sizes, as well as testing with percentage zooms.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @JasonNeel, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
