### ISSUE TITLE
A11Y Simple Tabs without jQuery

### ISSUE THREAD

**Issue by BeyondHyper** [a11yproject/a11yproject.com#390]
http://codepen.io/BeyondHyper/pen/xZXXzj

This is a tab solution based on Scott Vinkle's Simple Tabs (http://codepen.io/svinkle/pen/edmDF) removing the jQuery dependency and an enhanced presentation.

**Comment by joe-watkins** [comment]
@BeyondHyper Nice work! Heya.. are you able to create a PR for the pattern? If not let me know and I'll do it.

**Comment by BeyondHyper** [comment]
@joe-watkins - thanks! Yeah, I can do that.

**Comment by svinkle** [comment]
@BeyondHyper, nice work! 

FYI I recently updated my pen to include a `focus` event listener along with the `click`. Reason behind this change is when someone using the VO Rotor would find one of the tabs under the Form Controls menu, the tab panel content would not get updated on click. This small change helps to make sure when a tab gets focus, by other means other than the arrow keys, the tab panel content loads the appropriate content. With this change you could also remove the `tabClickEvent()` calls from the `keyboardEvent()` function, but test first. :)

**Comment by BeyondHyper** [comment]
@svinkle , thanks for the info! I don't think most people (including me) were/are thinking about voice over. I will take a look and adjust accordingly.

**Comment by thierryk** [comment]
I think it is important that any example posted offers a proper fallback (i.e. with JS off). 
For example, in @BeyondHyper's last Pen the jump links do not seem to work without JS.

**Comment by BeyondHyper** [comment]
@thierryk: Agreed! I just updated my anchors. It was a typo issue.

**Comment by BeyondHyper** [comment]
@svinkle - wondering the reason for adding a click and focus listener since the item will gain focus when clicked and call the tabClick function? Also, in your current repo, when you click the tab, it is jumping to the anchor. Is this expected behavior?

**Comment by svinkle** [comment]
@BeyondHyper, just fixed the jump-link issue by separating the `click` and `focus` events in to their own listener. Should be good now.

**Comment by BeyondHyper** [comment]
@svinkle - I separated mine as well and am just calling the preventDefault method on click since the element will gain focus on click and fire the tabClick function.

**Comment by thierryk** [comment]
I just created a pen for this ([Pure CSS Tab Panel](http://codepen.io/thierry/full/gPoWxj/)), not sure if it is worth adding it to the list though...

**Comment by svinkle** [comment]
@thierryk, nice use of `:target`. That has always confused me as to when and how to use it.

I'd suggest reading the [WAI-ARIA Tab Panel Widget Authoring Practice](https://www.w3.org/TR/wai-aria-practices/#tabpanel) and see if you can get in some of the roles and aria properties. Right now it's quite confusing as the tabs are announced as radio buttons and with no accessible name. It would be idea if the tab names were also in each label, and the tabs were announced as tabs.

This could be a bit difficult without JavaScript, but give it a go. I'm curious to see how it turns out.

**Comment by thierryk** [comment]
@svinkle the whole point of this is that it is **not** conveyed to AT users as a _Tab Panel widget_ but as a succession of heading/section&mdash;which is much easier for people to create a mental model from.
This should not be confusing to screen-reader users though as all controls should be **ignored** as I'm using `<input aria-hidden="true" ...>`. I ran some tests using Voice Over/Chrome and these controls were not announced. Also, a couple of my "Accessibility friends" looked at it and didn't report any issue. 
What SR did you use?
Thanks for the feedback!

**Comment by svinkle** [comment]
@thierryk, ah, I understand. I also see where it went wrong for me. The middle tab `input` does not have `aria-hidden=true`, so when I _saw_ that I was on a tab, and used the arrow keys to navigate which led to the tab in the middle being announced as a radio button. Also, you might want to add `tabindex=-1` to the radio controls so they don't receive focus, which would also prevent the arrow keys from functioning.

**Comment by thierryk** [comment]
@svinkle Ah! Good catch. I didn't see I missed a control. But I don't want to add `tabindex="-1"` because that would make the tabs totally **inaccessible** to sighted keyboard users.
