### ISSUE TITLE
Article: How–to: Use Skip Navigation links - JS alternative not truly needed

### ISSUE THREAD

**Issue by ngoodrum** [a11yproject/a11yproject.com#395]
The Javascript alternative listed is because a tabindex isn't set on a tag that isn't in normal tab flow. The Chrome bug does seem to be for anchors as well but it looks like tabindex bypasses the issue regardless. Since more people are moving from using named anchors for jump points and are using wrapping containers / headings, using the tabindex="-1" or 0 would be a good method regardless and doesn't require JS. 

I'm not sure removing the disclaimer is necessary since there are quirks. However, adding in an alternative note would be helpful. If necessary an explanation of tabindex could be included.

**Comment by thierryk** [comment]
> using the tabindex="-1" or 0 would be a good method

It should be `tabindex="-1"`, not `tabindex="0"`, because the latter would create a "meaningless" tab stop - which is not really good for skip links which usually target sections.

**Comment by ngoodrum** [comment]
I included it as an option since it depends on the complexity of what is planned for the skip. If possibly the area has an aria-describedby attached to it or maybe some functionality related to it that you might want to come back to. However, I'm fine with just tabindex="-1" since it is an introductory post and the example is fairly simple. That's why I was thinking a better clarification of tabindex would be helpful.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @ngoodrum, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
