### ISSUE TITLE
Simple Manually-Activated Multiple Item Carousel

### ISSUE THREAD

**Issue by robfentress** [a11yproject/a11yproject.com#412]
[http://codepen.io/robfentress/pen/grGRbX](http://codepen.io/robfentress/pen/grGRbX)
This was designed in response to the following expressed need: 4 individual statistics from a list of 6 or more need to be displayed at a time. Clicking a next button causes 2 items from the list to be removed from the beginning of the view, and the next 2 items from the list to be added to the end of the view.  If the end of the list is reach, then it cycles, adding items from the beginning of the list to the view, as in a carousel.  The same behavior occurs in reverse for the Previous button.

The interesting feature of this is that four items are displayed at a time with two being pushed onto the displayed items at a time, but only the ones that are added are voiced.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @robfentress, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
