### ISSUE TITLE
Article: Accessible Typography

### ISSUE THREAD

**Issue by inclusiveThinking** [a11yproject/a11yproject.com#417]
Contributing an article on Accessible Typography. Should it possibly be under "Misc" instead of "Quick Tests"?

**Comment by davatron5000** [comment]
@inclusiveThinking Thanks for helping out. It might be a "How to" ? Like "How-to: Create accessible typography"? We can always re-categorize if necessary.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @inclusiveThinking, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
