### ISSUE TITLE
Bug: Broken link

### ISSUE THREAD

**Issue by tzae** [a11yproject/a11yproject.com#419]
The link to the article on `alt` text at the checklist page [Images section]((http://a11yproject.com/checklist.html#images)) is broken. 

It should be:

 <http://a11yproject.com/posts/alt-text.html> 

instead of 

<http://a11yproject.com/posts/alt-text/>

**Comment by davatron5000** [comment]
Thanks for letting us know. This is a duplicate. There's a fix for this in #405, just need to QA it and merge it.
