### ISSUE TITLE
Frend: A collection of accessible, modern front-end components.

### ISSUE THREAD

**Issue by grayghostvisuals** [a11yproject/a11yproject.com#420]
Possible inclusion for resources/patterns section [http://frend.co/](http://frend.co/)

**Comment by webuxr** [comment]
@grayghostvisuals: Why not edit and add this link to the [Resources page YML file](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/_data/resources.yml), under the "_HTML Related_" and/or "_Online Tools_" sections, then submit a pull request?

I'm new to [contributing to the a11yproject](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md) so am not sure if this is the correct protocol or not however, now that you have [this](https://github.com/a11yproject/a11yproject.com/issues/420) issue created, why not tag it in your commit/pull request?

Depending on the responses to my comment here (you have dibs of course), I might just try this myself.

Thoughts?
_rs

**Comment by davatron5000** [comment]
Merging with #319 

@webuxr I'll follow up there...
