### ISSUE TITLE
Pattern: Accessible Availability Grid (audible keyboard shortcuts)

### ISSUE THREAD

**Issue by jpdevries** [a11yproject/a11yproject.com#425]
Hello a11y friends. I've been working on an accessible AvailabilityGrid component that is HTML&ndash;first, uses "custom styled" native `<input type="checkbox">` elements, and supports screen readers and keyboards.

![](https://camo.githubusercontent.com/e1ddaf38a8f36898fdd273fda48ba6ca4a8e2b2f/687474703a2f2f6a34702e75732f3039334932793052333232412f6865726f2e676966)

I created a CodePen to show the gist of it, but please note you'll need to take a look at the demo on GitHub to see the progressively enhanced JavaScript version.
http://codepen.io/jpdevries/pen/QEvyGo?editors=1100
https://github.com/jpdevries/availability-grid#demo

Perhaps this components contains multiple "patterns" but the main one I would like to share is the use of accessibly hidden text along with `aria-describedby` to read aloud not only what checkbox they are on but the [keyboard shortcuts available for them to use](https://github.com/jpdevries/availability-grid#usability-considerations).
![](https://camo.githubusercontent.com/141aa8261aedb5f487eabd99f3be6d94baaf25c2/687474703a2f2f6a34702e75732f304e324a304b3053313230322f53637265656e25323053686f74253230323031362d30362d31352532306174253230342e31342e3330253230504d2e706e67)

**Comment by joe-watkins** [comment]
@jpdevries This is slick! Nice work -- very usable.

The only thing that makes me scratch my chin a bit would be keyboard instructions may be confusing/verbose for users that may not be using a keyboard.

**Comment by jpdevries** [comment]
@joe-watkins ya, that is a good point. Also currently it will give you those "hints" every time, which could get annoying. I've been kind of going back and forth and experimenting with things like that. Is something like that helpful? Is it annoying? I haven't got a chance to read through these yet:
Responses To The Screen Reader Strategy Survey | HeydonWorks http://www.heydonworks.com/article/responses-to-the-screen-reader-strategy-survey

but I'm sure there is some great insight in there from people who use screen readers day in and day out.

**Comment by svinkle** [comment]
@jpdevries, any update on this pattern?

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @jpdevries, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
