### ISSUE TITLE
Bug: Links to local posts with trailing slashes return 404

### ISSUE THREAD

**Issue by jennschiffer** [a11yproject/a11yproject.com#427]
Looking at [the checklist page](http://a11yproject.com/checklist.html), any posts to the rest of this site that had a trailing slash added to the href attribute leads to a 404. Without a slash works. 

Looking into it, it looks like it may be a new Jekyll config deal: https://github.com/jekyll/jekyll/issues/4440

I would update and try but I cannot get `bundle install` to work (like https://github.com/bundler/bundler/issues/4467).

**Comment by davatron5000** [comment]
Thanks, @jennschiffer. We just fixed this with #405.  Sorry it took so long to get merged in.
