### ISSUE TITLE
Web Accessibility Checklist 404

### ISSUE THREAD

**Issue by MrGeneric** [a11yproject/a11yproject.com#430]
Hi,
The [Quick Tip: Aria Landmark Roles and HTML5 Implicit Mapping](a11yproject.com/posts/aria-landmark-roles/) link on the [Web Accessibility Checklist](http://a11yproject.com/checklist.html) returns a 404.

Seems to be just missing the scheme part (http://).

Thanks

**Comment by MrGeneric** [comment]
Noticed the same issue with the [Read article on using ALT text](http://a11yproject.com/posts/alt-text/) link.

**Comment by davatron5000** [comment]
Thanks for reporting! This is a known issue and will be fixed in #405. Just need that QA'd. 

I'll merge this issue into there and work on getting that QA'd.
