### ISSUE TITLE
Bug: Dead link to modal window article on patterns

### ISSUE THREAD

**Issue by joekrie** [a11yproject/a11yproject.com#436]
The [Patterns page](http://a11yproject.com/patterns/) has a dead link under "Modal Windows":

The Incredible Accessible Modal Window, Version 3
https://accessibility.oit.ncsu.edu/training/aria/modal-window/version-3/

It appears that the NC State Accessibility site removed it's article on modals. If you go to [Accessibility Handbook content](https://accessibility.oit.ncsu.edu/developers/accessibility-handbook/) and scroll down to "Step 5", "Modal Window" is not a link.

**Comment by nschonni** [comment]
Thier search still returns it too https://oit.ncsu.edu/search/?q=modal, but I noticed at the side there is this message
>
CAN’T FIND WHAT YOU’RE LOOKING FOR?
We recently redesigned and restructured our website, so some content may have been temporarily misplaced.

> If there's something you can't find, please email help@ncsu.edu.

**Comment by BeyondHyper** [comment]
I searched the site and the the link listed in the query results is also dead. I then when through their training page and the article is not listed there either. I sent them an email asking if the article would be added back. I'll update this here when I get a response.

**Comment by derick-montague** [comment]
So, I finally received a follow up from the university. The response was to look in the way back machine and a link. 

https://web.archive.org/web/20150928220111/http://accessibility.oit.ncsu.edu/training/aria/modal-window/version-3/

I did find that the Github repo:  https://github.com/gdkraus/accessible-modal-dialog

I've created a pen for it here: http://codepen.io/BeyondHyper/pen/NREjpP

**Comment by derick-montague** [comment]
@joe-watkins or whoever @davatron5000  merged this issue, it can be closed.
