### ISSUE TITLE
Bug: Link to 'Various Twitter Accounts' is dead

### ISSUE THREAD

**Issue by hxmattobee** [a11yproject/a11yproject.com#437]
The link to 'Various Twitter Accounts' (https://medium.com/web-accessibility/8f7161340cc1) in the Community Help section of the Resources page is returning 404.

**Comment by joe-watkins** [comment]
Hmm... good catch! @hxmattobee 

We could swap that out with a little project I started: [Top people to follow in Web Accessibility](https://github.com/joe-watkins/top-people-to-follow-in-web-accessibility)

**Comment by hxmattobee** [comment]
Agreed @joe-watkins, looks good 👍

**Comment by davatron5000** [comment]
Looks like this was changed to "Web Accessibility content tagged on Medium" in #454. I think we could merge @joe-watkins' link in a separate PR. It's a good link.
