### ISSUE TITLE
Skip to Content Link required for screen readers

### ISSUE THREAD

**Issue by schappaughc** [a11yproject/a11yproject.com#453]
What landmark should this have so it will pass testing tools?

If your navigation contains many links and comes before the main content in the DOM, add a Skip to main content link before the navigation (for a simple explanation, see this A11Y Project article on skip navigation links). Using the .sr-only class will visually hide the skip link, and the .sr-only-focusable class will ensure that the link becomes visible once focused (for sighted keyboard users).

**Comment by joe-watkins** [comment]
@schappaughc #394 was merged and [you can read more about Skip Navs](http://a11yproject.com/posts/skip-nav-links/).
