### ISSUE TITLE
Read markdown documents in the terminal

### ISSUE THREAD

**Issue by prettydiff** [a11yproject/a11yproject.com#456]
I don't know if this is any kind of help, but I needed to read markdown from the terminal, so I wrote a markdown to ANSI parser in this distribution tool I am working on.  The goal is to read documents directly, as they are intended, without need for external tools (aside from screen readers).  Fortunately, most text that appears in the terminal is accessible by default (including \u001b formatting modifiers, which are probably ignored) due to the primitive nature of that interface.

The costs are that the data is not structured (unlike HTML/XML), so its just paragraphs of text, but this tool will format for usability and that formatting could be inferred for other things so long as the formatting is applied in a uniform manner.  To get added benefit from this screen readers could infer structure due to indentation.  I am indenting text according to the heading level.  Level 1 headings and their following text get no indentation, while level 2 headings impose 1 step of indentation to all following text, level 3 headings 2 steps, and so forth.

The distribution tool is https://github.com/prettydiff/biddle and you would read documents with a command something like

    node biddle markupdown myRelativePath/myDocument.md 60

Where the 60 is the word wrap limit (default is 80).

**Comment by webuxr** [comment]
@prettydiff How does reading markdown docs within a Terminal interface relate to the A11y Project website? I understand your described need for a markdown parser in the terminal. That actually sounds neat.

On the other hand (and please forgive me if this sounds confrontational, it's not meant to be), unless you are making a proposal for new content or suggesting a content addition, I'm not sure what you're getting at here by posting this as an issue affecting the A11y Project website.

Perhaps this issue relates to some existing content on the A11y Project website that I'm not aware of? If so, my apologies.

**Comment by prettydiff** [comment]
Its just an unorthodox tool suggestion.

**Comment by davatron5000** [comment]
@prettydiff I think this is a cool project but probably out of scope for a11yproject. I actually have use for a CLI-based markdown reader. Thanks for sharing it but I'll close this out.
