### ISSUE TITLE
Twitter Cards and OpenGraph tags

### ISSUE THREAD

**Issue by jedd-ahyoung** [a11yproject/a11yproject.com#468]
Adding Twitter cards to the site would be a nice touch for enhanced visibility when posting links to A11yproject.com on Twitter. The implementation is fairly simple: Twitter looks for a set of `meta` tags with for the information required. Jekyll can generate the correct tags for specific articles.

Twitter also takes advantage of OpenGraph tags, which are used by other media sites.

https://dev.twitter.com/cards/overview

**Comment by joe-watkins** [comment]
@jedd-ahyoung tnx for the great idea -- I've created a PR tackling this in #478

**Comment by joe-watkins** [comment]
#478 was merged
