### ISSUE TITLE
Suggestion: Include HTML5 Video Caption Maker 

### ISSUE THREAD

**Issue by plfstr** [a11yproject/a11yproject.com#469]
A suggestion for the, ‘Using Caption Services with HTML5 Video’ post. 

Perhaps the [Transcribing section](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/_posts/2013-07-17-using-caption-services-with-html5-video.md#transcribing) could include a mention of the [HTML5 Video Caption Maker](http://samples.msdn.microsoft.com/Workshop/samples/media/captionmaker/default.html) which allows you to view and transcribe a video side by side.

**Comment by joe-watkins** [comment]
@plfstr This is a great addition. Are you able to make the Pull Request to add this?

**Comment by joe-watkins** [comment]
@plfstr tnx!!
