### ISSUE TITLE
ARIA alert Role Example

### ISSUE THREAD

**Issue by malikfaizanhaider** [a11yproject/a11yproject.com#481]
Please tell me how to read alert messages via screen readers.

**Comment by joe-watkins** [comment]
Hi @malikfaizanhaider `role="alert"` can be VERY frustrating and it is because browser support is not consistent. [Learn more about some different ways to approach the alert role](https://www.paciellogroup.com/blog/2012/06/html5-accessibility-chops-aria-rolealert-browser-support/).
