### ISSUE TITLE
Update nesting of headings

### ISSUE THREAD

**Issue by scottaohara** [a11yproject/a11yproject.com#483]
Hi there,

I noticed on the index page that the different sections started with ```<h2>``` but each of the lead-in subheadings skipped over ```<h3>``` and instead used ```<h4>```.

I will be [submitting a PR](https://github.com/a11yproject/a11yproject.com/pull/484) to change the heading level from 4 to 3, while maintaining the current visual design of the current site.

**Comment by joe-watkins** [comment]
good eye! @scottaohara tnx :)
