### ISSUE TITLE
Fix for invalid ul nesting on pattern page

### ISSUE THREAD

**Issue by scottaohara** [a11yproject/a11yproject.com#486]
Noticed a bug in the sub-category list creation on the patterns page, where an unnecessary ```<ul>``` was being injected as a direct child of an existing ```<ul>```.

[This pr](https://github.com/a11yproject/a11yproject.com/pull/485) removes the unnecessary ```<ul>```.

**Comment by joe-watkins** [comment]
tnx @scottaohara !!
