### ISSUE TITLE
Broken link in Skip Nav Link Post

### ISSUE THREAD

**Issue by scottaohara** [a11yproject/a11yproject.com#487]
Hi there,

Seems that my PRs, [484](https://github.com/a11yproject/a11yproject.com/pull/484), [485](https://github.com/a11yproject/a11yproject.com/pull/485) are currently failing travis-ci due to a broken external link on the How-to: Use skip navigation links article.

This particular link is the culprit: https://www.nczonline.net/blog/2013/01/15/fixing-skip-to-content-links/

It looks like Nicholas C. Zakas's entire website is currently offline, and only after an extended period of time, will a Cloudflare snapshot of the site render.

**Comment by mindlessroman** [comment]
I just checked the site and it rendered....? https://www.nczonline.net/blog/2013/01/15/fixing-skip-to-content-links/ And the site is pingable atm. 
That aside, it would probably make sense to drop the site for something more stable?

**Comment by nschonni** [comment]
@joe-watkins do you have permission to restart the Travis builds? It looks like the site is up now and those PRs can get retested

**Comment by scottaohara** [comment]
oh good!  glad to see it's back up and running.

**Comment by mindlessroman** [comment]
@nschonni @joe-watkins - the same sort of thing was happening in the build for #482 on travis-ci; the urls that failed then now are pinagble.  I guess it depends on whether having a pristine "builds passed" record is needed/desired. But if all the PR builds are run again, then they should be good to go, imo

**Comment by joe-watkins** [comment]
I've merged those two latest PRs and disabled the Travis build -- while broken/dead links are a bummer it shouldn't hold back great contributions.
