### ISSUE TITLE
Pattern: Show focus styles on keyboard events only

### ISSUE THREAD

**Issue by svinkle** [a11yproject/a11yproject.com#492]
This is something I came up with a few days ago per client request; show focus styles only on keyboard events: https://codepen.io/svinkle/pen/zzrORW

Not sure if we'd like to feature this as a pattern as it encourages an anti-pattern (`outline: 0`). If not, we could do something with the `:focus-ring` [polyfill](https://github.com/WICG/focus-ring/blob/master/src/focus-ring.js). Thoughts?

**Comment by davatron5000** [comment]
I've been reaching out to Rob Dodson at Google to see if browser sentiment is there for focus-ring and when it might be implemented. I think once we know more and it does seem like it's moving forward we could recommend the polyfill. I have clients asking for it as well. 
		

		
	





On Sun, Jun 11, 2017 at 10:32 PM -0500, "Scott Vinkle" <notifications@github.com> wrote:












This is something I came up with a few days ago per client request; show focus styles only on keyboard events: https://codepen.io/svinkle/pen/zzrORW


Not sure if we'd like to feature this as a pattern as it encourages an anti-pattern (outline: 0). If not, we could do something with the :focus-ring polyfill. Thoughts?

**Comment by svinkle** [comment]
Sounds good, @davatron5000. Let's wait for that to happen and have a decent pattern to recommend. Closing this.
