### ISSUE TITLE
Pattern: Accessible SVG Link List with Tooltips

### ISSUE THREAD

**Issue by svinkle** [a11yproject/a11yproject.com#498]
Hi all!

Looking for feedback on this pattern: https://codepen.io/svinkle/pen/pwYRzM/

This link list tries to be a consistent and accessible user experience across browsers/assistive technologies. Features:

- SVG sprite
- CSS tooltips
- `aria-hidden` attribute on SVGs to hide from AT
- No SVG `<title>` elements as they are wildly inconsistent across browsers/AT
- Links are described via tooltip text for screen reader users
- Tooltips are visually displayed on `:hover` and `:focus` for keyboard-only users
- Browser default focus styles for keyboard-only and low-vision users
- Tested with Safari/VO, Firefox/NVDA, IE/JAWS, Chrome/TalkBack

/cc @davatron5000 @joe-watkins @jeryj

**Comment by jeryj** [comment]
Howdy @svinkle!

Tested quickly in Chrome with mouse, keyboard, and VoiceOver. All works well here!

My 2 cents:
1. If there's a way to make `.link-list__tooltip{ margin-left: -32px;}` not a magic number (I tried a quick `left: 0; right: 0;` but it wasn't centered perfectly (which I imagine you tried and noticed as well).
2. Why `aria-hidden=true` and not `aria-role=presentation`?

Overall looks great! 💯  Would fork.

**Comment by joe-watkins** [comment]
@svinkle Sweet! Good one -- checks out in NVDA FF / JAWS IE as well.

You could level up the nerd factor if you wanted to support old fart browsers just for fun.. not really an a11y thing but more of a progressive enhancement angle.. by offering a raster image version of the icon using the `<image>` attribute. Browsers that don't understand `<svg>` will load the image. Fault tolerance FTW! :)

Example here: https://codepen.io/joe-watkins/pen/MoxEzd

**Comment by svinkle** [comment]
Hey @jeryj! 

1. Great point about the magic numbers. I went in an refactored those out; much better solution now! 
2. I prefer to apply `aria-hidden` as this hides the SVG and any child elements completely from AT. In a way this is treating the SVG the same as applying `alt-""` on purely decorative images. If there's a `<title>` or anything else embedded in the SVG, we only want the tooltip text to describe the link. Using `role="presentation"` basically just removes the role announcement from AT but any text within the element still gets announced.

Thanks for looking an the great questions!

**Comment by svinkle** [comment]
@joe-watkins Nice add! I'm not sure if I want to include this as SVG support does go way back. Well, perhaps not so far for SVG sprites like I have hear. I think is someone needed that level of support, they could look it up. For example, I found this article with a different solution than yours. Not sure which is correct? https://webdesign.tutsplus.com/tutorials/how-to-implement-cross-browser-svg-sprites--cms-22427
