### ISSUE TITLE
inaccuracy in 'how to hide content'

### ISSUE THREAD

**Issue by mfairchild365** [a11yproject/a11yproject.com#499]
This article has a potential inaccuracy: http://a11yproject.com/posts/how-to-hide-content/

Specifically, I don't think the `body:hover` portions of the suggested css work as intended. Per the now deleted Yahoo article that this post is based on, the `body:hover` styles are meant to `display: none` visually-hidden content that is in the focus order. The idea being that if visually hidden content is focused, it might cause the screen to scroll and/or end up with a confusing tab order for a sighted keyboard-only user.

However, not all screen reader users are totally blind keyboard-only users. I don't think it is safe to assume that screen reader users will never use a mouse, or active `:hover` styles.

I was going to suggest that a better solution would be to apply a `tabindex="-1"` to visually hidden, but natively focusable content (such as an `<a>` or `<button>`), but I think the better solution is to display that content visually on hover, similar to the skip nav pattern.

So my proposed solution is to 1) remove the `:hover` css, and 2) describe how to implement the skip-nav-like pattern for visually hidden but natively focusable content.

I'd like a few people to weigh in before I submit a PR to fix this.

**Comment by svinkle** [comment]
@mfairchild365, thanks for your feedback! I think you're correct, this article is mad out-of-date and could use some tlc. That `.visually-hidden` class should be updated with the latest offering from [h5bp CSS](https://github.com/h5bp/html5-boilerplate/blob/bad87b9f54bcacd85bce4bd687b871592a111f77/dist/css/main.css#L137).

The best course of action would be to fork the article and make your changes in a gist. Then add the link to the gist here for folks to review.

**Comment by svinkle** [comment]
@mfairchild365, any luck creating a new gist with your changes?
