### ISSUE TITLE
Pattern: Toggletip from paragraph

### ISSUE THREAD

**Issue by svinkle** [a11yproject/a11yproject.com#500]
Pretty rad tooltip from @Heydon: https://codepen.io/heydon/pen/Vzwdpy

I like it. Thoughts?
/cc @davatron5000 @joe-watkins @jeryj

**Comment by joe-watkins** [comment]
@svinkle That is slick! Performs very well.

This raises a good question about our standards for native ES6 code.. should we recommend compilation for submissions? e.g. Babel?

**Comment by svinkle** [comment]
@joe-watkins I think any sort of preprocessor/compiler is optional, but acceptable as CodePen makes it easy to see/copy the compiled code.

**Comment by Heydon** [comment]
I can rewrite it so that it doesn't use string interpolation? Not difficult.

**Comment by Heydon** [comment]
@svinkle It's rewritten now to be ES5. https://codepen.io/heydon/pen/Vzwdpy

**Comment by svinkle** [comment]
All good, @Heydon. Thanks!
