### ISSUE TITLE
inaccuracy in article never-remove-css-outlines

### ISSUE THREAD

**Issue by sgregson** [a11yproject/a11yproject.com#503]
While `Style the element itself. You can remove the outline as long as you style the focused element differently` is a valid approach to dealing with removal of outlines, the examples shouldn't use color change as an example. This directly contradicts WCAG2.0 1.4.1 and in some cases is a specific failure criteria (links and interactive components).

https://www.w3.org/TR/WCAG20/#visual-audio-contrast-without-color

> *1.4.1* Use of Color: Color is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element. (Level A)

https://www.w3.org/TR/WCAG20-TECHS/F73.html

> The objective of this failure is to avoid situations in which people who cannot perceive color differences cannot identify links (when people with color vision can identify links). Link underlines or some other non-color visual distinction are required (when the links are discernible to those with color vision).

> While some links may be visually evident from page design and context, such as navigational links, links within text are often visually understood only from their own display attributes. Removing the underline and leaving only the color difference for such links would be a failure because there would be no other visual indication (besides color) that it is a link.

I'll draft a PR tonight with alternative examples and specific language about avoiding color-only changes if there's no issues.

**Comment by svinkle** [comment]
@sgregson, any luck drafting this PR?

**Comment by scottaohara** [comment]
@sgregson just want to follow up on if this is still something you want to work on?

**Comment by RyanAaronGreen** [comment]
Hey @scottaohara! Just wanted to round back on this, it looks like you've marked this as complete in #669 (at least checked). Do we still need someone to make this update?

**Comment by scottaohara** [comment]
Hi @RyanAaronGreen 
The checklist is to indicate that an audit was performed, but not that work was necessarily completed.  e.g. there are items checked off that now have, or in the case of this article, already had issues opened for them to update.  [See my next comment in 669](https://github.com/a11yproject/a11yproject.com/issues/669#issuecomment-441085121)

With that said, if you'd like to take on the task of providing an update for this, by all means :)  it'd be much appreciated!
