### ISSUE TITLE
IE 11 bug - Logo treatment

### ISSUE THREAD

**Issue by joe-watkins** [a11yproject/a11yproject.com#525]
The logo area of the site in IE11 is borked.

![2017-09-03_11-59-56](https://user-images.githubusercontent.com/3695795/30005814-a14cd6a4-909f-11e7-8775-5d27816c0e18.png)

**Comment by derick-montague** [comment]
You just need to set a height on the SVG. Set it to 1.4em (same as width) and you'll be good. I don't have a local environment for this project set up yet, but I tested it using Dev tools in IE 11, FF, Chrome, and Edge.

**Comment by joe-watkins** [comment]
Fixed in #530
