### ISSUE TITLE
Bug: Link at Comprehension Level not working

### ISSUE THREAD

**Issue by evaferreira** [a11yproject/a11yproject.com#536]
I'm getting a 404 with the first link (Read-able.com) in http://a11yproject.com/posts/check-comprehension-level/ 

Maybe this is the new link? https://www.webpagefx.com/tools/read-able/ I can submit a PR if that's correct!

**Comment by scottaohara** [comment]
Hey there!

Just gave this a look and the link seems to be working on my end.   Maybe there was an outage or hiccup in the redirect?

But checking the present link and the one that you posted, they definitely are the same.  Probably a good idea to update the link.  Want to do the PR?

Thanks!

**Comment by evaferreira** [comment]
Done! https://github.com/a11yproject/a11yproject.com/pull/537

Thanks and sorry for the trouble (:

**Comment by scottaohara** [comment]
What trouble? No trouble at all!  Thank you for helping out :) !!!
