### ISSUE TITLE
Article: Colour blindness introduction

### ISSUE THREAD

**Issue by mtthwhggns** [a11yproject/a11yproject.com#538]
I've started turning some old talk notes into a few short articles, some of which match things from the "List of Post Ideas". 

This first one is the "Introduction to color blindness". 

I'm still planning some heavy editing, switching things over to the American spellings and updating a few bits and pieces, but I'd really like some feedback on the general structure and scope. 

Here's the current gist; https://gist.github.com/mtthwhggns/bba634db0c980a73f74aed0447518745

**Comment by svinkle** [comment]
Thanks for your submission, @mtthwhggns! I've left a few items to adjust over on your gist.

Let me know when you've had a chance to fix those up!

**Comment by mtthwhggns** [comment]
Hi @svinkle ,

Thanks for the feedback.

I've made all of your suggested changes, except the last one, where I think neither of our ideas really explained what I was thinking. I've written something new you can take a look at, in the paragraph two-from-bottom. Any more feedback is most welcome.

One question; I've (automatically) used British spelling. Should we use US English to match all of the content on this website, or should we stick to the writer's own dialect?

**Comment by svinkle** [comment]
@mtthwhggns Excellent! I like the way that paragraph reads now; it's a tough thing to explain for sure.

And no, leave the spelling as is. In the spirit of inclusivity, diversity should be celebrated, and that even includes unique language quirks.

Create the PR and let's get this merged. 👍
