### ISSUE TITLE
Dropdown menu uses incorrect ARIA roles

### ISSUE THREAD

**Issue by aardrian** [a11yproject/a11yproject.com#544]
The pattern for the dropdown menu at http://a11yproject.com/patterns.html#menus uses a code example that leans on ARIA menu roles: https://codepen.io/grayghostvisuals/pen/ltjDa

If this is a pattern for an *application* menu (not web site/page navigation, but something that lives in `role="application`) then I suggest the following:

- Add `role="application` so that screen readers do not intercept the keys that the menu supports.
- Add support for `Home`, `End`, `Shift` +`F10`,
- Remove the 'role="navigation"` from the `<nav>` element since it is a mis-match for this menu.
- Change how the menu is referenced and refer to it as an application menu, with all the caveats that entails.

If this is a pattern for web site navigation (the links within the example suggest it is), then I suggest the following:

- Remove all the roles (the one on `<nav>` is fine, though overkill if targeting recent browsers).
- Remove support for the arrow keys and `Space` key (as this intercepts page scrolling behavior).

When I have some time I can provide an alternate example web site navigation menu.

Context comes from the [ARIA 1.1 specification](https://www.w3.org/TR/wai-aria-1.1/). It suggests these three roles do not belong here:

- [`menu`](https://www.w3.org/TR/wai-aria-1.1/#menu) (role): A `menu` is often a list of common actions or functions that the user can invoke. The `menu` role is appropriate when a list of menu items is presented in a manner similar to a menu on a desktop application.

- [`menubar`](https://www.w3.org/TR/wai-aria-1.1/#menubar) (role): The `menubar` role is used to create a menu bar similar to those found in Windows, Mac, and Gnome desktop applications. A menu bar is used to create a consistent set of frequently used commands. Authors should ensure that `menubar` interaction is similar to the typical menu bar interaction in a desktop graphical user interface.

- [`menuitem`](https://www.w3.org/TR/wai-aria-1.1/#menuitem) (role): An option in a set of choices contained by a `menu` or `menubar`.

It also suggests this role is more appropriate:

- [navigation](https://www.w3.org/TR/wai-aria-1.1/#navigation) (role): A collection of navigational elements (usually links) for navigating the document or related documents.

But since the `<nav>` element does that job, it isn't even necessary. It also suggest nesting any of the menu roles under the navigation role is incorrect.

The The [WAI-ARIA Authoring Practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/#menu) document provides further guidance on expected keyboard interaction if going down this route.

**Comment by svinkle** [comment]
Thanks, @aardrian this is fantastic stuff.

What we should do is update the current pattern to reflect these notes, and perhaps someone could create another patter which is appropriate for the `role="menu"` context.

@grayghostvisuals, are you up for adjusting your pattern? Otherwise I can make a fork and relink on the patterns page.

**Comment by grayghostvisuals** [comment]
> Otherwise I can make a fork and relink on the patterns page.

👍
