### ISSUE TITLE
Live aXe-core Webinar: Updates and aXe Coconut

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#547]
[Join our free webinar](https://accessibility.deque.com/accessibility-testing-axe-core-webinar) on Tuesday, November 7th, from 2-3PM EST and learn what's new with aXe-core 3.0-alpha and how to test with aXe Coconut. This webinar is organized by Deque Systems and presented by Marcy Sutton.

**Comment by ericwbailey** [comment]
Added in https://github.com/a11yproject/a11yproject.com/pull/551.
