### ISSUE TITLE
Live Panel: Are you Ready for the Section 508 Refresh?

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#549]
[Join us on Wednesday, December 6th](https://accessibility.deque.com/section-508-refresh-panel) at 9:00AM to learn the steps you and your agency can take for organizational readiness for the Section 508 Refresh. 

Doors will open at 8:30AM at the Westin Crystal City and we welcome attendees to stay and network after the panel until 12:00PM. This panel is hosted by Deque Systems and [includes a panel of Section 508 experts](https://accessibility.deque.com/section-508-refresh-panel).

**Comment by ericwbailey** [comment]
Added in https://github.com/a11yproject/a11yproject.com/pull/551.
