### ISSUE TITLE
Ann Arbor Web Accessibility Meetup

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#550]
Our first event! [You should come](https://www.meetup.com/a2a11y/events/243778915/) on Monday, November 13th from 6-8PM. This will be a pretty low-key social gathering to give us all the opportunity to hang out with others who are interested in digital accessibility. 

Bring ideas for what you'd like to get out of an accessibility meetup! Also, feel free to reach out to either of us organizers with any questions or concerns. We plan to send out a survey to all members after the event to gather feedback and suggestions.

**Comment by ericwbailey** [comment]
Added in https://github.com/a11yproject/a11yproject.com/pull/551.
