### ISSUE TITLE
Resources subnav truncated on desktop

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#564]
If the screen is short enough, the bottom of the resource list sidebar is cut off when scrolling to the bottom of the page.

I wonder if we could do a little consolidation of subcategories to get around this without any fancy CSS/JS work.

![Gif demonstrating the scrolling truncation issue. Screen recording.](https://user-images.githubusercontent.com/634191/34048664-915de538-e182-11e7-920f-00984152cfab.gif)

**Comment by svinkle** [comment]
Subcategories sounds like a band-aid solution to me. There's no guarantees that the same issue won't come up even after consolidation.

That said, curious what you have in mind. 🤔

**Comment by ericwbailey** [comment]
Lemme stew on it.

**Comment by joe-watkins** [comment]
I wonder if the `offset` property in the Waypoint/TOC JS that could be hacked.. it triggers the `.stick-footer` which helps with positioning of the fixed sidebar once the footer is in view. Need that to kick in sooner.

**Comment by ericwbailey** [comment]
Thanks @joe-watkins, that's a great starting point! I've got PR merged that should fix it: https://github.com/a11yproject/a11yproject.com/pull/565
