### ISSUE TITLE
Quick tip: Safari Keyboard Navigation

### ISSUE THREAD

**Issue by svinkle** [a11yproject/a11yproject.com#569]
Just wrote a quick tip article on enabling full keyboard support in Safari for my fellow Shopifolk and thought I'd share it here.

Here's the gist for review: https://gist.github.com/svinkle/a429c127db5358ec0bd8b42ab6c9ee78

**Comment by ericwbailey** [comment]
Love it! 

`defaults write NSGlobalDomain AppleKeyboardUIMode -int 3` in the Terminal enables keyboard control on the OS, if Shopify uses a config script for new machines.

**Comment by scottaohara** [comment]
Nice.

I wrote about this on my blog awhile ago too.  Going to add a link to this for additional information per the Safari bit you wrote.  Wasn't aware of that.

**Comment by svinkle** [comment]
@ericwbailey Really? And yes they do. Gonna share this! 🔥
