### ISSUE TITLE
Live Webinar: Using Personas as an Inclusive Design Tool

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#580]
[Join us on February 27th at 1PM EST](https://accessibility.deque.com/creating-ux-design-personas-webinar), Denis Boudreau and Caitlin Geier, two of our UX accessibility experts, will talk about creating personas which you can use to promote inclusive design in your workplace and to design websites and applications which work for a broad variety of people. This is the first part of our new UX and Inclusive Design webinar series. In this webinar you will learn:

- What personas are, and how they fit into the UX process
- How representing disabilities and other needs in personas influences design decisions
- How designing for inclusion informs the overall design process
- How designing for extreme cases results in a better user experience for everyone
- How to build your own accessibility personas to create a more inclusive product

**Comment by ericwbailey** [comment]
All set, thanks! https://github.com/a11yproject/a11yproject.com/pull/581
