### ISSUE TITLE
More web accessibility conferences in aApril 2018

### ISSUE THREAD

**Issue by anqaka** [a11yproject/a11yproject.com#589]
I'm not hosting the conferences but I've done some research in web and I found two really interesting:
1. Funka Accessibility Days 2018

- event link: https://www.funka.com/en/we-offer/funka-accessibility-days/
- 17-18.04 in Stockholm
- Description from their website: 'During the 10th anniversary of the Funka Accessibility Days 17-18 April, much will of course revolve around the Web Accessibility Directive, and the new European accessibility standard that the public sector must meet. We will also focus on the latest version of the international guidelines WCAG 2.1 and the latest in accessible technology, design and content.'

2. Web4All

- event link: http://www.w4a.info/2018/
- 23-25.04 in Lyon
- Description form their website: W4A continues to be a premiere venue for accessibility research, and we welcome submissions in any of our traditional core areas covering all aspects of web accessibility. We invite your best work that advances our understanding of access for people across the accessibility continuum.

**Comment by svinkle** [comment]
@anqaka Thanks for the info and links! 👍
