### ISSUE TITLE
Accessible by Design Conference

### ISSUE THREAD

**Issue by wbobe** [a11yproject/a11yproject.com#590]
Accessible by Design: Creating more inclusive digital experiences

May 8, 2018
Bloomington, IN

The one-day Accessibility conference offers software designers, programmers, and higher-ed leaders a chance to hear from professionals in the field and get some hands-on experience in a tactic-oriented workshop format. [Read more about the line-up and register at accessiblebydesign.org](https://accessiblebydesign.org)

**Comment by ericwbailey** [comment]
Thanks for the submission, looks like a cool event 👍
