### ISSUE TITLE
Live Webinar: Intro to Accessibility Heuristics

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#592]
[Join us on Tuesday, April 10th from 1:00-2:00PM EST](http://bit.ly/2FYT8QI), to learn the fundamentals of heuristics as a design evaluation tool. Our UX accessibility experts, Denis Boudreau and Caitlin Geier will introduce a set of accessibility-focused heuristics which can help you assess accessibility during the design phase.  

In this webinar you will:

- Understand what usability heuristics are and who they are for
- Learn why assessing accessibility at the design phase matters
- See how accessibility heuristics can help meet goals for digital inclusion
- Get an introduction to a set of accessibility-focused heuristics
- Learn how you can apply heuristics to your own work

**Comment by ericwbailey** [comment]
Thanks! You're all set! https://github.com/a11yproject/a11yproject.com/pull/593
