### ISSUE TITLE
Live Webinar: An Introduction to Screen Readers

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#595]
[Join our live webinar on Thursday, May 17th from 1:00-2:00PM EST](https://accessibility.deque.com/live-webinar-introduction-to-screen-readers)
In this webinar, Steve Sawczyn, Solutions Architect at Deque Systems, will demonstrate how he uses a screen reader to navigate the web. In celebration of Global Accessibility Awareness Day (GAAD), this fundamentals-based webinar will provide developers, designers, business users or anyone new to digital accessibility a first-hand experience of how people who are visually impaired navigate the web. In this webinar you will:

- Experience a screen reader simulation first-hand
- Understand how a screen reader navigates a web page
- Hear how a screen reader announces the content on a page
- Discover common design barriers that trap or make the web inaccessible to persons using assistive technologies
- Learn an introduction to accessibility testing with screen readers

**Comment by ericwbailey** [comment]
All set, thanks! https://github.com/a11yproject/a11yproject.com/pull/597
