### ISSUE TITLE
Seattle Meetup: Global Accessibility Awareness Day 2018

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#596]
To celebrate Global Accessibility Awareness Day 2018 (http://globalaccessibilityawarenessday.org/), we're coming together as a community to share ideas and get inspired. [Come learn about web accessibility perspectives ](https://www.meetup.com/a11ysea/events/249275750/)and techniques from other Meetup members and make new friends.

We're so excited to see everyone! If your schedule changes closer to the event and you can't attend, please update your RSVP to allow people to join from the wait list. That will also help the food and drink situation!

Event location:
Expedia
645 Elliott Ave W · Seattle, WA

Date & Time:
6-8:30pm Thursday, May 17

Accommodations:
If you need ASL or other accommodations in order to attend this event, please let us know as soon as possible to allow enough time for planning and scheduling.

**Comment by ericwbailey** [comment]
All set, thanks! https://github.com/a11yproject/a11yproject.com/pull/597
