### ISSUE TITLE
Link to W3 site on this page not resolving to correct page https://a11yproject.com/posts/getting-started-aria/ 

### ISSUE THREAD

**Issue by nellyk** [a11yproject/a11yproject.com#599]
The links  found on this page are not working and are resolving to an error page. 

Roles - http://www.w3.org/TR/wai-aria/roles
States and Properties - http://www.w3.org/TR/wai-aria/states_and_properties

Can i create a pull request to update them to the correct links?

Roles - https://www.w3.org/WAI/PF/aria/roles
States and Properties - https://www.w3.org/WAI/PF/aria/states_and_properties

**Comment by ptrin** [comment]
Checked the issues to see whether anyone had reported this. The system works!
