### ISSUE TITLE
Article: MYTHBUSTED: Accessibility is just turning off CSS

### ISSUE THREAD

**Issue by ValorNaram** [a11yproject/a11yproject.com#603]
The post on https://github.com/a11yproject/a11yproject.com/issues/12 inspired me to write a short article for you to publish on your site.

Note: I am not good at writing articles and this is probably my first one, so I am open for better ones, corrections, additions etc.

You can check out my gist at https://gist.github.com/ValorNaram/161d5afdc5db1212ae81fb3531ab56d2

**Comment by ValorNaram** [comment]
I updated my gist, please review the updated version and give feedback. In my article I also cover the problem we frontend web developers have with accessibility.

**Comment by svinkle** [comment]
This is quite difficult to read. I would suggest running the content through https://hemingwayapp.com/ as a starting point.
