### ISSUE TITLE
Cleveland Accessibility - A11yCLE Brand, Mission, and Vision Meetup

### ISSUE THREAD

**Issue by mbozz** [a11yproject/a11yproject.com#613]
August 8, 2018

Please join us as Melanie Bozzelli and Kate Penrod lead us through an exercise to develop a brand, mission, and vision for our [Cleveland Accessibility Meetup](https://www.meetup.com/Cleveland-Accessibility-Meetup/events/252287250/). These essential elements will provide the foundation upon which we build our long-term success. [Visit our Meetup link to sign up for this meeting](https://www.meetup.com/Cleveland-Accessibility-Meetup/events/252287250/).

**Comment by ericwbailey** [comment]
Addressed in https://github.com/a11yproject/a11yproject.com/pull/616

Thank you for your submission and best of luck with the event!
