### ISSUE TITLE
Add authors & updaters to all applicable posts

### ISSUE THREAD

**Issue by scottaohara** [a11yproject/a11yproject.com#617]
There are a bunch of posts on the site that do not have authors, or attribution to those who have updated an article, who were not the original author.

We should review previous posts and 
1. Note the author (may require reviewing commit history)
2. Note the updater (if different from the original author)

Question:
Should we add a link to an author's name to have a link back to their websites / social media accounts?

**Comment by ericwbailey** [comment]
I'm always a fan of attribution, so I'm a fan of this.

I know this balloons the effort involved, but we might want to reach out and confirm with the author/editor if they want that info added.

**Comment by svinkle** [comment]
Wasn't this a recent PR?

**Comment by scottaohara** [comment]
No, but I spoke to you about it in the context of another PR.

**Comment by ericwbailey** [comment]
Asked for permission for some people whose contact info they made available. I figure I'll start adding it in if I get replies.

**Comment by ericwbailey** [comment]
Here's the first pass: https://github.com/a11yproject/a11yproject.com/pull/638
