### ISSUE TITLE
Please add link to Accessibility Scotland 2018

### ISSUE THREAD

**Issue by mathalete** [a11yproject/a11yproject.com#622]
Hello there.

We're running Accessibility Scotland again this year.

It's on the 9th of November here in Edinburgh.

More information can be found on our website > https://accessibility.scot/

Thanks!

**Comment by ericwbailey** [comment]
All set, thank you! https://a11yproject.com/events#accessibility-scotland

**Comment by mathalete** [comment]
Cheers Eric.

**Comment by ericwbailey** [comment]
Ah, sorry about that. It should be all set now;
