### ISSUE TITLE
Question: Is the order of the categories intentional?

### ISSUE THREAD

**Issue by ptrin** [a11yproject/a11yproject.com#628]
Hi, 

The order of categories in the navigation and on the homepage is:

**Categories**

- How-tos
- Myths
- Quick tests
- Quick tips
- Assistive technology
- Basics

Is there a reason for this order? Should we consider starting with Basics for people who are new to accessibility?

**Comment by jeryj** [comment]
The original intention (right or wrong) of the homepage was to have a dev or designer be able to learn something they could put into practice within the first minute of being on the site. I think the Basics section would be a better fit for getting someone in for the long haul of learning web accessibility, and Quick Tips and How-Tos would be better for getting someone to implement _something_ and then learn more later.

Looking at the Basics section, it may serve from a rename. Maybe "Background"? I definitely agree that the order seems odd when looking at it in that category list :)

**Comment by ericwbailey** [comment]
Ah, that makes sense! I don't think we'd be risking breaking too much if we renamed, considering the URLs for that section are `/posts/`.

**Comment by svinkle** [comment]
Reading over the topics of what's under this section, I feel like these posts are more "advanced" or a "deep-dive" into a very specific topic. I'm on board with a rename as I wouldn't consider these "basic" concepts.

**Comment by scottaohara** [comment]
Yeh, looking at each, i'm in the middle.  they're more intermediate topics, but I don't think i'd call them that?  Each is more than a quick tip, but none of them provide a full narrative on the topic.

**Comment by ericwbailey** [comment]
Closed via #634
