### ISSUE TITLE
Add a style guide for content

### ISSUE THREAD

**Issue by missmatsuko** [a11yproject/a11yproject.com#629]
I think it would be helpful to have a style guide for content contributions to keep content nice and consistent.

I noticed that color/colour is spelled different ways on the website, and even within the same article:
https://a11yproject.com/posts/understanding-colourblindness/

I also read this comment on a PR that mentions some conventions that I couldn't find formally recorded in a single file:
https://github.com/a11yproject/a11yproject.com/issues/516#issuecomment-324784426

**Comment by ericwbailey** [comment]
I also think this is a good idea, thank you! If you get an initial PR ready, say a Markdown file in the repo's root, we can have a discussion about it there.

**Comment by ericwbailey** [comment]
Yeah. I think it'd be better to point to CONTENT_STYLE_GUIDE.md from CONTRIBUTING.md. I'd prefer to segment it into "here's how to behave when you want to work with us," and "here's what to know when you write for us." It'd also make for a shorter contributing doc, which I think would help people actually reading it!

As for the guide, I think that's a great starting point! I'm also a big fan of [Shopify's](https://polaris.shopify.com/content/product-content#navigation).

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/640
