### ISSUE TITLE
Inaccuracy: Quick Test: Navigate using just your keyboard

### ISSUE THREAD

**Issue by missmatsuko** [a11yproject/a11yproject.com#631]
https://a11yproject.com/posts/navigate-using-just-your-keyboard/

- As with other Quick Tests, I have no idea what 'Estimated Time' means (issue #630). Furthermore the amount of time to run this test would entirely depend on how much content there is to go through and how interactive it is. 5 seconds of tabbing is probably enough to go through a small amount of content.
- Step 1, "Un-plug/turn off your mouse." - there is no need to do this in order to tab through a web page.
- Step 2, "Use the Tab key browse." - doesn't cover Safari's default controls to navigate by keyboard, which is `tab + alt`. Some more details on this here: https://a11yproject.com/posts/safari-keyboard-navigation/
- Step 3, "Use Enter to select elements." - unclear what "select" means here. Tabbing would presumably focus the element if it's focusable. Entering would trigger a click action if it's interactive (e.g. link or button). Might be good to provide more info about what space and enter do on anchors and buttons.

**Comment by missmatsuko** [comment]
Made a gist here for review/feedback:
https://gist.github.com/missmatsuko/7548490d2fe040cc4fd0309b708fcfc3

**Comment by scottaohara** [comment]
I think this is a good start on revising this article to make it more informative.

In how to navigate a site with keyboard, when talking about macOS defaults for tabbing, it probably makes sense to link to the post you mentioned in this issue (https://a11yproject.com/posts/safari-keyboard-navigation/)

I have a couple of other small comments, but probably it'd be great if you wanted to revise the original article with the contents of your gist, and then we can do a full review on a PR for replacing the original piece :)

**Comment by missmatsuko** [comment]
Cool, I can make a PR later today with the added link.

As an aside, I thought that issues were used for discussions based on this part of the contrib: https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#plain-text-workflow-for-article-submission

Is that still accurate?

**Comment by ericwbailey** [comment]
This was written before Github rolled our better review tools. Might be worth revisiting this, too.

**Comment by missmatsuko** [comment]
Ah, that makes sense. I thought it was to reduce the number of commits added to include one new article or something.

**Comment by ericwbailey** [comment]
Addressed in https://github.com/a11yproject/a11yproject.com/pull/635

`CONTRIBUTING.MD` issues will be addressed shortly.
