### ISSUE TITLE
Allow other options for Follow

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#633]
It seems like a lot of the a11y community is migrating away from Twitter, or at least testing out other options like Mastodon. 

It might be worth updating the Follow page to indicate their preferred form of social media.

**Comment by KharVarsha** [comment]
Thanks for your message.
Will check it tomorrow.

**Comment by ericwbailey** [comment]
Closing this because I realize we sort of allow this with an arbitrary URL. If and when we redesign it might be good to include a little service icon.
