### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by missmatsuko** [a11yproject/a11yproject.com#636]
- [Set up Locally](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#set-up-locally) instructions differ from [Local Development](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/README.md#local-development) instructions in the README. I think the README's instructions are more up-to-date, but I haven't tried either yet.
- Update processes involving Gists and issues? I don't know the common procedure now, but based on [the convo starting in this issue](https://github.com/a11yproject/a11yproject.com/issues/631#issuecomment-414351166) it seems like Gists aren't necessary and discussions are done in PRs?

**Comment by ericwbailey** [comment]
I'm working on this as we speak 🙂

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/640
