### ISSUE TITLE
Intro to Talkback and Android Accessibility

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#639]
**[September 18th, 1:00pm - 2:00pm EST](https://accessibility.deque.com/intro-to-talkback-and-native-android-accessibility)**

Our Mobile Developer and A11y Expert, Chris McMeeking, will walk you through how to navigate and test for accessibility with Talkback.

Chris has 5+ years of mobile application development experience and has worked with the Android Open Source Project. Currently, he is the Senior Software Engineer at Deque Systems, architect of Deque’s Native Accessibility analysis solutions. Chris has been working in accessibility since he was a sophomore in college, where he started a project to create a keyboard for children with cerebral palsy. Chris is also an active member of the W3C (World Wide Web Consortium) mobile working group that is defining international standards for accessibility.

In this webinar you will learn:
- An in-depth demonstration and introduction to Talkback, the built-in screen reader for Android devices.
- How you can navigate your applications with Talkback via explore by touch and other gestures.
- A demonstration of an inaccessible application and designs as they interact with Talkback.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/2f4595e0cf0f0a8352bf4981812c735836fe03e4.
