### ISSUE TITLE
What you need to know about WCAG 2.1 webinar

### ISSUE THREAD

**Issue by msapega** [a11yproject/a11yproject.com#644]
Date: September 26
Time: 12pm EST

In this 30-minute webinar, Léonie Watson from The Paciello Group will look at the business case for adopting the Web Content Accessibility Guidelines (WCAG) 2.1. In this compact briefing, she will consider the following key questions:

What are the differences between WCAG 2.0 and WCAG 2.1?
What are the legal considerations of adopting WCAG 2.1?
What are the benefits of adopting WCAG 2.1?
Are there risks to adopting WCAG 2.1?
What is the migration path for adopting WCAG 2.1?

Register for the webinar here: https://zoom.us/webinar/register/4615355480419/WN__Ajriw-dQt65h4__cTZZ5A

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/584c47b8a0e1e7c80e552764a2ced098e8abaa81
