### ISSUE TITLE
Projects & the Future of a11yproject.com

### ISSUE THREAD

**Issue by RyanAaronGreen** [a11yproject/a11yproject.com#647]
Hey all!

Just wanted to suggest to the maintainers about maybe coming up with a projects tab or some more `help-wanted` posts to help keep people like me knowing how I can best be helping keep this project fresh. I'd love to hear the maintainers thoughts about where they want a11yproject.com to go and if there are any milestones that we can fight to reach as a community.

**Note:** I know that there are some `help-wanted` issues alive and I'm aware that this is not so much  an issue as much as it's a "Hey! How can I help?"

I'm sure I'm not the only one who wants to be contributing on a larger scale, so please let us know where you want this project to go and what steps need to happen in order to get us there.

**Comment by alexroseb** [comment]
I'm in a similar position! I'd love to do more work on this, whatever is as helpful as possible.

**Comment by svinkle** [comment]
Hey @RyanAaronGreen and @alexroseb! Thanks for reaching out.

The list of post ideas in #12 is always a good place to start. Also, if you see events being announced in the community, feel free to add to [_data/events.yml](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/_data/events.yml).

Or, if you have an idea and there's something specific you'd like to contribute, feel free to [create a new issue](https://github.com/a11yproject/a11yproject.com/issues/new) and let's chat about it! 🙂

**Comment by alexroseb** [comment]
@svinkle The main problem with #12 is that quite a few of those articles have been written but the post hasn't been updated. Also, there are a whole bunch of comments going back many years. Perhaps a place to start would be creating a new issue that clears the slate and only includes posts that haven't been written? I think that would help reduce the barrier to entry for others. 
I'll keep brainstorming for other contribution ideas.

**Comment by ericwbailey** [comment]
Seems in poor taste to close that issue and hide the historical record.

**Comment by RyanAaronGreen** [comment]
> Seems in poor taste to close that issue and hide the historical record.

I agree - I don't think we'd want to be rid of it.

My initial post was initially looking for some conversation on some of the higher level ideas of where the maintainers of a11yproject wanted to go. I was hoping to have more discussion on some goals for maybe the those interested in pushing things forward to focus on for the future. 

**Things such as the following:**
- We'd love the site to have bi-weekly posts centered around the concept of a11y to keep the site consistently fresh!
- Maybe a11yproject branded Youtube videos that walk through some of the fundamentals of what makes an accessible site (patterns, tutorials, etc)
- More patterns/conversations on javascript frameworks and how they should be working still with html.

I just wanted to pick everyone's brain a little because I wouldn't want to start pushing this project in a direction that it wasn't ever intended to go.

**Comment by davatron5000** [comment]
👋 Feel free to close #12. Or maybe se could even break up some of the most-wanted articles into `good-first-issue` (https://github.com/bnb/good-first-issue) type issues.

**Comment by ericwbailey** [comment]
Thanks, @scottaohara!

And that'd be great, @alexroseb! 

@RyanAaronGreen: Those suggestions also sound really cool. We actually just started undertaking a visual refresh with @tatianamac, so hopefully that'll help drum up some more interest. Right now we're thinking a documented living styleguide would be a great way to demonstrate how to build attractive and accessible UI. If that's something you'd specifically like to help out with, we'd love the support.

**Comment by svinkle** [comment]
![Captain Picard: "Make it so."](https://media.giphy.com/media/bKnEnd65zqxfq/giphy.gif)

**Comment by ericwbailey** [comment]
Updating to say we've added a bunch of [Help Wanted](https://github.com/a11yproject/a11yproject.com/issues?q=is%3Aissue+is%3Aopen+label%3A%22Help+Wanted%22) tags!

**Comment by ericwbailey** [comment]
Converting to use GitHub's new Discussion feature.
