### ISSUE TITLE
Munich Accessibility Meetup

### ISSUE THREAD

**Issue by nuriapenya** [a11yproject/a11yproject.com#652]
Hey there!

We just organised an **Accessibility Meetup group here in Munich**. The idea is to provide a welcoming place for people to learn, share experiences, ideas and best practices, and to collaborate on building a more inclusive web.

Here's the link to the group: https://www.meetup.com/Munich-Accessibility-Meetup/

And this is going to be our first event: https://www.meetup.com/Munich-Accessibility-Meetup/events/255477733/

We would be very thrilled if you could include this info in the list of events and Meetup groups so we can spread the word about them :)

Thanks a lot !!!

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/653

Thanks for adding the event to the site, it looks like it'll be a lot of fun! Congratulations, and best of luck for your inaugural event 🎉
