### ISSUE TITLE
Accessibility and Compliance: Current Legal Landscape

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#659]
[Join part one of our live webinar series on accessibility and compliance](https://accessibility.deque.com/accessibility-and-compliance-current-legal-landscape).
**November 27th, 1:00-2:00PM EST** 

**Teresa L. Jakubowski**, partner at Barnes & Thornburg LLP, will discuss the current litigation landscape for website accessibility. Teresa chairs the firm’s Accessibility and Disability Law Practice. Find out more about current trends in case decisions and claims involving web and digital accessibility.

In this webinar you will learn about:

- Recent case decisions, addressing coverage of websites and other issues such as due process, standing, mootness etc.
- Cases currently pending before the 11th and 9th Circuit Courts of Appeals (**Gil v. Winn-Dixie Stores** and **Robles v. Domino’s Pizza**)
- Expanding scope of claims, such as mobile applications
- Which accessibility standards current cases are utilizing
- How the current legal landscape is affecting covered entities

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/a3e899b3a2aaafc6a6aef9bad556c4634a0209d4.
