### ISSUE TITLE
Create YouTube series on testing for a11y

### ISSUE THREAD

**Issue by alexroseb** [a11yproject/a11yproject.com#663]
As discussed in #647, I'd like to start some informational YouTube videos that can appear on a11yproject.com and be fall under this umbrella. I'm proposing that the first series address how to test a website for accessibility. 
I'm imagining each video being only a few minutes long and composed of a screencast and voiceover to describe what I'm doing. Of course, I'd include captions as well as a transcript. 
This first series would include using tools like aXe, WAVE, and color contrast checkers, each showing how to use the tool and what to do with the results that are generated. I'd love suggestions for other tools to showcase as well.

**Comment by svinkle** [comment]
@alexroseb This sounds pretty great! I'd suggest making some videos and adding to your YouTube channel in order for us to review. That would be a good start.

**Comment by Pythonidaer** [comment]
This is a very cool idea! I am new to the game but if I can ever help I will let you all know. 

I was wondering: would comprehensiveness of the a11y project (checklists and whatnot) increase if videos were uploaded to the website? If so, then would those videos summarizing pages in more "plain-speak" (less jargon) be a useful guideline for what topics should be covered in videos?

Just a thought.

**Comment by ericwbailey** [comment]
Converting to use GitHub's new Discussion feature.
