### ISSUE TITLE
Virtual Panel: Inclusion and equality for people with disabilities in education and employment

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#665]
To commemorate International Persons with Disabilities Day, our panelists will discuss the experiences they've had in academic institutions and while seeking employment.

This webinar is intended to create awareness common barriers, opportunities, or resources for people with disabilities encounter at academic institutions or while seeking employment. This panel is a great introduction for people who are new to accessibility but want to learn more.

[Join this live webinar](https://accessibility.deque.com/inclusion-for-people-with-disabilities-education-employment) on December 3rd, from 10:00-11:00AM EST.

Panelists:

- **Anne Forrest**, Ph.D., has been recognized as one of the nation’s leading patient advocates for people with traumatic brain injury. She lives with persistent symptoms from a mild TBI that she received during a June 1997 car accident and continues to recover.
- **Jamie Knight** is a Senior Accessibility Specialist at BBC. Jamie enjoys mountain biking and is never seen far from his plush sidekick, Lion. Jamie's areas of expertise include accessibility, JavaScript, HTML, CSS and Autism.
- **Tim Harshbarger** is an Accessibility Consultant at Deque. Tim has been visually impaired since a young age, he is very passionate about accessibility and believes it should be a part of the web development process.
-**Birkir Gunnarsson** is a senior UX and Digital Accessibility Expert at BB&T. Birkir was born and raised in Iceland, attended Yale University, and has been visually impaired since the age of 5.
-**Dr. Paul Bohman** is the Director of Training at Deque Systems and Certification Chair or the International Association of Accessibility Professionals. Dr. Bohman is a multi-faceted educational technology leader and curriculum creator and analyst, whose doctoral dissertation evaluated masters-level technology education.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/8ccadd0a494139667ec666ea25367e5625e96978.
