### ISSUE TITLE
A11y Nottingham Event - 10/12/2018

### ISSUE THREAD

**Issue by hexproductionsben** [a11yproject/a11yproject.com#667]
Do you want to learn how to make what you’re creating accessible and/or just keen to network with other like-minded people looking to make a difference to users with different abilities?

We will predominantly be covering digital topics to gain as much insight into the technology that is assisting people every day. This will include hints and tips on website accessibility from organisers, HeX Productions. 

On the 12/10/2018 from 6PM-9PM we will be hosting: 

- Opening Remarks (15 mins)
- Act One – Sean Gilroy – BBC Cape (35 mins)
- Entertainment - Luke Shaw – Poet/Writer Spoken Word Artist (Advisory note: Strong language) (10 mins)
- Meet& mingle – Break for food (45 mins)
- Act Two – Speaker tbc (20 mins)
- Lightning Talk – Speaker tbc (15 mins)
- Closing Remarks & Competition Draw (15 mins)

Follow @a11yNottingham for more info.

**Comment by ericwbailey** [comment]
@hexproductionsben Do you have a URL for the event? I'll use your Twitter if not.

**Comment by ericwbailey** [comment]
Thanks, Ben! All set: https://github.com/a11yproject/a11yproject.com/pull/671.
