### ISSUE TITLE
Create Issue Templates

### ISSUE THREAD

**Issue by scottaohara** [a11yproject/a11yproject.com#668]
In an effort to request topic ideas from the community, we should create an issue template that would help call out their participation.

Ideas for the new article template:

* Topic idea
* Problems you (the person filing the issue) have faced concerning this topic. 
* Are you posting this as a means to look for help on the topic or do you have a method you've developed/tested to solve the issue/topic?

Additionally, we should create other templates to help guide users to file issues with the website in general, note issues with hosted resources (articles/howtos), and to ensure that all information for event listings are included (e.g. not forgetting date, time, or link to the event).

- [x] Issue to create new article template
- [x] Issue with the a11yproject website template
- [x] Issue with existing article/hosted resource template
- [x] New event listing template

Others?

**Comment by ericwbailey** [comment]
I like this idea. How do you feel about the issue template pointing to sub-templates for these concerns? I'm thinking each sub-template could also point to the relevant section in [`CONTRIBUTING.md`](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md), to help people self-serve.

We do have [an example post](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/_posts/example-post.md) in `_posts/`, but maybe it's worth moving to project root to help discoverability if we're also creating these sub-issues? 

We could revise the Issue labels to help identify and triage, I like using [this kind of setup](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63).

I also think that if we move forward with this we should just start by creating the templates you listed out and add more as they become apparent.

**Comment by ericwbailey** [comment]
Yeah. I don't think GitHub allows you to select from a range of issue templates, but what we could do is provide a list that points to other Markdown documents. So sorta like:

- Link to issue template for writing articles
- Link to issue template for site issues
- Link to issue template for feature requests
- etc.

With each doc having FAQs, pointing to relevant content areas, and the like.

**Comment by nschonni** [comment]
> Yeah. I don't think GitHub allows you to select from a range of issue templates

Yup, you can now https://help.github.com/articles/creating-issue-templates-for-your-repository/

https://help.github.com/articles/using-templates-to-encourage-high-quality-issues-and-pull-requests-in-your-repository/ talks about the various types of templates that are supported

**Comment by ericwbailey** [comment]
@scottaohara: Do you think @alexroseb's recent work closes this issue?

**Comment by scottaohara** [comment]
Yup.  missed closing this when we merged the PR.

closed by #774
