### ISSUE TITLE
Article Audit: NVDA + VoiceOver articles

### ISSUE THREAD

**Issue by scottaohara** [a11yproject/a11yproject.com#674]
In reviewing the NVDA and VoiceOver articles for #669, there are some updates I think would be good to create a level of consistency between the two, as well as to provide a template to follow for future articles for JAWS and mobile screen readers.

The NVDA article (2015) is largely good as is, but adding in additional links to more in-depth usage articles/resources would be good here.

The VoiceOver article (2013) could use a listing of common key commands, like the NVDA article, and also links to more in-depth usage articles/resources.

**Comment by erinoerin** [comment]
@scottaohara Is this Issue open for other people to address?

**Comment by scottaohara** [comment]
sure!  i assigned it to myself as a reminder.  anyone can pick it up though :)

**Comment by bistaastha** [comment]
@scottaohara Hi! Can I work on this?

**Comment by scottaohara** [comment]
Go for it!
