### ISSUE TITLE
Design: Update focus styles

### ISSUE THREAD

**Issue by scottaohara** [a11yproject/a11yproject.com#683]
While we've begun the process of a site redesign for 2019, presently the focus indicators for the A11y Project website are the system defaults and not always the easiest to see.

If someone would like to take a stab at updating the focus styles for the current design, that'd be very much appreciated :)

![the current focus indicator around the CTA link on the home page. Barely noticable.](https://user-images.githubusercontent.com/4152514/48972286-37faa800-eff5-11e8-8a18-3c3011fe0c48.jpg)

**Comment by petetalksweb** [comment]
Is there documentation anywhere about the redesign? Or is it still in process?

**Comment by ericwbailey** [comment]
It's still very much in the "very early in the process" phase 🙂

**Comment by davidluhr** [comment]
I'd love to help out with this! Happy to put together a PR for the current website, as well as the redesigned site (if the color palette is changing).

I've always really admired the focus styles found in IBM's Carbon Design System buttons: https://www.carbondesignsystem.com/components/button/code

I'd recommend setting an explicit focus indicator with an `outline` that matches the color of the button/link, which ensures that WCAG 2.0 AA contrast requirements are met (3:1 for focus indicators). With some very minor animation (via `transition` on specific properties), it can give the impression that focus is animating between elements as users tab around the UI, which provides very helpful context.

Let me know how I can help!

**Comment by scottaohara** [comment]
Hey @davidluhr 

If you got something in mind you want to try out for the current site, go ahead and create a PR for us to review.  

Thanks

**Comment by davidluhr** [comment]
@scottaohara I have changes ready to open a PR for feedback, but it appears I do not have permissions to push to the repo. I didn't find instructions regarding permissions in `CONTRIBUTING.md`; is there something I need to do on my end? Thank you!

**Comment by KempfCreative** [comment]
@davidluhr generally you want to fork the project, then issue a PR from your fork to this repo.

See more detailed instructions here: [https://help.github.com/articles/fork-a-repo/](https://help.github.com/articles/fork-a-repo/) and this [SO answer](https://stackoverflow.com/a/4384824)

**Comment by scottaohara** [comment]
Thanks for responding @KempfCreative.  

@davidluhr let us know if you have any other questions.  Looking forward to the PR.

**Comment by davidluhr** [comment]
@scottaohara I have a PR open now for feedback. Let me know if there is anything else I can provide.

Sorry for the extra PR (688) that I closed. I had an odd situation where my feature branch wasn't detecting a diff with `gh-pages`, even though the code was different, thereby preventing me from rebasing/updating as needed. I fixed up the branch and now everything looks good in 689.
