### ISSUE TITLE
How to Hide Content

### ISSUE THREAD

**Issue by jnurthen** [a11yproject/a11yproject.com#69]
The off-screen text technique to hide text visually and still have the text available to screen readers, while still occasionally useful, has been superseded by aria-label in most cases. Rather than encouraging more use of a hack it would be better to point people to more modern techniques.

**Comment by svinkle** [comment]
This issue has become "[stale](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#stale-issues)" — @jnurthen, feel free to open a [new issue](https://github.com/a11yproject/a11yproject.com/issues/new) if you'd like to continue.
