### ISSUE TITLE
Accessibility and Compliance: How to measure digital accessibility

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#691]
Join part two of our live webinar series on accessibility and compliance.

[Join us on December 11th, 1:00-2:00PM EST 
](https://accessibility.deque.com/accessibility-and-compliance-how-to-measure-digital-accessibility)
**Glenda Sims**, Director of Consulting at Deque Systems, will discuss how organizations can measure accessibility via the Web Content Accessibility Guidelines (WCAG) 2.0 A & AA in order to stay compliant and accessible.

In this webinar you will learn about the :

- The structure of WCAG 2.0 and its principles
- Examples of success criterion in the regulation
- Easy first steps towards becoming accessible
- Why interpretation differences exist as experts interpret the standard

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/129643fb993338f18c8c080db0f775ae85bea1a3.
