### ISSUE TITLE
Different names for further reading section in different posts

### ISSUE THREAD

**Issue by petetalksweb** [a11yproject/a11yproject.com#697]
A lot of posts on the site have some kind of "Further reading" section... but they aren't all called that. I've seen:
- [Further reading](https://a11yproject.com/posts/myth-screen-readers-dont-use-javascript/#further-reading)
- [Additional reading](https://a11yproject.com/posts/understanding-vestibular-disorders/#additional-reading)
- [Additional references](https://a11yproject.com/posts/aria-landmark-roles/#additional-references)
- [More resources](https://a11yproject.com/posts/alt-text/#more-resources-for-writing-alt-text)

Should there instead be a ```further-reading``` property in a post's front matter where authors can list the links they want, and then have them printed out by post.html to standardize these sections?

**Comment by scottaohara** [comment]
Please!  I think this is a great idea.  

I'm good with "Further reading" as the heading to the listing of links.  The only con I see to that is if someone wants to link to a GitHub page or something that isn't really an article / more information.

Also, I really want to make sure the site is consistent with how the further reading links are marked up.  For instance...
Title of resource (link). Date published (text). Source Name (text).

**Comment by petetalksweb** [comment]
> The only con I see to that is if someone wants to link to a GitHub page or something that isn't really an article / more information.
 and those definitely 

There are a couple of articles that have something like an "Available tools" section or something similar, that link to GitHub projects/examples/etc. and those can/should definitely still stay in custom lists to give a reader more context. 

I'm just talking about the large number of posts that exclusively provide links to other articles.

> I really want to make sure the site is consistent with how the further reading links are marked up. For instance...
Title of resource (link). Date published (text). Source Name (text).

I think: title_of_resource (link) by soure_name on date_published might be more appropriate. Thoughts? But there should definitely be a consistent mark up for them.

I can work on a PR for this, and add a ```further-reading``` section to the example-post.md file, specifying this format... and then I'll probably mention that the example-post.md exists in the "Submitting Content" section of the CONTRIBUTING.md

I would also go back and modify old posts to use this pattern to try and make it stick.

**Comment by scottaohara** [comment]
Yeh, I see your point about the ordering of the information.  Personally, I am more concerned with publish date than source. Since reputable sources can host stale content, I'd want that date out front.  But I'm not going to argue further than this on that subject.

Otherwise, I think the rest of this makes sense and would definitely help in the consistency / clean up efforts.

@ericwbailey thoughts?

**Comment by ericwbailey** [comment]
This is great, thank you @petetalksweb! And +1 to using "Further reading".

Personally, I prefer the `title as a link` by `source name` on `date published` pattern. My thinking is info on an authoritative source will probably still be relevant, so it'd take priority.

But to both of your points, I think consistency is key, whatever form it ultimately takes.

**Comment by petetalksweb** [comment]
Cool!

I'll work on a PR for this. Probably have it done sometime later this week.
