### ISSUE TITLE
Subscribe link is not working

### ISSUE THREAD

**Issue by Sidhe-is-me** [a11yproject/a11yproject.com#703]
Please review our Contributing guidelines:
https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#reporting-issues

## Summary
>Subscribe link at bottom of page is not working as expected.
> 
> Example:
> 1. Click Subscribe. https://a11yproject.com/atom.xml
> 2. An HTML page loads- see attached image
> .

### Expected result
>  Expected to be directed to a subscription page.

### Actual result
> Explain what actually happened.
> HTML page loaded- see attached

### Additional Information
> To help us try and reproduce the issue, please provide the following information:
> 1. What device were you using?  Dell Laptop Chrome browser 
> 2. Operating System version.
> 3. Browser(s) and version(s). Chrome Version 70.0.3538.110 (Official Build) (64-bit)
> 4. Assistive technology used (if applicable) None

### Additional Information
Note anything else you think would be important to know that didn't fall into an above category.
<img width="1022" alt="subscribe link" src="https://user-images.githubusercontent.com/13264422/49670643-53bd6f80-fa33-11e8-8376-90f26eb72153.PNG">

**Comment by scottaohara** [comment]
Thanks @Sidhe-is-me 

Additional notes:
Firefox on macOS loads a screen with a subscribe button at the top.  Safari 12 produced a screen like the one in the provided screen shot.

**Comment by alexroseb** [comment]
I can look into this!

**Comment by alexroseb** [comment]
The easiest way to do this is to create a FeedBurner since some browsers (like Chrome) don't display RSS feeds correctly unless you have a plugin installed. 
I created one with the URL http://feeds.feedburner.com/A11yProject and will replace the "Subscribe" link with the new one.

**Comment by alexroseb** [comment]
OK, so there really aren't any good sites on our end to display the feed in a better way - it's mostly dependent on the user having a reader plugin of some kind installed or them copying the link into an external reader.
I'd suggest either changing the text to "RSS Feed" and/or adding a short statement explaining that the URL is just the feed, not a prettified view. @scottaohara, thoughts? @Sidhe-is-me do you think this would help make it clearer?

**Comment by Sidhe-is-me** [comment]
I would consider changing the wordage to rss feed from subscribe. I think
that would make it more clear.

**Comment by scottaohara** [comment]
Yup, i'm good with that solution.

**Comment by alexroseb** [comment]
Fantastic, I’ll open a branch and PR.
