### ISSUE TITLE
Change "Who to follow" page to Twitter lists

### ISSUE THREAD

**Issue by petetalksweb** [a11yproject/a11yproject.com#707]
The "Who to follow" page seems a little unruly. I think it might be better to change it to a [Twitter list](https://help.twitter.com/en/using-twitter/twitter-lists) maintained by the [A11y Project Twitter account](https://twitter.com/A11YProject) or separate Twitter lists for people, companies, and Meetups.

This would have the added benefit of allowing users to follow/unfollow the whole list at once, rather than going through and doing it piecemeal.

**Comment by scottaohara** [comment]
I don't disagree with this.  

For context, the list was largely a port of [Joe Watkin's top people to follow in web accessibility](https://github.com/joe-watkins/top-people-to-follow-in-web-accessibility).

That list has also continued to receive updates that haven't flowed through to here.

I think we should noodle on this some more, as I agree with you that there's probably a more efficient way to at least organize this information, if not make it less of a manual process to update.

**Comment by petetalksweb** [comment]
If the list is mostly a port of this other repo, should we just link to it?

Have the page just be 3 sections:
- Follow the official A11y Project twitter, and link to the RSS feed for the site
- List out the author info from authors.yml to encourage readers to follow them on the link they provide in authors.yml
- Say something like "for more great content checkout..." and link to the Joe Watkin's repo

**Comment by scottaohara** [comment]
I think this makes sense / like the proposal, but want others to weigh in on the idea.

**Comment by ericwbailey** [comment]
Yeah, this sounds like a more pragmatic solution. To me, the cons to this approach would be hiding the larger community behind a link we hope people click, but listing the authors might help with that. 

Another thing I've been discussing for the [upcoming redesign](https://github.com/a11yproject/a11yproject.com/milestone/4) is a way to put a more human face on the project. I'd love to have a monthly/bi-monthly showcase of someone doing good work in the field as a way to promote their efforts.

**Comment by ericwbailey** [comment]
I have initial work here that captures what we've been discussing: https://github.com/a11yproject/a11yproject.com/blob/2019-redesign/eleventy/follow/index.njk

The design and content aren't finalized, but I figured I'd update this thread with progress for those who are interested.

**Comment by ericwbailey** [comment]
We should also make sure that we submit a PR to Joe's list that includes anyone we have that he dosen't. @alexroseb, could I tap you to review them when you have a moment?

**Comment by alexroseb** [comment]
@ericwbailey will do! I’m on vacation now but will be able to get back online in the new year.

**Comment by ericwbailey** [comment]
Totally, thank you! Enjoy your time off :)

**Comment by alexroseb** [comment]
Done! https://github.com/joe-watkins/top-people-to-follow-in-web-accessibility/pull/41

**Comment by ericwbailey** [comment]
Awesome! Thanks!

**Comment by ericwbailey** [comment]
So, it's been a bit, and the PR has yet to be merged. 

So here's a question: should we create that Twitter list on our A11Y Project Twitter account and use Joe's as a starting point? We can credit him on the site as the list's originator.

**Comment by ericwbailey** [comment]
We have deprecated who to follow. There's an orphan page to not break existing links that links to Joe's list.

**Comment by darekkay** [comment]
Unfortunately, Joe's list isn't updated anymore. The PR from Alex [linked above](https://github.com/a11yproject/a11yproject.com/issues/707#issuecomment-452009099) has been open for almost 2 years now. I've been contributing to [awesome-a11y](https://github.com/brunopulis/awesome-a11y) and there you can find [an updated list of people to follow](https://github.com/brunopulis/awesome-a11y/blob/master/topics/people.md).

Do you think changing the link to a more recent list (whether `awesome-a11y` or something different) or coming back to hosting the list on the a11y project would be a good thing? I can open a new issue (and also take it up) if this change is welcome.

**Comment by ericwbailey** [comment]
@darekkay I'd be happy pointing towards a more actively maintained resource. If you want to create and issue and tackle the PR I'd be more than happy to merge it.
