### ISSUE TITLE
Article Audit: How-to: Hide content

### ISSUE THREAD

**Issue by scottaohara** [a11yproject/a11yproject.com#712]
The how to hide content article could use some minor updates to the prose, and link to additional resources that have extended information on this subject matter.

**Comment by RyanAaronGreen** [comment]
@scottaohara - I'll take this one on if no one else is already working through it

**Comment by scottaohara** [comment]
go for it @RyanAaronGreen 

i wrote a bit about this stuff as well if you want to reference:
https://www.scottohara.me/blog/2017/04/14/inclusively-hidden.html
https://www.scottohara.me/blog/2018/05/05/hidden-vs-none.html

webaim could be one of the further reading links:
https://webaim.org/techniques/css/invisiblecontent/

thank you

**Comment by alexroseb** [comment]
@RyanAaronGreen, are you still working on this?

**Comment by RyanAaronGreen** [comment]
@alexroseb - unfortunately, shortly after I started I ended up putting it on the backburner and I  haven’t been actively working on it. But I’m still interested!

Is this something that you’re interested in writing?

**Comment by alexroseb** [comment]
@RyanAaronGreen, no worries! Just going through and checking the status of old issues. Shall I assign it to you or open it up to others?

**Comment by scottaohara** [comment]
Closed by [this update](https://github.com/a11yproject/a11yproject.com/commit/f2b7649e2ec28e6a5ac9c0efc960363ca635fb0c)
