### ISSUE TITLE
Using caption services with HTML5 video

### ISSUE THREAD

**Issue by alexroseb** [a11yproject/a11yproject.com#716]
Reviewed for #669.
We should add some further resources and update the content a bit.

**Comment by michaelspellacy** [comment]
In addition to new resources, I would love to see some guidance on implementing audio descriptions.

**Comment by alexroseb** [comment]
@michaelspellacy That sounds like a great idea but I don't think it would fit with this one - you should absolutely create an issue for someone to add a new article!
