### ISSUE TITLE
Add new utility/info pages

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#717]
I think we should add a few new pages to the site for the redesign.

Inspired by [It’s Beginning to Look a Lot Like XSSmas](https://24ways.org/2018/its-beginning-to-look-a-lot-like-xssmas/)/[snyk's `SECURITY.md`](https://github.com/snyk/snyk/blob/master/SECURITY.md). We're a static site, but I still think proactively it'd be a good thing to have. 

Checklist of desired pages:

- [x] An [accessibility statement](https://www.w3.org/WAI/planning/statements/)
- [x] A security and privacy statement
- [x] A [D&I timeline](https://zapier.com/jobs/working-on-diversity-and-inclusivity/)
- [x] A "write for us" page, including linking to the writing styleguide
- [x] A team page

**Comment by webuxr** [comment]
@ericwbailey I know things with the redesign are likely still in flux but I’m curious... are these loosely defined tasks more about seeking content creation (i.e.: copywriting, imagery, iconography, and/or art direction) ...or... more towards the brainstorming and ideation phase (if you will) and are seeking help with wireframes, rough page layout concepts, and/or even code-level page build-out?

While I’m not much of a copywriter, I could be put to work on just about any of the other things I’ve mentioned.

Thoughts?

**Comment by ericwbailey** [comment]
Tagging @tatianamac, as this is relevant to her work.

We have overall aesthetics/art direction pinned down from Tatiana's work, but iconography is still a bit in flux as she continues to work. Layout is mostly reflective of the current site, a single main column of text with an accompanying sidebar or subdivision of content when it's capable of being supported.

For secondary-level pages, we've settled on the following structure:

## Site

- History
- Values
- Team
- Authors

## Utility

- Code of Conduct
- Accessibility Statement
- Content Style Guide
- Privacy and Security

## Copyright

- Copyright
- Sponsorships and Support

For those pages, we're trying to map existing content and merge where it makes sense. For example, [Purpose and Team](https://a11yproject.com/purpose/) will likely get split into Values and Team, respectively. Another example would be taking the current [Content Style Guide](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTENT_STYLE_GUIDE.md) and moving it out of GitHub, as GH itself can be a barrier or disorienting context shift.

Ironically, one thing we could really use help with is copywriting (😅). The following pages don't have content, and if you'd like to take a crack at writing some content that would be very much appreciated: 

- History
- Accessibility Statement(!)
- Privacy and Security
- Sponsorships and Support

We're going to have a "generic" template for these kinds of pages—it'll probably borrow heavily from the blog post template. However, if you think there are specific content needs within these pages, rough wireframes or other ideation would definitely be welcome!

**Comment by ericwbailey** [comment]
Somewhat unrelated to this issue's topic, but for code-level, we could also use help improving the gulp setup. I have a barebones runner right now, but I'd love it if we could get more mature features like better error handling.

**Comment by SebacicA11y** [comment]
I'm a better editor than writer, and some of these topics I would have no
idea what the content is. If we can open a Google doc for each page to
throw ideas into, I'll happily ask questions, ask for verification,
re-write etc so that I can understand it. Then I'll write it again so
anyone can understand it.

**Comment by jeryj** [comment]
@ericwbailey, what kind of error handling did you have in mind? I might be able to help with that.

**Comment by ericwbailey** [comment]
@jeryj Ooh, yes! We have a coversation going on here for a 404: https://github.com/a11yproject/a11yproject.com/issues/808

**Comment by tatianamac** [comment]
Happy for the help anywhere! Frankly right now I'm not to the space where I feel like we can dole out GitHub-issue-level tasks quite yet. Once I get the infrastructure for a couple more pages and their child components, there will be work to do that I can more easily assign out.

**Comment by ericwbailey** [comment]
Closing this issue as each page has been captured and will be published with the redesign's launch. 

The goal of this issue was to facilitate the creation of these pages. Now that they're made, I consider this issue resolved. I figure we can have more targeted and effective per-page conversations on a per-issue/PR-basis, should the need arise.
