### ISSUE TITLE
role=drinks San Diego Accessibility Kickoff!

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#723]
`[Join us for our role=drinks San Diego kickoff event](https://www.meetup.com/role-drinks-SD/events/257721676/)`! Whether you're an accessibility guru or are just curious about what exactly web accessibility and inclusive design are, this meetup is for you. This group is for designers, developers, project managers, execs... really anyone involved in building web products. Let's get together, network, collaborate and learn from one another!

Mission Brewery is dog friendly. They don't serve food but outside food is welcomed - we'll bring some pizza. $5 draft pints on Tuesdays, soft drinks available. The space is accessible.

This kickoff event will be a networking happy hour mixer. Future events will also feature accessibility-related lightning talks. Come help us advance web accessibility and inclusiveness in San Diego!

Learn more about role=drinks at https://www.roledrinks.com

Code of Conduct at https://www.roledrinks.com/code-of-conduct.html

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/774929c6f3864acc9bd1d19316d538c93a590532. Thank you!

**Comment by ljgoslin** [comment]
This is showing up under 2018 instead of 2019 on the events page.

**Comment by ericwbailey** [comment]
Sorry about that, it should be fixed now. If it helps, I've already written 2 checks dated 2018 this year, and it's only January.
