### ISSUE TITLE
Mobile Office Hours: Deque mobile updates with dedicated time for Q&A

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#726]
[Join our live, open office hours](https://accessibility.deque.com/mobile-office-hours-webinar) on February 12th from 1:00-2:00PM EST to stay up-to-date on all things Deque mobile (iOS & Android) and  come prepared with your outstanding mobile accessibility questions!

This session will be hosted by our mobile expert, **Chris McMeeking**. Chris has 5+ years of mobile application development experience and has worked with the Android Open Source Project. Currently, he is the Senior Software Engineer at Deque Systems, architect of Deque's Native Accessibility analysis solutions. Lastly, Chris is an active member of the W3C (World Wide Web Consortium) mobile working group that is defining international standards for accessibility.

In this office hour, there will be:
- Announcements and short discussion about current development efforts at Deque.
- A discussion about recent changes in the Android/iOS Platforms and how they impact Mobile Development teams.
- 30 minutes dedicated to have your outstanding mobile accessibility questions answered with one of the leading experts in the mobile accessibility field, come prepared!

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/9dc0721d7ce1b6373655e3381ff08d341569b79a.
