### ISSUE TITLE
Event: Nurturing a Neurodiverse Workplace

### ISSUE THREAD

**Issue by deconspray** [a11yproject/a11yproject.com#727]
Wednesday, January 23, 2019
6:30 PM to 7:30 PM
Nurturing a Neurodiverse Workplace
https://www.meetup.com/a11ychi/events/257913463/
Live stream: https://www.youtube.com/watch?v=BQMMDNLYTgk
Live captions: http://www.streamtext.net/player?event=CDA

Join us for a talk about growing a neurodiverse work team! Amy Johnson will share her experiences in using her self-awareness as a tool in her work and approaching design from a different direction. She'll cover topics including:

- The benefits of hiring those with atypical brains.
- How to best collaborate with individuals who have ADD, ADHD, Autism, and more.
- How to make your work environment healthier and more flexible for all, both neurotypical and atypical.

**Comment by ericwbailey** [comment]
Thanks for the submission, Dennis!

Closed via https://github.com/a11yproject/a11yproject.com/commit/d56a6c424e00623287b2ec4fde995bf872bc1b91.
