### ISSUE TITLE
Cleveland Accessibility January Meetup Digital Accessibility 101

### ISSUE THREAD

**Issue by mbozz** [a11yproject/a11yproject.com#728]
[Digital Accessibility 101 - The Basics](https://www.meetup.com/Cleveland-Accessibility-Meetup/events/257287270/)
Digital accessibility means that your website, mobile app, or electronic documents like PDF files can be navigated and understood by all users, including those with visual, auditory, motor, or cognitive disabilities. This presentation will cover the fundamentals of inclusive design and digital accessibility
https://www.meetup.com/Cleveland-Accessibility-Meetup/events/257287270/

**Comment by ericwbailey** [comment]
Thanks! Closed via https://github.com/a11yproject/a11yproject.com/commit/6ba663cdc2973344efb337b900b08423de463e7f and https://github.com/a11yproject/a11yproject.com/commit/3b0a2ada2090c6009faa13a2774a60bb70c5cebc.
