### ISSUE TITLE
Cleveland Accessibility February Meetup - Local Accessibility Projects and Assistive Technologies

### ISSUE THREAD

**Issue by mbozz** [a11yproject/a11yproject.com#729]
[Local Accessibility Projects and Assistive Technologies](https://www.meetup.com/Cleveland-Accessibility-Meetup/events/258068572/)
Local accessibility experts discuss successful accessibility projects and introduce you to assistive technologies for people with vision loss. 
https://www.meetup.com/Cleveland-Accessibility-Meetup/events/258068572/
#A11yCLE

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/6ba663cdc2973344efb337b900b08423de463e7f and https://github.com/a11yproject/a11yproject.com/commit/3b0a2ada2090c6009faa13a2774a60bb70c5cebc.
