### ISSUE TITLE
4th Annual Axe-Hackathon

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#730]
[Join our in-person hackathon](https://www.eventbrite.com/e/axe-hackathon-2019-tickets-54988465982) that is post-CSUN at the Anaheim Marriott on Saturday, March 16th from 10:00AM-3:00PM PST.

Contribute to making the web accessible to people with disabilities at the 4th Annual axe-Hackathon on March 16th, 2019. The Hackathon will be led by [Wilco Fiers](https://twitter.com/wilcofiers) and other members of the axe team. We will be...

- Testing open source component libraries and logging accessibility issues
- Building new axe integrations
- Sharing knowledge and solutions with our fellow accessibility devotees
- Working on personal accessibility projects
- Hanging out with awesome people and making the web a better place

**Who should come?**
You should come. And bring your friends. This hackathon is open to all experience levels. [If you can download a browser extension](https://www.deque.com/axe), you can test for accessibility. We'll also have some advanced project opportunities for our more seasoned a11y friends.

**Will there be food?**
Yes! We will provide lunch and a coffee break. We'll email everyone for dietary restrictions closer to the event.

**Will there be accessibility accommodations?**
We will provide captioning for the opening and closing of the hackathon. The event will mostly consist of people working independently and in small groups on various projects, so it won't be possible to caption absolutely everything said at the event. If you need ASL interpretation or other forms of accommodation, please send an email to [marketing@deque.com](mailto:marketing@deque.com).

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/6ba663cdc2973344efb337b900b08423de463e7f and https://github.com/a11yproject/a11yproject.com/commit/3b0a2ada2090c6009faa13a2774a60bb70c5cebc.
