### ISSUE TITLE
Conference & Demo: Business Built on Inclusive Design

### ISSUE THREAD

**Issue by accesstosuccess** [a11yproject/a11yproject.com#731]
Join us on Feb 5th, 2019 in Toronto as we deep dive into how businesses, large and small, are being commercially successful using the concept of Inclusive Design. Inclusive design encourages designing for the 'excluded user' and thereby extending a product or service to many more. The event will feature 4 short talks, a hands-on demo and a case competition for MBA students. Learn more and register at accesstosuccess.ca! For a peak into who is going to be there, take a look at the attached document!
[Access to Success conference.pdf](https://github.com/a11yproject/a11yproject.com/files/2781191/Access.to.Success.conference.pdf)

**Comment by ericwbailey** [comment]
Thanks for submitting an event. For regional events, [we require a location](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#events). I was unable to locate one on [your website](http://accesstosuccess.ca/), would you mind providing us an address to list?

**Comment by accesstosuccess** [comment]
The event is at the Rotman School of Management, University of Toronto. 
105 St George St
Toronto, ON
M5S 3E6

**Comment by ericwbailey** [comment]
Thank you! Closed via https://github.com/a11yproject/a11yproject.com/commit/d55de2f2cb0f887816d5b055616840a650ef6b45
