### ISSUE TITLE
Move off of Google Analytics

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#737]
I think there's value in discussing migrating away from Google to use a service that is more privacy conscious. I've been looking at [Simple Analytics](https://simpleanalytics.io/) as an alternative, especially now that we have a budget for it.

**Comment by robinmetral** [comment]
I can also recommend a self-hosted [Matomo](https://matomo.org/) instance, if you want to fully own analytics data (Simple Analytics is privacy-friendly, but it still collects some)

**Comment by Toyrone** [comment]
Hi! I realize this might not be the right place to say this. But I’m quite interested in contributing here, just not sure where my input would be needed. Thanks ☺️

**Comment by robinmetral** [comment]
One more option to consider is [Fathom](https://usefathom.com/).

Contributor @davatron5000 wrote about it in his blog: https://daverupert.com/2019/04/goodbye-google-analytics-hello-fathom/ :slightly_smiling_face:

**Comment by ericwbailey** [comment]
[GoatCounter](https://www.goatcounter.com/) also looks promising.

**Comment by ericwbailey** [comment]
[Plausible](https://plausible.io/), as well

**Comment by ericwbailey** [comment]
I have enabled [Netlify Analytics](https://www.netlify.com/products/analytics/), as we're already using them for deployment. Working on a PR to update the site now.
