### ISSUE TITLE
Make sure redirects work

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#738]
We want to ensure our content is still capable of being read if our URLs change with the redesign. This is to preserve links that exist on other sites.

**Comment by ctrimm** [comment]
Since #793 was closed out, this could probably be closed out as well.

**Comment by ericwbailey** [comment]
We're going to keep this open as a reminder. We're using a different a different site generator, so we'll need to update our redirect logic.

**Comment by ericwbailey** [comment]
Reports of broken links have died down for the most part. Closing in favor of individual redirect Issues.
