### ISSUE TITLE
World IA Day 2019 - Kent, OH

### ISSUE THREAD

**Issue by mbozz** [a11yproject/a11yproject.com#739]
Get your tickets now for **[World IA Day in Kent, Ohio](https://www.eventbrite.com/e/world-ia-day-2019-kent-oh-tickets-54812055333)**. Saturday, February 23rd, this full-day event features amazing speakers from Northeast Ohio's top companies and surrounding states. Inclusive Design and A11y topics are on the agenda. Tickets are free for this event. **[Reserve your spot now](https://www.eventbrite.com/e/world-ia-day-2019-kent-oh-tickets-54812055333)**.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/88817711acd69315c605708fdb17c34d206cc72d. Thank you!
