### ISSUE TITLE
How Accessibility Testing Actually Impacts Developers

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#740]
February, 26th from 1:00-1:30PM EST

[Join our live webinar](https://accessibility.deque.com/how-accessibility-testing-actually-impacts-developers) to learn about the scope of accessibility and its potential impact on your day to day job as a developer.

Developers are often told to make their websites accessible like it is an easy light switch you turn on or off. Accessibility is necessary to make the web a better place, but it can be a challenging topic if you’ve recently been tasked with it.

Whether you’ve recently been tasked with accessibility or you’re curious about ways you can save time with automated accessibility testing, it’s very important to understand the scope of accessibility and its potential impact before implementing accessibility best practices into your code.

In this webinar, Noah Mashni, Deque’s Solution Architect, will:

- Show you why accessibility is important and how implementing it into your dev practices makes you a better developer
- Discuss what accessibility testing entails and its potential impact your development process
- Run deep dive demos into various types of accessibility testing such as automating accessibility into your existing framework (Mocha, Jasmine, Karma, Protractor, etc.) for end to end and/or unit testing, user flow testing using natural language scripts, or via a simple browser extension.

**Comment by ericwbailey** [comment]
Thanks! Closed via https://github.com/a11yproject/a11yproject.com/commit/547b5bc90504ff2a38688561126955907ffe27c9.
