### ISSUE TITLE
Article: Quick tip: Creating valid and accessible links

### ISSUE THREAD

**Issue by emmasax** [a11yproject/a11yproject.com#741]
Been wanting to write an article about links for a long time. They are seemingly so simple but are just as simple to mess up for accessibility.

**Comment by emmasax** [comment]
I don't seem to have access rights to push my branch. `ERROR: Permission to a11yproject/a11yproject.com.git denied to emmasax.` 😢

**Comment by scottaohara** [comment]
closed via #742
