### ISSUE TITLE
How to convince your boss to care about accessibility

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#743]
March, 7th from 1:00-1:30PM EST

[Join our live webinar](https://accessibility.deque.com/how-to-convince-boss-care-about-accessibility) to learn about best practices and real-life examples of how to convince your boss to care and prioritize accessibility at your organization.

Before accessibility is prioritized at an organization, there is oftentimes a lone developer or small group that cares about creating websites or applications that are accessible for all users. However, advocating for accessibility without having funding can be a frustrating battle.

In this live webinar, **Travis Marasca**, will help make the case for accessibility by:
- Discussing his previous experience of how his team convinced leadership to start doing something about accessibility
- How to deal with concerns around budget and level-of-effort
- How to identify allies within your organization that can help your cause
- Treating accessibility as code quality or like other requirements such as Security, SEO, Performance)

**Comment by ericwbailey** [comment]
Thanks! Closed via https://github.com/a11yproject/a11yproject.com/commit/051a318246e8e52f18e3fcd07866f32c3423475e.
