### ISSUE TITLE
maximum-scale advice is not entirely true

### ISSUE THREAD

**Issue by tmcw** [a11yproject/a11yproject.com#745]
## Summary

On a device with iOS >= 10

- Focus the input on this page, which includes maximum-scale=1 https://max-scale-test-2lgyfhbw3.now.sh/
- Focus the input on this page, which does not https://max-scale-test-2lgyfhbw3.now.sh/index-no.html

### Expected result

Reading the page about [maximum-scale](https://a11yproject.com/posts/never-use-maximum-scale/), I'd expect that maximum-scale does not have effect, so the pages should behave the same.

### Actual result

maximum-scale does have an effect: it prevents the page from zooming into the focused input. The [Apple post](https://webkit.org/blog/7367/new-interaction-behaviors-in-ios-10/) referenced in the a11yproject article is vague about what actually changed, but I suspect that what they're saying that "maximum scale does not forbid user zooming" rather than "maximum scale has no effect". maximum-scale does have at least one effect - it changes the behavior of Safari when an input is zoomed.

### Additional Information

This demo works on my iPhone XR, as well as all the devices in Simulator.app that I tested.

### Additional Information

Unfortunately I can't see any way to both preserve the behavior of not zooming on focusing - which, for our application, is an impediment to the user experience and unnecessary because we're using large font sizes - and also abide by this accessibility rule, which - as far as I can tell, is a little oversold. Via both the a11yproject page and Apple's site, I expected maximum-scale to be actually ignored, and it isn't.

**Comment by ericwbailey** [comment]
Thanks for this, @tmcw. If you'd like to submit a PR to the article to clarify, we'd be happy to incorporate your findings. Have you tested with other mobile browsers such as Android?

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/751. Thank you, @tmcw!
