### ISSUE TITLE
Cleveland Accessibility March Get-Together... and Book Club!

### ISSUE THREAD

**Issue by mbozz** [a11yproject/a11yproject.com#746]
**[Cleveland Accessibility March 21, 2019 Meetup](https://www.meetup.com/Cleveland-Accessibility-Meetup/events/259335332/)** will be a social/networking gathering to discuss the Book "A Web for Everyone" by Sarah Horton & Whitney Quesenbery. 

This book gives practical advice and examples of how to create sites that everyone can use, and uses individual personas to focus attention on the essential idea that accessibility begins and ends with people.

We'll be meeting at the Market Garden Brewery in Cleveland, Ohio. Join us! Details and Registration here: 
https://www.meetup.com/Cleveland-Accessibility-Meetup/events/259335332/

**Comment by ericwbailey** [comment]
Thanks! Closed via https://github.com/a11yproject/a11yproject.com/commit/df3d13b4c2f49f6c33f977348a2bc40ea29ff7a3.
