### ISSUE TITLE
Adding Equidox to resources

### ISSUE THREAD

**Issue by erhinehalt** [a11yproject/a11yproject.com#749]
Equidox is a big supporter of the a11y movement. I propose adding Equidox under the resources tab in the professional help category as well as a link to PDF remediation tools in the PDFs category. Here are the links, respectively:

https://equidox.co/
https://equidox.co/equidox-briefs/

**Comment by ericwbailey** [comment]
Thank you for the submission of https://github.com/a11yproject/a11yproject.com/pull/748. Unfortunately, as noted in the [contributing guidelines](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#submitting-content), we try not to feature content that has a high cost of entry. 

If you have public resources such as blog posts that feature advice, we'd love to add that instead.

**Comment by erhinehalt** [comment]
would I be able to list the PDF remediation tools and not the professional services? or vice versa? I'm just curious which part is of concern here as Equidox has lower-cost options than the resources that are already listed and the PDF remediation tools I posted are free and informative

**Comment by dennisgaebel** [comment]
Hi @erhinehalt. Thanks for filing this issue as I suggested when you first sent me your e-mail request. 

In response to your comment:

> I'm just curious which part is of concern here as Equidox has lower-cost options than the resources that are already listed and the PDF remediation tools I posted are free and informative

This is the mention in the [guidelines](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#submitting-content) that Eric is referencing…

> As we are an Open Source project, The A11Y Project tries to only promote content that is **free**, or has a low barrier to entry. We're not too keen on partnership deals or promotions.

Forgive me if I'm missing something, but I don't see anything that lets someone execute these PDF tasks without sending a direct message through your contact form. Please correct me if I'm wrong.

That said, I think it would be best to have @ericwbailey and the rest of the team review [your blog](https://equidox.co/equidox-accessibility-blog/) before adding it. We appreciate your interest, and support of this project so please be patient while we take things under consideration as we don't want to support content nor promote it without giving it a review. Thanks again for your interest and support the A11Y project.

~Cheers 🍻

**Comment by erhinehalt** [comment]
I totally understand that it's not an instantaneous process and my apologies for submitting a pull request before this issue. I'm still pretty new to github etiquette at this point, go easy on me! The blog is informative and getting better and better content as it progresses if I do say so myself. I suppose the website does not reflect that Equidox has developed a brand new tool, that we are using to analyze web directories for free upon contact to help organizations understand where they stand and how to gameplan to bring their resources to compliance. It's a site crawler of sorts that gives a report regarding the content and accessibility of all PDFs in any given directory. Anyways, I can come back with another issue about that once we have a link to a page for that specifically. I hope the blog is up to par, let me know!

**Comment by dennisgaebel** [comment]
Hi @erhinehalt we appreciate your interest, but after reviewing your blog with our team we don't feel it is the best fit for our resources page as much of your content is duplicated on other resources we currently have listed. Finally, please feel free to file another issue regarding your PDF tool once you have it available to the public. We wish you luck and appreciate your continued support of the A11Y project ~Cheers
