### ISSUE TITLE
What to expect from an accessibility audit

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#752]
April 9th from 1:00-2:00PM EST

[Join our live webinar](https://accessibility.deque.com/what-to-expect-from-an-accessibility-audit) to learn the scope of an accessibility audit and how it can jumpstart your organization’s accessibility journey.

If your organization is just starting to learn about accessibility, it can be difficult to know where to start. Free automated testing tools, such as axe, or training are a great starting point. However, if you want to be confident that your website or application is accessible, consulting with an accessibility partner for an accessibility audit is essential.

In this webinar, Deque’s experts, Glenda Sims and Tammy Cosseboom, will discuss:

- The timeline of a “typical” accessibility audit
- How audits can vary from one accessibility partner to another
- The content and substance of an accessibility audit

**Comment by ericwbailey** [comment]
Thanks! Closed via https://github.com/a11yproject/a11yproject.com/commit/f07881bf11855b0f939973ae28b50fd58a715ef3.
