### ISSUE TITLE
Mobile Office Hours: Axe for Android Open Source Announcement and Q&A

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#754]
**Monday, March 25th from 1:00-2:00PM EST**

[Join our live webinar](https://accessibility.deque.com/mobile-office-hours-axe-for-android-and-qa) to learn about Deque’s newest announcement: Open sourcing axe for Android!

This session will be hosted by our mobile expert, Chris McMeeking. Chris has 5+ years of mobile application development experience and has worked with the Android Open Source Project.

Currently, he is a Senior Software Engineer at Deque Systems, architect of Deque’s Native Accessibility analysis solutions. Lastly, Chris is an active member of the W3C (World Wide Web Consortium) mobile working group that is defining international standards for accessibility.

In this office hour, there will be:

- More information on the axe for Android tool from Deque and how your development team can leverage this tool.
- 30 minutes dedicated for your outstanding mobile accessibility questions, come prepared!

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/8ac4c233c2b7c1686d08aa4318954995a7f2d7a1. Thank you!
