### ISSUE TITLE
Cleveland Accessibility April Meetup: CSUN Assistive Technology Conference Recap 2019

### ISSUE THREAD

**Issue by mbozz** [a11yproject/a11yproject.com#759]
A11yCLE April 29 Meetup: **[CSUN Assistive Technology Conference Recap 2019](https://www.meetup.com/Cleveland-Accessibility-Meetup/events/260263110/)**

The CSUN Assistive Technology Conference is the largest conference in the world to focus on the field of assistive technology. The conference was held in Anaheim, California, March 11 to March 15, 2019. Over 350 presentations were on the agenda, and more than 500 speakers representing a wealth of expertise on all facets of living with disabilities and using assistive technologies were in attendance. 

**[RSVP for the Meetup](https://www.meetup.com/Cleveland-Accessibility-Meetup/events/260263110/)**: https://www.meetup.com/Cleveland-Accessibility-Meetup/events/260263110/

A **[curated list of available presentations and other resources](https://www.microassist.com/digital-accessibility/csun-2019-assistive-technology-conference-backchannel/)** is maintained by MicroAssist: 
https://www.microassist.com/digital-accessibility/csun-2019-assistive-technology-conference-backchannel/

A11y Cleveland will present 'Lighting Rounds' of selected topics from the CSUN conference. We invite you to review the available, publicly posted speaker presentations and present your own 10 minutes summaries: http://bit.ly/csunatc19

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/27cdeb6269bdf2a095a7f9ec3a1aaba703a6e938. Thank you!
