### ISSUE TITLE
T12t meetup - Global Accessibility Awareness Day

### ISSUE THREAD

**Issue by Kolombiken** [a11yproject/a11yproject.com#760]
## Description
Spotify will host us for our Global Accessibility Awareness Day (GAAD) meetup in their new headquarters in Stockholm. We have a great lineup of speakers – including international keynote [speaker Molly Watt](https://twitter.com/mollywatttalks), flying in from the UK.

## Info and Sign Up
More info [at meetup.com/t12t-stockholm](https://www.meetup.com/t12t-Stockholm/events/260048922/)

## Event type
Public event

## Date and time
Thursday, May 16, 2019
5:30 PM to 9:00 PM

## Physical address of event 
Spotify, Regeringsgatan 19, Stockholm
[Location Google Maps](https://goo.gl/maps/RtFeft3AkH72)

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/27cdeb6269bdf2a095a7f9ec3a1aaba703a6e938. Thank you!
