### ISSUE TITLE
Resources: Accessibility Developer Tools is deprecated

### ISSUE THREAD

**Issue by asciidan** [a11yproject/a11yproject.com#764]
As stated by Google in the extension overview, Accessibility Developer Tools is no longer supported and will become inaccessible in the near future. I suggest we remove it from the resources and instead add Axe Accessibility Testing by Deque (recommended by Google Accessibility).

**Comment by ericwbailey** [comment]
I agree completely. Closed via https://github.com/a11yproject/a11yproject.com/commit/c2178a68b2f3ad26c563aeee68ed5fd0ec467076, thank you very much!
