### ISSUE TITLE
Move off of Google Translate

### ISSUE THREAD

**Issue by robinmetral** [a11yproject/a11yproject.com#768]
#511 and #700 already mention that translations are currently done via a Google Translate widget in the footer.

But if your browser is in another language, it's much more than just the footer:

![google-translate](https://user-images.githubusercontent.com/35560568/56414467-e34d1780-628a-11e9-973a-07cb95477936.png)

This raises a few issues:
 - Google scripts = tracking. In the same idea as #737, it might be good to move off of Google Translate.
 - My browser is in French but I can read in English. I don't need this Translate bar popping up everywhere
 - The Translate bar looks really old and ugly
 - It's really not accessible
 - Google translations of full webpages are really bad (at least in French)
 - If somebody doesn't understand something, they can pop it into Google Translate anyway. We're used to it :slightly_smiling_face: 

:arrow_right: Since we're moving to community translations anyway (see #511 and #700), how about getting rid of the Google Translate widget?

**Comment by ericwbailey** [comment]
No argument here. Could I trouble you for a PR, @robinmetral?

**Comment by robinmetral** [comment]
Will do, you can assign me :slightly_smiling_face:
