### ISSUE TITLE
How to credit article editors

### ISSUE THREAD

**Issue by alexroseb** [a11yproject/a11yproject.com#771]
This may have been addressed somewhere but I can't find it in contributing resources. Is there a standardized way to give credit to article editors? Also, should the publishing date be updated to reflect that the information is more recent/current? My main worry with that would be breaking links.

**Comment by scottaohara** [comment]
original publish date stays the same as does author.

example of updated info that goes into the head of the markdown file:

```
updated_by: editor_name
last_updated: 2019-##-##
```

dunno if this is going to be addressed further as part of the redesign.  but for now, that's how it's been handled.

**Comment by alexroseb** [comment]
Thanks @scottaohara! I added a new section to the contrib guidelines to make this clear to all.
