### ISSUE TITLE
How Accessibility Testing Actually Impacts Quality Assurance (QA)

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#777]
**Tuesday, May 14th from 1:00-1:45PM EST**

[In this live webinar](https://accessibility.deque.com/how-accessibility-testing-actually-impacts-quality-assurance), you'll learn about the scope of accessibility and its potential impact on your day to day job as a QA tester or manager.

QA teams that are tasked with accessibility may be unfamiliar with the topic and unsure where to start. To achieve compliance and test for accessibility requirements, QA testers should understand the scope of accessibility and what tools and methodologies are available.

In this webinar, **Noah Mashni**, Deque’s Solution Architect, will:
- Show you why accessibility is important and QA can have a significant impact when your team tests for accessibility issues.
- Discuss what manual and automated accessibility testing entail and its potential impact your QA testing process.
- Run deep dive demos into various types of accessibility testing such as automating accessibility into your existing framework (Mocha, Jasmine, Karma, Protractor, etc.) for end to end and/or unit testing, user flow testing using natural language scripts, or via a simple browser extension.
- Run a deep dive demo of Deque's WorldSpace Assure, a step by step guided manual testing solution and reporting tool.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/50023f2d7f67279b10ada309634608829e5cf053. Thank you!
