### ISSUE TITLE
Budapest Accessibility Meetup

### ISSUE THREAD

**Issue by szantaikaroly** [a11yproject/a11yproject.com#778]
## Title
>Budapest Accessibility Meetup

### Description
>This is going to be the first event of the Budapest Accessibility Meetup. The language of this meetup is Hungarian.

### URL
>https://www.meetup.com/Budapest-Accessibility-Meetup/events/260887655/

### Date
>2019-05-13

### Type
>Regional

### Address (if Regional)
>Nem Adom Fel Cafe&Bar, 1086 Budapest, Magdolna utca 1., Hungary

### Map (optional)
>https://goo.gl/maps/dyebRCCqezCP1XLy9

### Hashtag (optional)
>#a11ybudapest

**Comment by szantaikaroly** [comment]
Please include our meetup in the list of Meetup groups. Here is the link to the group: https://www.meetup.com/Budapest-Accessibility-Meetup/
Thanks!

**Comment by ericwbailey** [comment]
Thanks! Added via https://github.com/a11yproject/a11yproject.com/pull/781.
