### ISSUE TITLE
Cleveland Accessibility #GAAD May 16, 2019 Meetup

### ISSUE THREAD

**Issue by mbozz** [a11yproject/a11yproject.com#780]
Join us on May 16th as we celebrate Global Accessibility Awareness Day! This is a co-hosted Meetup with **[Cleveland Accessibility](https://www.meetup.com/Cleveland-Accessibility-Meetup/events/260995280/)** and UX Akron. The purpose of #GAAD is to encourage people to talk, think, and learn more about digital accessibility and inclusion.

RSVP: https://www.meetup.com/Cleveland-Accessibility-Meetup/events/260995280/

UX Researchers, UX designers, front-end developers, back-end developers, programmers, and other digital professionals can work to ensure that websites, mobile apps, and other digital experiences (VR, AR) are inclusive and accessible to EVERYONE. 

We'll be discussing general accessibility themes to help you gain a better understanding of accessibility issues:
[] Explanation of digital accessibility and how everyone is impacted by online accessibility.
[] Common approaches and fixes to make websites accessible.
[] Group discussion on barriers to web accessibility, and how to overcome common objections. 
[] How to get started with web accessibility. 

Let's work together to make universal access common practice. Let's work together to bake accessibility right into digital projects so it's part of the recipe, not an afterthought that gets tacked on later. 

Resources for discussion:

Accessibility - the State of the Web
https://www.youtube.com/watch?v=TomOQYxFnrU

An Alphabet of Accessibility Issues - Anne Gibson
https://the-pastry-box-project.net/anne-gibson/2014-July-31

Global Accessibility Awareness Day website: https://globalaccessibilityawarenessday.org/

The venue:
Twinsburg Public Library is accessible, with onsite parking. 

Snacks and beverages will be available. This is a free event.

Agenda: 
6:30 PM to 7:00 PM - Networking, food and drinks.
7:00 PM to 8:00 PM - Presentations and group discussion
8:00 PM to 8:30 PM - Q+A, wrap-up, and more networking!

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/781.
