### ISSUE TITLE
Article: "A primer to vestibular disorders" should mention `prefers-reduced-motion` MQ

### ISSUE THREAD

**Issue by Malvoz** [a11yproject/a11yproject.com#792]
IMO, the section on [What should you consider](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/_posts/2013-05-15-understanding-vestibular-disorders.md#what-should-you-consider) should mention the `prefers-reduced-motion` media-query:

- https://developers.google.com/web/updates/2019/03/prefers-reduced-motion
- https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

I suppose it could be just an addition, however, I don't find the current advice of: only display animations after user-interaction (such as button click) a realistic goal for developers. This media query should (in [browsers that support it](https://caniuse.com/#search=prefers-reduced-motion)) negate the need for such on-site opt-ins.

**Comment by scottaohara** [comment]
Agreed @Malvoz.  Would you like to contribute to updating this piece?  I think that'd be a good addition.
