### ISSUE TITLE
Cleveland Accessibility June Meetup: Digital Accessibility for Business, Developers, and Designers

### ISSUE THREAD

**Issue by mbozz** [a11yproject/a11yproject.com#795]
**June 5th** - **[Digital Accessibility for Business, Developers, and Designers](https://www.meetup.com/Cleveland-Accessibility-Meetup/events/261028665/)**.
Presented by Level Access and hosted by Progressive Insurance and **[Cleveland Accessibility Group](https://www.meetup.com/Cleveland-Accessibility-Meetup/events/261028665/)**. **RSVP:** https://www.meetup.com/Cleveland-Accessibility-Meetup/events/261028665/

Two topics will be presented:

1. **Digital Accessibility for Business**
All kinds of businesses can implement accessibility best practices! Derek Featherstone and Elle Waters of Level Access will discuss and explore reasons and benefits for business owners to incorporate accessibility into their business. While it's easiest to build websites and apps with accessibility features right from the start, retrofits and fixes are common. There is a growing trend towards digital accessibility legislation and lawsuits, which businesses can avoid by making their websites and apps accessible.

2. **Accessibility in Design Systems**
Front-End and Back-End Developers, Programmers, and Designers can benefit from incorporating accessibility knowledge into their daily work. The Design System approach operationalizes design and creates efficiency and value. How do you integrate accessibility into design systems to create a sustainable process that allows for continuous improvement and a standardized, accessible user experience? Strategies for building accessibility into your organization’s Design Operations will be presented.

**Comment by ericwbailey** [comment]
@mbozz We're happy to include the event, but please provide a description that adhere's to [our issue template](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/.github/ISSUE_TEMPLATE/request-to-add-an-event.md#description).

**Comment by ericwbailey** [comment]
Closed as the event has passed.
