### ISSUE TITLE
Dropdown is not very accessible

### ISSUE THREAD

**Issue by amgolden** [a11yproject/a11yproject.com#803]
The first item on the home page, under "Menus" is "Dropdown."  The way this is currently coded, it is not very good for accessibility as there is no ability at all to interact with menu items using the arrow keys.  Once I activate a drop-down, the only way I can get past it is to tab through every single menu item and this can be quite cumbersome if the menu is very substantial.  (I once experienced a drop-down menu that required me to tab over 300 times to get out of it.)  Forcing users to move through every item to get out of the menu does not provide a very equal experience that allows users with disabilities to interact within the same time-frame and with substantially equivalent ease of use.  You have no idea of the websites this may be plugged in to, nor how many menu items those sites will have.  This current implementation is only somewhat accessible if the site's menu is not very substantial.

**Comment by ericwbailey** [comment]
Thanks for the report, @amgolden. We're currently discussing what to do about [Patterns](https://github.com/a11yproject/a11yproject.com/issues/721), and this kind of info provides valuable context. 

We'll take this into consideration as we move forward with the redesign, and see if we can make some shorter-term updates about these issues for that pattern as well.
