### ISSUE TITLE
a11yproject needs a 404 page

### ISSUE THREAD

**Issue by scottaohara** [a11yproject/a11yproject.com#808]
it just has the stock github pages 404, which is not helpful.

[creating a 404 page](https://help.github.com/en/articles/creating-a-custom-404-page-for-your-github-pages-site)

what's the content that goes here?

**Comment by ericwbailey** [comment]
I like 404s that tell the user what happened, what they can do about it, and who they can contact about it. Not so much a fan of it being a place for a nerd joke with no other actionable information.

**Comment by SebacicA11y** [comment]
And a Search bar too??

**Comment by ericwbailey** [comment]
Search would be nice. It's [a little tricky on a JAMstack](https://www.hawksworx.com/blog/adding-search-to-a-jamstack-site/) site, but I'd like to eventually have it.
