### ISSUE TITLE
New Event Request: ACCESS 2019

### ISSUE THREAD

**Issue by derek3play** [a11yproject/a11yproject.com#809]
Hi there, 
I would like to submit an accessibility event in Boston on October 3rd that many people might be interested in attending!

**Here is the event for free tickets to the event:**
https://eventbrite.com/e/access-2019-tickets-56415471193?discount=darkmatter

**Here is the description for the event:**
ACCESS is for the accessibility enthusiast. Attendees can hear from industry leaders on a11y laws, strategies, and use cases, get certified as a video accessibility expert, network, and get access to free food, swag, open bar at happy hour, and more! 
Whether you already have a video accessibility initiative at your organization or not, you'll leave empowered, motivated, and prepared to create a more universe-ally accessible world.

**Comment by ericwbailey** [comment]
All set! https://github.com/a11yproject/a11yproject.com/commit/ef7cdfc1ae5a08294658f16c349cb5859ddd8e34

Maybe I'll see you there :)

**Comment by derek3play** [comment]
Hey Eric, 

Hope to see you there as well!
Can you make a quick change for us? I realized we added the wrong link for this and ended up getting too many responses for the free tickets. Can you change the Eventbrite URL to https://www.eventbrite.com/e/access-2019-tickets-56415471193?discount=astronaut?

Thanks,
Derek

**Comment by derek3play** [comment]
Feel free to use the free ticket link for yourself :)

**Comment by ericwbailey** [comment]
All set!
