### ISSUE TITLE
install issue gemfile not found

### ISSUE THREAD

**Issue by danseo-reisys** [a11yproject/a11yproject.com#810]
following the install steps.
git clone https://github.com/a11yproject/a11yproject.com.git
cd a11yproject.com
bundle install
Could not locate Gemfile

please advise.

**Comment by scottaohara** [comment]
Hi @danseo-reisys,
You can do an `npm install jekyll` in the a11yproject directory.

There may be some redirect issues occurring when running the site locally due to some work we had to do to get redirects to work for the live site.  These are known issues that we're looking to get solved asap

**Comment by danseo-reisys** [comment]
do you have any reference for running a11y on kubernetes or openshift?

**Comment by danseo-reisys** [comment]
when i run npm, i get following.

npm WARN enoent ENOENT: no such file or directory, open '/root/gitrepos/setup-tools/A11y/a11yproject.com/package.json'
npm WARN a11yproject.com No description
npm WARN a11yproject.com No repository field.
npm WARN a11yproject.com No README data
npm WARN a11yproject.com No license field.

**Comment by scottaohara** [comment]
yeh, those are also known, but shouldn't be a problem to actually loading the site itself.

the only issues you should actually run into are trying to navigate to the top level nav items.  the index and posts should load fine locally.  

also if you comment out `- jekyll-redirect-from` prior to running `jekyll serve` in the command line, even the top level links will work locally.

believe it or not, this is actually a better situation than we were in previously with the build process...  but all this will be corrected once the redesign lands.

**Comment by elmnt** [comment]
I'm seeing the exact same thing. Tried running 'npm install jekyll' in the a11yproject directory, but that didn't seem to change anything. Any hints would be appreciated, thanks!

**Comment by ericwbailey** [comment]
Just added a `Gemfile` and `.ruby-version` via https://github.com/a11yproject/a11yproject.com/pull/815, that should hopefully address the issue.

As for Kubernetes/Openshift, we have no plans to support containerization.
