### ISSUE TITLE
The ROI of Digital Accessibility

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#819]
[Join our live webinar](https://accessibility.deque.com/roi-digital-accessibility-webinar) on August 20th from 1:00-2:00PM EST to learn more.

By making your website accessible, your organization can capture a huge, overlooked market share, reduce your legal risk, lower call-center costs, and boost brand value. 

Building accessibility into your development process and reaching your compliance goals shouldn’t be disruptive to your organization’s development velocity, or business operations. In fact, having an accessible website that is inclusive, increases brand loyalty and expands your organization’s reach to a “hidden” market of $490 billion. 

**Greg Williams**, Accessibility Program Office Executive at Deque, will discuss the ROI of building accessible websites. Attendees will learn:

- How shifting accessibility left in the development process is more cost-effective than fixing accessibility defects in post-production.
- How accessibility can help meet omnichannel goals and reduce costs.
- The revenue potential by adopting accessibility captures an overlooked market share and boosting brand value.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/0dd049d7383e73af370850cdd7370dfabb09faf4.
