### ISSUE TITLE
What you need to report for the 21st Century Integrated Digital Experience Act (IDEA)

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#820]
[Join our live webinar](https://accessibility.deque.com/idea-act-webinar) on August 6th from 1:00-2:00PM EST to learn more.

The 21st Century IDEA Act requires that public service agencies report their state of Section 508 compliance to Congress by December 20, 2019. 

While Section 508 was recently refreshed and the requirements have been around for a couple of decades, this brings a renewed focus on Section 508, requiring CIO's of agencies to submit a report of the baseline status to Congress, with annual updates on the progress. 

In this webinar, Deque’s CEO Preety Kumar will discuss:

- What CIOs need to include in their report to Congress by the December 20th deadline and what’s needed for the subsequent four years.
- How to assess, prioritize, and inventory content for the Congressional report.
- How to scope and create the necessary budget to bring new and existing content into compliance according to the IDEA requirements.
- How to strategically make all new and existing websites and digital services comply with Section 508 going forward.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/0dd049d7383e73af370850cdd7370dfabb09faf4.

@ljgoslin: In the future, it would be great if you could adhere to [the Event issue template](https://github.com/a11yproject/a11yproject.com/issues/new?template=request-to-add-an-event.md). The time it takes to convert these issues into a format we can use adds up.
