### ISSUE TITLE
Code blocks in Posts

### ISSUE THREAD

**Issue by matyus** [a11yproject/a11yproject.com#825]
## Summary

There seems to be inconsistency in how code blocks are formatted between various posts.

### Expected result

Code blocks should use the same syntax and the output should have syntax highlighting.

### Actual result

Some code blocks are syntax highlighted and some aren't.

- Markdown style indent: https://github.com/a11yproject/a11yproject.com/blob/00d814701f2559afbb8f764ab9fbb84cd020bc53/_posts/2013-01-11-how-to-hide-content.md#L22-L28
- Three backticks: https://github.com/a11yproject/a11yproject.com/blob/00d814701f2559afbb8f764ab9fbb84cd020bc53/_posts/2013-01-14-aria-landmark-roles.md#L76-L78
- Three backticks with syntax highlighting: https://github.com/a11yproject/a11yproject.com/blob/00d814701f2559afbb8f764ab9fbb84cd020bc53/_posts/2013-01-14-never-use-maximum-scale.md#L21-L23
- Liquid syntax highlight: https://github.com/a11yproject/a11yproject.com/blob/00d814701f2559afbb8f764ab9fbb84cd020bc53/_posts/2013-05-11-skip-nav-links.md#L20-L34

### Additional Information

I'm interested in contributing to this repo and happy to open a pull request to tidy the code up! Just let me know if I should account for anything in particular... it's not immediately obvious to me how any of this relates to the 2019 redesign.

I would like to propose the use of three back ticks with the filetype (e.g. ` ```html `) rather than plain markdown style double indents or liquid tags.

**Comment by scottaohara** [comment]
The reason for this variance is largely due to different authors over a span of many years.  

If you'd like to clean this up, I say go for it, and thank you :)
