### ISSUE TITLE
IAAP & Deque Webinar: The Real Cost of Accessibility Complaints & Lawsuits

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#830]
Thursday, September 12th from 11:00AM-12:00PM ET - [REGISTER NOW](https://accessibilityassociation.formstack.com/forms/registration_real_cost_webinar)

Has your company received an accessibility complaint or lawsuit? Awareness of the true dollar costs associated with inaccessible content is critical.  Using this data you can build a case for sustained investment. 

Providing accessible content is the best way to avoid complaints and litigation. Handling accessibility complaints properly is critical to avoiding costly litigation. During this webinar, you'll gain insight into these events using real-world cost examples from Fortune 500 companies.

In this webinar, attendees will:
-Gain a better understanding of the current legal landscape surrounding digital accessibility 
-Learn the true cost of an accessibility complaint and lawsuit using real-world numbers
- Hear what your organization can do after receiving a complaint or lawsuit (short-term and long-term)
-Learn how to use statistics about legal costs and potential market share to build a case for accessibility

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/be5d72a02703cbc37d571d4e5f9727eea4c14920.

@ljgoslin Again, we ask you adhere to [the contributing guidelines](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#events) and to [use the issue template](https://github.com/a11yproject/a11yproject.com/issues/new?template=request-to-add-an-event.md) when submitting events. While we're happy to help promote community events, the time it takes to format them to work with our site adds up.
