### ISSUE TITLE
Bug: `localhost` link in Checklist

### ISSUE THREAD

**Issue by knagurski** [a11yproject/a11yproject.com#833]
The link to _"Non-text contrast"_ under _"Check the contrast for all icons"_ on the [Checklist page](https://a11yproject.com/checklist/#section-color-contrast) points to a `localhost` URL.
 
## Summary
1. Navigate to the [Checklist page](https://a11yproject.com/checklist/)
2. Scroll to the [_"Color contrast"_](https://a11yproject.com/checklist/#section-color-contrast) section
3. Expand the _"Check the contrast for all icons."_ section
4. Click the _"1.4.11 Non-text Contrast"_ link

### Expected result
The link should click through to `https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html`

### Actual result
The link clicks through to `http://localhost:4000/AA%20requires%20contrast%20ratio%20of%203.0:1.`

**Comment by scottaohara** [comment]
thank you @knagurski
