### ISSUE TITLE
Add offline support

### ISSUE THREAD

**Issue by knagurski** [a11yproject/a11yproject.com#835]
## Summary
Currently a11yproject.com does not have offline support and does not pass Lighthouse PWA audits.

1. Open https://a11yproject.com
2. Click around site
3. Disconnect from network
4. Click around site

### Expected result
Pages and assets previously displayed should be retrieved from cache

### Actual result
Pages fail to load

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/issues/835.
