### ISSUE TITLE
Bug: Contribute link on https://a11yproject.com/ sends you somewhere confusing.

### ISSUE THREAD

**Issue by suzannehillman** [a11yproject/a11yproject.com#837]
## Summary
Brief description of the issue. Please identify specific steps.
 
1. Go to https://a11yproject.com/
2. Click on the "Contribute on Github" button. 
3. Be utterly confused as to what to do next.

### Expected result
I would have expected it to either have opened up "https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md" or (probably a better place to start) "https://github.com/a11yproject/a11yproject.com/blob/gh-pages/README.md"

### Actual result
It sends you to the main github page, not a document that tells you what contributors can do. If you scroll down a lot, you get to the readme eventually, but it's not especially friendly to make people do that (especially not people who have to use screen readers!).

### Additional Information
To help us try and reproduce the issue, please provide the following information:

1. Laptop, but I doubt it matters.
2. Windows 10, and I doubt it matters. 
3. Firefox 68.0.2 (64-bit), and see above.

### Additional Information
Note anything else you think would be important to know that didn't fall into an above category.

I clicked on the current link and - as is often the case with github pages - find it strange that the first thing one sees on a github page is the files instead of a readme type page. Since it's possible to adjust that, why not do that?

**Comment by ericwbailey** [comment]
Thank you for submitting this issue, @suzannehillman. It's a really insightful observation.

To provide some background, the contributing documentation was only recently updated, while the contribute link has been a longtime part of the site.

Would you be interested in submitting a PR to address the issue, or would you prefer we make the update? We more than welcome community contributions!

**Comment by suzannehillman** [comment]
Hi @ericwbailey,

I'm currently working on setting up the website on my machine so that I can do a PR - hopefully the instructions are sufficient. If not, I shall clearly need to update those, as well! (and find out where to get additional help)

**Comment by ericwbailey** [comment]
That'd be great! Feel free to post in this issue if you run into anything, I'm happy to help if I can 🙂

**Comment by suzannehillman** [comment]
First problem: "git@github.com:a11yproject/a11yproject.com.git" doesn't actually do anything useful (at least not in debian on windows). I had to use "git clone https://github.com/a11yproject/a11yproject.com" instead.

I was wondering why that would work, so wasn't shocked that it did not. I am curious, however, why that's what was put in the readme?

**Comment by suzannehillman** [comment]
Ok, I've gotten the site up and running locally, but I cannot figure out which markdown files to edit to adjust that link. A grep on "ontribute" only shows me html files with the appropriate text, no others.

**Comment by ericwbailey** [comment]
For the first part, that's on me for forgetting the `git clone` portion of the command (I wrote that section). I think you also raised a good point in that using https may be a lower barrier of entry than setting up SSH keys and all that. I'll make an update to that documentation soon.

For the second part: In Jekyll, anything that isn't a blog post is sourced from HTML templates and data from the `_data/` directory. We're also using HTML `href` attributes instead of routing or attribute manipulation for navigation, as it is far more robustly supported by assistive technology. 

It's looking like you should be able to [update the URL on this line in `archives.html`](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/_layouts/archives.html#L25) and point it to the destination you mentioned in your expected result (it looks like there's extra spaces surrounding the `class` attribute as well).

**Comment by ericwbailey** [comment]
Another thing that's on my radar is moving our contributing content off GitHub and onto the site, so we don't have that jolt of jumping off the site onto GitHub, which can be very intimidating. That fix is a little down the line, however.

**Comment by suzannehillman** [comment]
Right, ok. So I've edited the _layouts/archives.html file, and realized that I hadn't made my own branch. I've since done that and told it to push that branch to origin, and it's complaining that I don't have access (error 403). Do I need to update my ssh key somehow? (I ended up using the Fork GUI for git because I always forget how annoying it is to remember all the steps - I already have an ssh key in github for it, so I thought it would just work)

Error message: "remote: Permission to a11yproject/a11yproject.com.git denied to suzannehillman.
fatal: unable to access 'https://github.com/a11yproject/a11yproject.com/': The requested URL returned error: 403
Pushing to https://github.com/a11yproject/a11yproject.com/"

**Comment by alexroseb** [comment]
Hi Suzanne,
Since you’re not a member of the repository, you need to push your changes to your own fork (not just branch, your whole own fork) and open a pull request from that to a11yproject. Here’s a GitHub help link on that: https://help.github.com/en/articles/fork-a-repo.

**Comment by suzannehillman** [comment]
@alexroseb Ah, thank you! It might be good to update the docs at https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md then - it talks about branches, but not forks. I couldn't remember what forks were for. :)
