### ISSUE TITLE
Cleveland Accessibility October Meetup: JAWS Inspect Tool and Manual Testing

### ISSUE THREAD

**Issue by mbozz** [a11yproject/a11yproject.com#838]
Cleveland Accessibility Oct 9th Meetup is **[JAWS Inspect: An Inclusive Approach To Manual Accessibility Testing](https://www.meetup.com/Cleveland-Accessibility-Meetup/events/264002876/)**. Larry Lewis of The Paciello Group will discuss manually testing content for screen reader performance and issues, and give a demo of the **[JAWS Inspect tool](https://www.meetup.com/Cleveland-Accessibility-Meetup/events/264002876/)**. 

RSVP: https://www.meetup.com/Cleveland-Accessibility-Meetup/events/264002876/

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/571fdc3be173234c74c32dfbf050e23bed81b7c3.

@mbozz In the future can you [use the issue template](https://github.com/a11yproject/a11yproject.com/issues/new?template=request-to-add-an-event.md) when submitting events? While we're happy to help promote the meetup, the time it takes to format them to work with our site adds up.
