### ISSUE TITLE
Bug: favicon not visible on light-themed browser

### ISSUE THREAD

**Issue by b3u** [a11yproject/a11yproject.com#844]
## Summary
The favicon is completely white, which makes it invisible on a light ui.

Example:
  1. Go to a11yproject.com
  2. Look at favicon

### Expected result
My solution would be a dark favicon with a white border, making it visible on either a dark or a light background.

**Comment by ericwbailey** [comment]
Howdy, @b3u! I think that's a great observation. Is that something you'd like to try to fix?

**Comment by b3u** [comment]
Sure!

**Comment by b3u** [comment]
I'm overthinking it. I went for the gray with a white border and background. Let me know if that's good.

**Comment by ericwbailey** [comment]
Looks great! Thank you so much!

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/848.
