### ISSUE TITLE
Typo in checklist > controls

### ISSUE THREAD

**Issue by PhilipKrook** [a11yproject/a11yproject.com#846]
### Finding the issue
> How to get to the issue:
> 1. Turn on Chrome 
> 2. Go to a11yproject.com
> 3. Navigate to "checklist" then to "Controls" and click the ":focus" dropdown

### Actual result
There is a typo on line 2:
"Visible focus styles help people determine **_wihch_** interactive element has"

### Additional Information
> To help us try and reproduce the issue, please provide the following information:
> 1. Using laptop
> 2. Windows 10
> 3. Chrome

Thank you all for a great and very helpful site!

**Comment by alexroseb** [comment]
@PhilipKrook, does that fix look good?
