### ISSUE TITLE
Inaccuracy: Incorrect number of ARIA roles

### ISSUE THREAD

**Issue by tomlroach** [a11yproject/a11yproject.com#853]
## Summary
On this page: 
https://a11yproject.com/posts/getting-started-aria/

The Aria roles section says: 
> There are four categories of ARIA roles.

![image](https://user-images.githubusercontent.com/6569324/67503549-6cd00e80-f64d-11e9-9b55-bc1e310153d9.png)

But then it goes on to list 6 categories of role
![image](https://user-images.githubusercontent.com/6569324/67503580-7a859400-f64d-11e9-8386-a0a31675fe51.png)

### Expected result
It should presumably say there are six roles. Or it should distinguish more clearly between the four roles being referred to, and the other two.

### Actual result
Mismatch in number of roles listed and the number asserted in the content.

**Comment by alexroseb** [comment]
Thanks for the catch, @tomlroach! Please check out #854 and see if that looks good.
