### ISSUE TITLE
Accessibility Club Summit 2019

### ISSUE THREAD

**Issue by jkphl** [a11yproject/a11yproject.com#855]
The Accessibility Club Summit 2019 from November 16th-17th in Berlin, Germany, is the Accessibility Club's first ever 2-day community summit for developers, designers & accessibility enthusiasts, jointly run by several a11y meetups from all over Europe. We will have a full-day barcamp on Saturday, November 16th, with 5 pre-assigned international presentations and 10 additional spontaneous sessions. Sunday, November 17th, will be packed with 9 half- and full-day workshops around accessibility and disability topics, run by community members. The event is non-profit and open to anyone / any skill level.

Website: https://accessibility-club.org/event/accessibility-club-summit-2019
Colloq: https://colloq.io/events/accessibility-club/2019/berlin/1

**Comment by alexroseb** [comment]
@jkphl Thanks for the event submission! Would you mind adding a comment formatting the information as follows please:

## Title
>Add the title of your event here.

### Description
>A brief description (2-3 sentences).

### URL
>Link to the best place for people to sign up for you event (for instance your Meetup or Eventbrite page).

### Date
>Provide dates in Year / Month / Day, e.g. 20XX-01-01.

### Type
>Indicate if the event is a "Webinar" and/or "Regional".

### Address (if Regional)
>Physical address of event (if applicable).

### Map (optional)
>Use an online map service to provide a link to your event's physical address.

### Hashtag (optional)
>Let people follow along on social media with your unique Hashtag.

**Comment by jkphl** [comment]
@alexroseb Sure! We'll have 2 days and 4 locations, hope this works for you. Thanks!

## Title
Accessibility Club Summit 2019

### Description
This is the Accessibility Club's first ever 2-day community summit for developers, designers & accessibility enthusiasts, jointly run by several a11y meetups from all over Europe. We will have a full-day barcamp on Saturday, November 16th, with 5 pre-assigned international presentations and 10 additional spontaneous sessions. Sunday, November 17th, will be packed with 9 half- and full-day workshops around accessibility and disability topics, run by community members. The event is non-profit and open to anyone / any skill level.

### URL
https://accessibility-club.org/event/accessibility-club-summit-2019

### Date
2019-11-16..17

### Type
Regional (Barcamp + Workshops)

### Address
#### Barcamp (2019-11-16)
Microsoft Atrium
Charlottenstraße 46
10117 Berlin

#### Workshops (2019-11-17)
Thoughtworks
Zimmerstraße 23
10969 Berlin

.Henkelhiedl
Urbanstraße 116
10967 Berlin-Kreuzberg

Immobilien Scout
Andreasstraße 10
10243 Berlin 

### Map (optional)
Microsoft: https://goo.gl/maps/j5Z61nzuFkEUbLbr7
Thoughtworks: https://goo.gl/maps/RL8eMjbasJCwYGKn8
.Henkelhiedl: https://goo.gl/maps/oWZ3BTdpj2KLYL2z6
Immobilien Scout: https://goo.gl/maps/QH1rLiskAoaQ3ASf6

### Hashtag (optional)
a11yclubSummit
