### ISSUE TITLE
Smashing and Deque: Translating Design Wireframes Into Accessible HTML/CSS

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#858]
## Title
>Translating Design Wireframes Into Accessible HTML/CSS.

### Description
>In this webinar, Harris will walk you through the process of analyzing a wireframe from an accessibility perspective, making coding decisions to optimize for accessibility, implementing that code, testing your code, and troubleshooting.

### URL
>https://www.smashingmagazine.com/smashing-tv/translating-design-wireframes-into-accessible-html-css/.

### Date
>2019-11-20 from 1:00-2:00PM ET

### Type
>Webinar.

**Comment by alexroseb** [comment]
Thanks for the event updates!
