### ISSUE TITLE
Free Webinar on Accessible Edtech: How Clever made accessibility changes that impact millions of K-12 students

### ISSUE THREAD

**Issue by gkirk16** [a11yproject/a11yproject.com#864]
[Clever](https://clever.com/), the most widely used SSO platform for K-12 education, undertook accessibility changes that impacted millions of students, teachers and administrators country-wide. Hear from their Director of design, James Reffell, and Software Engineer, Anthony Fumagalli, on how they approached accessibility for their site, which has a far-reaching impact in US education. 

Link to Sign Up Form: https://accessibility.deque.com/clever-edtech-accessibility-webinar

**Comment by ericwbailey** [comment]
Hi @gkirk16. Thank you for submitting this event. Please reformat it to use [the event issue template](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/.github/ISSUE_TEMPLATE/request-to-add-an-event.md), as outlined in our [contributing documentation](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#events).

**Comment by gkirk16** [comment]
Hi @ericwbailey, my apologies (first time submitting!). Resubmitting in proper template.
