### ISSUE TITLE
Webinar: Accessible Edtech: How Clever made accessibility changes that impact millions of K-12 students

### ISSUE THREAD

**Issue by gkirk16** [a11yproject/a11yproject.com#865]
## Title
>Accessible Edtech: How Clever made accessibility changes that impact millions of K-12 students

### Description
>[Clever](www.clever.com), the most widely used SSO platform for K-12 education, undertook accessibility changes that impacted millions of students, teachers and administrators country-wide. Hear from their Director of design, James Reffell, and Software Engineer, Anthony Fumagalli, on how they approached accessibility for their site, which has a far-reaching impact in US education. Hosted by [Deque](www.deque.com)

### URL
>https://accessibility.deque.com/clever-edtech-accessibility-webinar

### Date
>2019-12-10

### Type
>Webinar

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/9fe603f50469a296245498d42a719fabe21cb63a. Thank you!
