### ISSUE TITLE
Inaccuracy: JAWS is an acronym; HTML is an initialism

### ISSUE THREAD

**Issue by mndrsn** [a11yproject/a11yproject.com#871]
## Summary
We have an opportunity to be a bit more specific when discussing acronyms versus initialisms on the article [Quick Tip: a11y and a brief numeronyms primer](https://a11yproject.com/posts/a11y-and-other-numeronyms/).

### Expected result
> Unlike [abbreviations](https://en.wikipedia.org/wiki/Abbreviation) like FYI (for your information), and PC (personal computer), or [initialisms](https://en.wiktionary.org/wiki/initialism) like HTML (hypertext markup language), and CSS (cascading style sheet), or [acronyms](https://en.wikipedia.org/wiki/Acronym) like JAWS (Job Access With Speech), and NASA (National Aeronautics and Space Administration) numeronyms are number-based words.

### Actual result
> Unlike [abbreviations](https://en.wikipedia.org/wiki/Abbreviation) like FYI (for your information), and PC (personal computer), or [acronyms](https://en.wikipedia.org/wiki/Acronym) like HTML (hypertext markup language), and JAWS (Job Access With Speech), numeronyms are number-based words.

### Additional Information
While the term acronym is commonly used to refer to both types of abbreviations, I feel like we have the opportunity to be more specific here. I do realize that adding yet another term into this paragraph makes it a bit of a lengthy sentence. If the desire for this change is mutual perhaps we could restructure this paragraph to read a bit clearer.

**Comment by ericwbailey** [comment]
Thanks for the further clarification, @mndrsn! I agree, the more specific we can be about the issue, the better. I also agree about the sentence length concerns—would you be comfortable drafting a PR so we could work on the issue together?

**Comment by alexroseb** [comment]
What about:
> There are many ways to shorten longer words and concepts into simpler terms. You may have heard of [abbreviations](https://en.wikipedia.org/wiki/Abbreviation) like FYI (for your information), and PC (personal computer), [initialisms](https://en.wiktionary.org/wiki/initialism) like HTML (hypertext markup language), and CSS (cascading style sheet), and [acronyms](https://en.wikipedia.org/wiki/Acronym) like JAWS (Job Access With Speech), and NASA (National Aeronautics and Space Administration). Similarly, numeronyms are number-based words.

**Comment by mndrsn** [comment]
I like what @alexroseb has recommended above in terms of a light restructuring. I can get a PR drafted with this content stubbed in as a starting point, or potential conclusion.

**Comment by ericwbailey** [comment]
That's great! Thank you!

**Comment by mndrsn** [comment]
@ericwbailey I've forked gh-pages and have submitted a PR for the change. Is there anything left for me to do on my end? Thanks in advance for your patience, it's been some time since I've submitted a PR to an external repo.

**Comment by ericwbailey** [comment]
Hm, I'm not seeing it. Did you push the PR up to your repo, or ours?

**Comment by mndrsn** [comment]
I pushed it up to mine.

**Comment by ericwbailey** [comment]
Ok, that would do it. Would you mind pushing it to this repo instead? That way we can merge your changes in.

**Comment by mndrsn** [comment]
@ericwbailey I'm getting the following error (see screenshot). It appears that I do not have privs to push to origin. I did all of the log out, log back in, etc. Also set up SSH on my machine. Not quite sure what's going on.
![Screen Shot 2019-12-23 at 2 46 05 PM](https://user-images.githubusercontent.com/13057402/71380056-75808a80-2593-11ea-8f39-6848b14871a6.png)

**Comment by ericwbailey** [comment]
@mndrsn Sorry for the extremely late reply. Long and short, 2020 happened. We've replatformed, so there might need to be some work on updating the PR to match our new CMS. Is this something you're still interested in working on?

**Comment by mndrsn** [comment]
@ericwbailey I may lean on you guys to carry this over the finish line. My git muscle memory is a little rusty as it shows, and considering that we appear to have landed on a direction, I'm fine with someone else taking this. Happy to have helped identify a resolution for this, though.

**Comment by ericwbailey** [comment]
Thank you, that's totally good.

It's really my fault for dropping the ball so hard. I'll make sure you're properly attributed.

**Comment by missmatsuko** [comment]
> There are many ways to shorten longer words and concepts into simpler terms. You may have heard of abbreviations like FYI (for your information), and PC (personal computer), initialisms like HTML (hypertext markup language), and CSS (cascading style sheet), and acronyms like JAWS (Job Access With Speech), and NASA (National Aeronautics and Space Administration). Similarly, numeronyms are number-based words.

This is confusing to me... aren't these all abbreviations (including numeronyms)? And aren't FYI and PC also initialisms?

**Comment by scottaohara** [comment]
agree with @missmatsuko, it is sort of burying the lede here.

from: wikipedia's entry on acronym
>The broader sense of acronym inclusive of terms pronounced as the individual letters (such as "TNT") is sometimes criticized, but it is the term's original meaning and is in common use

if this is really something that needs to be called out, then would much rather revise to:
>Unlike abbreviations like FYI (for your information), and PC (personal computer), or **initialisms &** acronyms like HTML (hypertext markup language), and JAWS (Job Access With Speech), numeronyms are number-based words.

**Comment by missmatsuko** [comment]
I think it's still confusing because all of those are abbreviations, just through different methods. 

Not all numeronyms are abbreviations, but "a11y" is a numeronym that is also an abbreviation for "accessibility". 

FYI, PC, HTML, and JAWS are also all abbreviations - most of them are initialisms except for JAWS which is an acronym (if you want to differentiate between acronyms and initialisms).

**Comment by ronsman** [comment]
The rules I follow as an editor are that an abbreviation is a shortened word (eg pro for professional), an initalism is where the initials of more than one word are pronounced as initials (eg FYI, PC, HTML), an acronym is a set of initals pronounced as a word (eg JAWS) and a numeronym is a shortened version of a word transposing a numeral for the number of letters between the first and last letter. A numeronym is meant only to be written, saving the effort of spelling out long words - that a11y resembles alley is an accident, you can't pronounce i18n, for instance. The other point is that acronyms can over time be accepted as words that don't need to be capitalised, eg radar and scuba.

**Comment by missmatsuko** [comment]
Yeah those are all abbreviations but not all numeronyms are abbreviations. For example the `520` example from the Wikipedia for numeronyms is a numeronym for `我爱你` but it's the same number of characters.

**Comment by scottaohara** [comment]
i like your approach @missmatsuko. the point of this article is to educate people on numeronyms and a11y specifically.  if people want to go down the rabbit hole of splintering this up into other sub-categories, fine. but that was never the point of this article, so let's move away from the content

would you mind taking a stab at rewording this?  i tried again, but I felt like it could still be cut down further.

**Comment by ericwbailey** [comment]
Closed for inactivity. @missmatsuko, feel free to re-open if you have the bandwidth!
