### ISSUE TITLE
Build vs. Buy: Automated Accessibility Tools

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#872]
## Title
Build vs. Buy: Automated Accessibility Tools

### Description
>In this live webinar, our presenters will review why in some cases it’s better to buy vs. build your own accessibility solution. They will review:

- The time, resources, and effort it takes to support and maintain a “built” solution

- How a “bought” solution can put you at a better starting point to address accessibility

- Features in “bought” solutions such as HTML reporting, dashboards, supported out of the box bindings, and custom rules. 

### URL
>https://accessibility.deque.com/build-vs-buy-webinar.

### Date
>2020-01-14.

### Type
>"Webinar".

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/0abd31fa520f37d2066041d3ea01ccf5f390af59. Thank you!
