### ISSUE TITLE
article redirect not working

### ISSUE THREAD

**Issue by scottaohara** [a11yproject/a11yproject.com#874]
The Safari keyboard article had the URL of https://a11yproject.com/posts/safari-keyboard-navigation/

It was updated in Nov. 2019 and the URL was changed to https://a11yproject.com/posts/macos-browser-keyboard-navigation/

There is a redirect noted in the markdown file, but the old URL goes to a 404 page rather than the new article.

**Comment by duncanjimbo** [comment]
We can close this as the fix has been resolved

**Comment by ericwbailey** [comment]
Thanks for the head's up, and for the fix. Closing now.
