### ISSUE TITLE
John Slatin AccessU

### ISSUE THREAD

**Issue by EricaBraverman** [a11yproject/a11yproject.com#879]
Hello, I would like to add the following conference to your events list please:

[John Slatin AccessU](https://knowbility.org/programs/accessu/2020/)
May 11-14 2020
Austin, Texas, United States
Both in-person and online sessions
Organizer: [Knowbility](https://knowbility.org/)

AccessU is the only three-day, hands-on conference that provides tools that can immediately be put to use by designers, developers, project managers, administrators, and anyone who is responsible for online content and development. John Slatin AccessU teaches those skills in an interactive and communal environment where you will learn everything you need to know about integrating accessibility into your company.

Thank you and please let me know if you have any questions,
Erica

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/e38d77bb9079a8c082421fa47431e20680f1cdbd. Thank you!

**Comment by EricaBraverman** [comment]
Hi Eric, thank you so much for posting our conference!

I am so sorry, I should have clarified this - the La Posada address is our office but the conference itself will take place at:

St. Edward's University
3001 South Congress Avenue
Austin, TX 78704

Can you please change the event address to this?
Thank you so much,
Erica

**Comment by ericwbailey** [comment]
All set!
