### ISSUE TITLE
AccessU Online 2020

### ISSUE THREAD

**Issue by teleject** [a11yproject/a11yproject.com#880]
Knowbility brings together some of the Web's most notable experts in digital accessibility for an all-new, full-day online conference, the AccessU Online! Bring the experts to your desktop May 14, 2020 from 9AM to 4:30PM (CT).

https://knowbility.org/programs/accessu/2020/accessu-online/

**Comment by ericwbailey** [comment]
Hi Christopher! Closed via https://github.com/a11yproject/a11yproject.com/commit/43e0c00226ab0a6a7654c8efceb9a0f0ff929992, best of luck with the webinar!
