### ISSUE TITLE
Article: Accessibility Lanes!

### ISSUE THREAD

**Issue by SMotaal** [a11yproject/a11yproject.com#881]
## Description

As someone who could once overcome difficulties in their world through the use of computers, in more recent years, this all started falling apart.

Sure, people have all kinds of differences, but there is a big problem when the world keeps introducing "fast lanes" for the mainstream of folks, each adhering or not to any given subset of the accessibility requirements. The problem now becomes, how do folks navigate the web, how do the search for and locate the respectively-accessible "fast lanes". And once they do, how do they find a fair balance of the added overload to allow them to be equal users with others for whom the experience was designed to see them in overdrive.

It is really sad to say, as a developer, I see all kinds of conformance work allowing people to pass the scrutiny on regulatory and legal requirements. But the story for a developer like myself, that is overlooked, because that story is never really considered, merely how the mainstream one looks and if along the way everything in it was properly made accessible.

I always suffered with reading and writing, but I was only diagnosed with a Visual Processing Learning Disability at the age of 25, in my junior year in my bachelors, along with ADHD. Because until then computers were my secret weapon, no one including myself even needed to wonder, until it was overloading. The following 10 years saw further overload, and that was now very characteristic with what some like to call "mild autism" or "high functioning autism". The problem is, all those conditions are life long ones, which may sometimes merely go undiagnosed, until a certain threshold of unsustainable overload is reached, then they become perpetually more pronounce and disabling.

Mine is offered as one story, of what is likely unfolding for too many folks, irrespective of the difference, and sadly it gets worse by the minute.

It is almost ironic, for me to find the accessible way to use any site, especially sites like GitHub, I've spent more than 2 years searching… the bottom line is all links lead to the wrong thing. Filing issues leads to the wrong thing, and even making calls or contacting support, nothing but proforma things.

## Would you like to write the article or request that it be written?

I would like to co-author or help working towards article about the disconnect between accessibility features and its intended consumers, and how accessibility lanes can be a way to close this disconnect.

> **Note** — I am not sure if article is the way to go, but it sounds like a good first step for my first issue on a11yproject.
>
> I'm also actively looking on Quora, and try to ask questions like: [<q>For any GitHub open source collaborators who suffer from significant visual and cognitive overload, relating to ADHD, ASD, LD, etc., can you share some usability and productivity insights from your experience?</q>](https://www.quora.com/unanswered/For-any-GitHub-open-source-collaborators-who-suffer-from-significant-visual-and-cognitive-overload-relating-to-ADHD-ASD-LD-etc-can-you-share-some-usability-and-productivity-insights-from-your-experience).
>
> Sometimes I try to answer ones like: [How do you unlearn social prejudice that's influenced by your environment?](https://www.quora.com/How-do-you-unlearn-social-prejudice-thats-influenced-by-your-environment/answer/Saleh-Abdel-Motaal)

**Comment by ericwbailey** [comment]
Closed for inactivity.
