### ISSUE TITLE
Authoring Accessible Content Workshop

### ISSUE THREAD

**Issue by teleject** [a11yproject/a11yproject.com#883]
March 26, 2020

Learn how semantic HTML is the foundation for websites and an integral part of digital accessibility. By following semantic HTML and organizing content, your web presence will gain more users, allow for easier to maintain code, and support current accessibility requirements.

https://knowbility.org/services/training/authoring-accessible-content/

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/2aab881fbf9560894220f46dde12bac23a7810ad. Thank you!
