### ISSUE TITLE
2019 Accessibility Trends

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#887]
## Title
>2019 Accessibility Trends.

### Description
>Preety Kumar, CEO, Deque Systems kicks off CSUN Assistive Technology Conference sessions by presenting "the state of the accessibility industry." For the 6th consecutive year, Preety shares her annual report looking at trends across the accessibility industry.

### URL
>https://accessibility.deque.com/csunatc20-accessibility-trends.

### Date
>2019-03-11.

### Type
>"Webinar".

**Comment by ericwbailey** [comment]
Hi @ljgoslin. We have deprecated events with the redesign, so I will be closing this and the other open event issues you've submitted. Thank you for working with us for past events, I really appreciated your flexibility with our process.
