### ISSUE TITLE
How to Act and Understand Accessibility Right Now

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#910]
## Title
>How to Act and Understand Accessibility Right Now.

### Description
>People with disabilities make up 26% of the US population. If your digital presence is inaccessible, they may not have any way to access your goods and services. There has never been a more crucial time to make your digital properties accessible, while COVID-19 continues to physically isolate us all. 

In this live webinar, Deque's experts will cover what it takes to make essential business functionality accessible to all and what it takes to make a difference right now.

### URL
>[Regiser Now](https://accessibility.deque.com/how-to-act-and-understand-accessibility-right-now).

### Date
>2020-04-07.

### Type
>"Webinar".

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/1d648bc42c759bfcfe60c23a099cbf65b918f0da. Thank you!
