### ISSUE TITLE
Digital Accessibility Legal Update

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#914]
## Title
>Digital Accessibility Legal Update.

### Description
>In this live webinar, Kristina Launey, a Partner at Seyfarth Shaw LLP and accessibility specialist, will discuss the legal landscape of digital accessibility, including recent and important developments.

Kristina Launey is a Counselor, Trainer, and Litigator who partners with businesses to develop best practices and ensure compliance with federal and state employment and anti-discrimination laws, including the Americans with Disabilities Act, California's Unruh and Disabled Persons Act, and other state and federal laws. 

She has extensive experience assisting clients with disability access litigation and compliance issues.  A Member of Seyfarth's ADA Title III Specialty Team and adatitleiii.com blog co-creator and contributor, Kristina is also a frequent writer and presenter on disability access issues.

### URL
>https://accessibility.deque.com/digital-accessibility-legal-update.

### Date
>2020-04-16 at 2:00PM ET.

### Type
>Webinar.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/863dbf128c941aba57fc6f713bc2182f885ba232. Thank you!
