### ISSUE TITLE
Intro to Accessible Online Learning

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#915]
## Title
>Intro to Accessible Online Learning.

### Description
>Whether you’re a part-time student, a professional continuing their education, or you prefer to be an online learner - the need for online learning is growing in K12 and Higher Education. Especially now, while COVID-19 has shifted all learning to virtual classrooms.

Ensuring that Learning Management Systems (LMS) and teaching methodologies are accessible is critical for students with disabilities. In this introductory webinar, attendees will learn:

- An Intro to Accessibility in EDU
- An Intro to accessible online learning
- Etiquette and overlooked best practices for accessible learning
- Accessibility best practices for major learning management systems such as Zoom, Blackboard, and Canvas
- An Intro to Accessible Documents.

### URL
>https://accessibility.deque.com/intro-to-accessible-online-learning-0.

### Date
>2020-04-21 at 2:00PM ET.

### Type
>Webinar.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/863dbf128c941aba57fc6f713bc2182f885ba232. Thank you!
