### ISSUE TITLE
The Basics of Remediating an Inaccessible PDF

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#916]
## Title
>The Basics of Remediating an Inaccessible PDF.

### Description
>Making a PDF document accessible for people with disabilities can be a daunting task if you're completely new to the topic. In this webinar, we will walk through the workflow of converting a Word Document and fixing some basic tagging issues using Acrobat Pro DC.

This webinar is designed for those who are new to PDF accessibility remediation or those who want a refresher. It will cover such subjects as: 

Changing existing tags
Creating new tags
Working with simple lists and tables
Tagging content as an artifact.

### URL
>https://accessibility.deque.com/the-basics-of-remediating-an-inaccessible-pdf.

### Date
>2020-05-12 from 2:00-3:00PM ET.

### Type
>Webinar.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/3cb8b8b83c647211569b60117bf5ab22c4c101df. Thank you!
