### ISSUE TITLE
Accessible Images When It Matters Most

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#917]
## Title
>Accessible Images When It Matters Most.

### Description
>Carie Fisher, Senior Accessibility Consultant at Deque, will review:

- The different types of images - decorative vs informative (plus actionable, emotional, simple, and complex)
- Accessibility of informational images created during the COVID-19 pandemic
- Which image elements we need to incorporate in our designs to make our images more inclusive to all.

### URL
>https://accessibility.deque.com/accessible-images-when-it-matters-most.

### Date
>2020-05-14.

### Type
>Webinar.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/1e998bcb4191e253b7dbb345a07157d7841f7926.
