### ISSUE TITLE
GAAD 2020: Virtual Panel - Teleworking for People with Disabilities

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#918]
## Title
>Virtual Panel - Teleworking for People with Disabilities.

### Description
>In celebration of this year's Global Accessibility Awareness Day (GAAD), this virtual panel will discuss teleworking for people with disabilities.

.

### URL
>https://accessibility.deque.com/teleworking-people-with-disabilities.

### Date
>2020-05-21.

### Type
>Webinar.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/1e998bcb4191e253b7dbb345a07157d7841f7926.
