### ISSUE TITLE
GAAD 2020: Basic Accessibility Fundamentals Bootcamp

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#919]
## Title
>Basic Accessibility Fundamentals Bootcamp.

### Description
>In celebration of this year's Global Accessibility Awareness Day (GAAD), Deque is offering free training of its basic accessibility fundamentals boot camp.

### URL
>https://accessibility.deque.com/basic-accessibility-fundamentals-bootcamp.

### Date
>2020-05-21.

### Type
>Webinar.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/1e998bcb4191e253b7dbb345a07157d7841f7926.
