### ISSUE TITLE
GAAD 2020: Intro to Agile Accessibility

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#920]
## Title
>Intro to Agile Accessibility.

### Description
>In celebration of this year's Global Accessibility Awareness Day (GAAD), Deque is excited to bring you this free webinar on agile accessibility..

### URL
>https://accessibility.deque.com/intro-to-agile-accessibility.

### Date
>2020-05-21.

### Type
>Webinar.

**Comment by ericwbailey** [comment]
https://github.com/a11yproject/a11yproject.com/commit/1e998bcb4191e253b7dbb345a07157d7841f7926
