### ISSUE TITLE
GAAD 2020: Digital Accessibility Legal Update

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#921]
## Title
>GAAD 2020: Digital Accessibility Legal Update.

### Description
>In celebration of this year’s Global Accessibility Awareness Day (GAAD), Deque is proud to have attorney Eve Hill, one of the nation’s leading disability rights attorneys from the law firm, Brown, Goldstein & Levy, join us for a digital accessibility legal update.

### URL
>https://accessibility.deque.com/gaad-2020-digital-a11y-legal-update.

### Date
>2020-05-20.

### Type
>Webinar.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/1e998bcb4191e253b7dbb345a07157d7841f7926.
