### ISSUE TITLE
Article: [Your title]

### ISSUE THREAD

**Issue by Mshaffar** [a11yproject/a11yproject.com#923]
Delete this boilerplate or any other information that doesn't apply to your article.
Please review our [contributing guidelines](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/CONTRIBUTING.md#submitting-content).

## Description
>A brief description (2-3 sentences) of your proposed article. Why should this article be written, and how does it fit on The A11Y Project?

## Would you like to write the article or request that it be written?
>Are you posting this as a means to look for help on the topic or do you have a method you've developed/tested to solve the issue/topic?

**Comment by nainardev** [comment]
better close this issue
