### ISSUE TITLE
Error on Checklist

### ISSUE THREAD

**Issue by stevepera** [a11yproject/a11yproject.com#924]
On the very first item under the first category: Content, Use plain language.  The success criteria should be "3.1.5 Reading Level".  The current criteria "3.1.2 Language of Parts" does not address using plain language.

**Comment by ericwbailey** [comment]
All set! Closed via https://github.com/a11yproject/a11yproject.com/commit/843e9bd346b3a9548ab90630c7459a9f591c90a0. Also see https://github.com/a11yproject/a11yproject.com/issues/925.
