### ISSUE TITLE
Error on Checklist

### ISSUE THREAD

**Issue by stevepera** [a11yproject/a11yproject.com#925]
Under "Content,  Use left-aligned text for left-to-right languages...", the criteria should be "1.4.8 Visual Presentation" , not "1.3.1 Info and Relationships".

**Comment by ericwbailey** [comment]
Ah, great call, thank you. Closed via https://github.com/a11yproject/a11yproject.com/commit/843e9bd346b3a9548ab90630c7459a9f591c90a0. Also see https://github.com/a11yproject/a11yproject.com/issues/924.
