### ISSUE TITLE
Intro to Word Document Accessibility Webinar

### ISSUE THREAD

**Issue by ljgoslin** [a11yproject/a11yproject.com#931]
## Title
>Intro to Word Document Accessibility.

### Description
>In this live webinar, Karina Boycheva, Instructional Designer for Deque University, will review key topics such as:

Headings, fonts, color contrast, and appearance
Tables, Charts, Graphs
Image alt text and long descriptions
Using the Accessibility Checker
Exporting to other formats (HTML, PDF, EPUB)

### URL
>https://accessibility.deque.com/intro-to-word-document-accessibility.

### Date
>2020-07-21.

### Type
>Webinar.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/commit/db4b34682127ac9a8c25ca82f81f67ee092724b7. Thank you!
