### ISSUE TITLE
Audit redesign font sizes and turn them into variables

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#933]
The redesign uses a lot of repetitive measurement declarations for font sizing (`1rem`, `1.25rem`, `1.5rem`, etc.). We should: 

- [x] Search through all font size declarations, 
- [x] See what declarations are commonly repeated and turn them into a set of Sass variables
- [x] Generate companion utility classes
- [x] Identify outliers and see if they can be normalized
- [x] Apply utility font sizes and remove font-size declarations from Sass, when the font size does not change between breakpoints

**Comment by thurab40** [comment]
There are about 74 font-size declarations on the site

- The lowest font size is 0.75rem 
- The highest is 3.5rem

So I was thinking to have this scale base on the 16px/1rem font size declaration on the body

`css
$font-size-body-tiny: 0.75rem; // 12px
$font-size-body-small: 0.875rem; // 14px
$font-size-body: 1rem; // 16px
$font-size-body-medium: 1.25rem; // 20px
$font-size-body-large: 1.5rem; // 24px

$font-size-heading-tiny: 1.75rem; // 28px
$font-size-heading-small: 2rem; // 32px
$font-size-heading-medium: 2.25rem; // 36px
$font-size-heading-large: 2.5rem; // 40px
$font-size-heading-larger: 2.75rem; // 44px
$font-size-heading-largest: 3rem; // 48px
$font-size-heading-huge: 3.5rem; // 56px
`

On the following declarations I saw the unit (2ex) was that a mistake?

`css
.c-content ul li:before {
 content:"─";
 display:block;
 font-family:Anaheim,sans-serif;
 font-size:2ex; // <---------------------------
 height:1rem;
 position:relative;
 top:1rem;
 right:1.8rem;
 width:1rem
}

.c-content ol li:before {
 content:counter(a);
 display:block;
 font-family:Anaheim,sans-serif;
 font-size:3ex;   // <---------------------------
 height:1rem;
 position:relative;
 top:.45rem;
 right:1.75rem;
 width:1rem
}
`

**Comment by ericwbailey** [comment]
@thurab40 Thanks for auditing this! I really like the naming scheme you came up with, as well.

As for [the `ex` unit](https://developer.mozilla.org/en-US/docs/Web/CSS/length#ex), that's intentional. I could definitely see a case for refactoring it if we have more codified font size variables to use.

Is this something you'd be interesting in working on as a PR?

**Comment by thurab40** [comment]
Sure, I am interested. How do I go about it?

**Comment by thurab40** [comment]
Thanks for the link. I never know "ex unit" first time. appreciate it

**Comment by thurab40** [comment]
@ericwbailey I figured out what to do on the contribute doc. I will take it from there thanks

**Comment by ericwbailey** [comment]
@thurab40 That's great to hear, thank you. Definitely feel free to mention me here if you need more detail about anything.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/1027.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/1027 and https://github.com/a11yproject/a11yproject.com/pull/1068.
