### ISSUE TITLE
Remove unused CSS

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#935]
Currently, the process we use for delivering CSS is to manually determine if it's used in the site. This approach is okay for now, but will be unsustainable as the site continues to grow and more people work on it independently.

We should augment our existing Gulp CSS-related tasks with one that determines if CSS is being used or not before being deployed. Something along the lines of [purgecss](https://www.npmjs.com/package/gulp-purgecss).

**Comment by aniketkudale** [comment]
PurgeCSS looks perfect choice for this, I would like to work on this.

**Comment by ericwbailey** [comment]
Heck yes, thank you!
