### ISSUE TITLE
Add dark mode support

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#939]
[Dark mode](https://a11yproject.com/posts/operating-system-and-browser-accessibility-display-modes/#dark-mode) is a nice way for some users to use a website without triggering things like migraines or nausea. 

It would be nice to include dark mode support for this site. We would want:

- [ ] An accessible, semantic toggle for the control
- [ ] Styling that integrates into our existing Sass setup, and not a filter overlay
- [ ] Localstorage to remember a user's preference

Andy Bell has [a good article on how to do this](https://hankchizljaw.com/wrote/create-a-user-controlled-dark-or-light-mode/), although we'd need to use ES5 and avoid using CSS custom properties for better legacy browser support. Additionally, [Smashing Magazine has another good post](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/) outlining some design considerations.

**Comment by dennisgaebel** [comment]
@ericwbailey Can I have at this one? Sounds like a super fun challenge I'd be into. I've only briefly done LocalStorage stuff, but i'd like to give it a go. I gotta get the new site running, and once that's done I can start on this if that's ok 🍻

**Comment by dennisgaebel** [comment]
ok cool! just hit you up on Slack so I'm gonna assign myself

**Comment by ericwbailey** [comment]
Closing via https://github.com/a11yproject/a11yproject.com/issues/1008, as discussed in [this comment](https://github.com/a11yproject/a11yproject.com/issues/964#issuecomment-661336876).
