### ISSUE TITLE
details/summary support for Internet Explorer 11

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#941]
## Summary

Clicking or keyboard activation does not work for the details/summary elements on the site in Internet Explorer 11.

Example:
1. Open Internet Explorer 11 and go to https://a11yproject.com/checklist/
1. Attempt to activate a checklist `details` element to toggle it open

### Expected result

The `details` element should expand open.

### Actual result

The `details` element does not expand open.

### Additional Information

Scott O'Hara has [a good post on how to best implement this](https://www.scottohara.me/blog/2018/09/03/details-and-summary.html#wrapping-up).

**Comment by aardrian** [comment]
Polyfill and page on which to test IE11:
https://codepen.io/aardrian/pen/bMxMoW

**Comment by ericwbailey** [comment]
Just implemented this locally and it worked perfectly, thank you. A PR should be up soon.

**Comment by ericwbailey** [comment]
@aardrian I believe I've addressed this via https://github.com/a11yproject/a11yproject.com/pull/1019. Can I trouble you to verify it on your end?

**Comment by aardrian** [comment]
Works (in a spot test, not every one)!

Be aware the extra arrows in the visual:

![image](https://user-images.githubusercontent.com/1376607/88414451-dfbc1080-cdaa-11ea-93ae-ec34c5a85512.png)

**Comment by ericwbailey** [comment]
Thanks for that. I'm calling this issue closed, as the double dropdown, while  potentially confusing, isn't a barrier to triggering the expand/collapse behavior. We can revisit the visuals as a followup PR.
