### ISSUE TITLE
Double-check gulp JavaScript concatination 

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#949]
JavaScript is supposed to be concatenated from individual script files placed in the `js` folder via gulp. I'm skeptical.

**Comment by eric-bednarz-dev** [comment]
Just looking at the gulp file, only files in **sub**directories of the `js` directory are supposed to be concatenated and build to a file that takes the subdirectory name as base name.

E.g. `src/js/foobar/*.js` => `dist/js/foobar.js`

**Comment by ericwbailey** [comment]
@eric-bednarz-dev Thanks for this. It was kind of overlooked in the push to release, but this will help us keep our future JS work nice and modular.
