### ISSUE TITLE
Safari CSS issues

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#950]
Our CSS needs a little love when it comes to Safari. Currently there are layout bugs for:

- [x] The `details`/`summary` elements for the Table of Contents component.
- [x] Focus state on sponsors
- [x] Layout of homepage cards on mobile

More added here as they're discovered.

**Comment by andrewborstein** [comment]
Does `claimed` mean someone has already claimed responsibility for submitting PRs to solve the above issues, like perhaps @jendowns? If it's still available I'd be happy to open a PR for the Safari focus state bug.

**Comment by ericwbailey** [comment]
@andrewborstein Yep. We're using `Claimed` to indicate the issue has someone working on it for sorting/filtering purposes. That being said, I was going to be the one who tackled the focus state bug. Would you like to do it instead?

**Comment by andrewborstein** [comment]
Yeah, I already have a good lead on how to fix it, so happy to take it!

**Comment by ericwbailey** [comment]
Closing this, as all issues have been addressed. Thank you @jendowns and @andrewborstein 🙏
