### ISSUE TITLE
Add CI/CD checks for accessibility

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#953]
These would be a great resource to have to help maintain the quality of the site's code. I'm thinking either axe or Lighthouse (yes, I know Lighthouse is a modified version of axe under the hood).

**Comment by eric-bednarz-dev** [comment]
Did you have a look at the axe linter GitHub app yet?

https://github.com/apps/axe-linter

(not entirely sure what “personal” entails)

**Comment by ericwbailey** [comment]
Yup, on my radar. I'm unsure if we qualify as we're an org. If so, we'll have to see if we can budget it.

**Comment by ericwbailey** [comment]
Looks like we qualify 🎉

Thanks for bringing this to my attention!
