### ISSUE TITLE
Meta: Cannot sponsor the a11yproject

### ISSUE THREAD

**Issue by danielmatthew** [a11yproject/a11yproject.com#962]
Per the [contributing guidelines](https://www.a11yproject.com/contributing-guidelines/#reporting-issues) I didn't think that this was worthy of being titled as a 'Bug', but I hit 'Sponsor' and see the following error screen:

<img width="469" alt="Github's Sponsor modal showing the project is not enrolled" src="https://user-images.githubusercontent.com/111794/87693240-a40ac080-c784-11ea-969e-763703381b6b.png">

> Some errors were encountered when parsing the FUNDING.yml file:
      Some users provided are not enrolled in GitHub Sponsors. Apply to Sponsors.

Thankfully the External Links sent me in the right direction…

**Comment by ericwbailey** [comment]
Oh yikes, that's not great. Thanks for the head's up.

**Comment by ericwbailey** [comment]
Strange. I thought we were in the sponsor program, but there's apparently some nuance behind applying versus actually qualifying. Regardless, it's been addressed in https://github.com/a11yproject/a11yproject.com/pull/991.
