### ISSUE TITLE
Incorrect link destination for "Featured resource:

### ISSUE THREAD

**Issue by jfhector** [a11yproject/a11yproject.com#963]
Please review our Contributing guidelines:
https://a11yproject.com/contributing-guidelines/

## Summary

1. Go to https://www.a11yproject.com/resources/
2. In the side bar navigation, under "FEATURED RESOURCE", click on the link called 'Inclusive Design Pattern'

### Expected result

Arrive on a page about Inclusive Design Pattern

### Actual result

Arrive on this page, which is not about Inclusive Design Pattern: https://howlowck.github.io/Akbar/

### Additional Information

> To help us try and reproduce the issue, please provide the following information:
> 1. What device were you using? (laptop, phone, tablet, etc.)
> 2. Operating System version.
> 3. Browser(s) and version(s).
> 4. Assistive technology used (if applicable)

### Additional Information

Here's the link's HTML. The label and the destination don't match.
```html
<a class="c-card__title" href="https://howlowck.github.io/Akbar/">Inclusive Design Patterns</a>
```

Something else that's important to know, but didn't fall into an above category: Well done on the redesign!! It looks and feels great. And thanks for this great site.

**Comment by ericwbailey** [comment]
Hi, Jean-Francois! Thank you for reporting this, we'll get right on it.
