### ISSUE TITLE
Bug: 404 Errors

### ISSUE THREAD

**Issue by michaelspellacy** [a11yproject/a11yproject.com#965]
Ran a link scan on your site and noted that humans.txt is throwing a lot of 404's when you have pages loading from within a sub-directory. Adding a forward slash should globally clear that one right up. 

**Before:** `<link rel="author" href="humans.txt">`

**After:** `<link rel="author" href="/humans.txt">`

Also spotted a few other 404's:

**Page:** https://www.a11yproject.com/announcements/2020-07-15-2020-redesign/ 
**Dead Link:** Contact Us (missing mailto: URI, should be mailto:hello@a11yproject.com)

**Page:** https://www.a11yproject.com/checklist/
**Dead Link:** modes such as Windows High Contrast or Inverted Colors (https://www.a11yproject.com/checklist/posts/operating-system-and-browser-accessibility-display-modes/)

**Page:** https://www.a11yproject.com/posts/2013-05-11-skip-nav-links/
**Dead Link:** ARIA landmarks (https://www.a11yproject.com/posts/aria-landmark-roles/)

**Page:** https://www.a11yproject.com/posts/2020-05-13-aria-has-perfect-support/ 
**Dead Link:** Accessible Rich Internet Applications (ARIA) (https://www.a11yproject.com/posts/getting-started-aria/)

**Page:** https://www.a11yproject.com/posts/2013-01-11-navigate-using-just-your-keyboard/  
**Dead Link:**  Quick Tip: Safari Keyboard Navigation (https://www.a11yproject.com/posts/safari-keyboard-navigation/)

**Page:** https://www.a11yproject.com/checklist/
**Dead Link:** skip link (https://www.a11yproject.com/posts/skip-nav-links/)

**Page:** https://www.a11yproject.com/posts/2013-01-11-navigate-using-just-your-keyboard/
**Dead Link:** How–to: Use Skip Navigation links (https://www.a11yproject.com/posts/skip-nav-links/)

Congrats again on new launch!

**Comment by ericwbailey** [comment]
Hi Michael! And thanks for doing this, we'll get on it shortly.

**Comment by thebencourt** [comment]
Fixed most of them in that PR, the only two I couldn't find were:

**Page:** https://www.a11yproject.com/checklist/
**Dead Link:** modes such as Windows High Contrast or Inverted Colors (https://www.a11yproject.com/checklist/posts/operating-system-and-browser-accessibility-display-modes/)

**Page:** https://www.a11yproject.com/posts/2013-01-11-navigate-using-just-your-keyboard/
**Dead Link:** Quick Tip: Safari Keyboard Navigation (https://www.a11yproject.com/posts/safari-keyboard-navigation/)

**Comment by ericwbailey** [comment]
@thebencourt I think I got them: https://github.com/a11yproject/a11yproject.com/pull/990

@michaelspellacy I believe this captures all your reported broken links. Could I trouble you to verify? You may need to do a hard refresh of the site, as it deploys a service worker.

**Comment by thebencourt** [comment]
@ericwbailey https://www.a11yproject.com/posts/2020-01-23-operating-system-and-browser-accessibility-display-modes/ is returning a 404

**Comment by ericwbailey** [comment]
@thebencourt Figured out why that's still 404ing, the post somehow got lost in the merge. I'm re-creating it now.

**Comment by ericwbailey** [comment]
Alright. Should be good as of https://github.com/a11yproject/a11yproject.com/pull/993. That'll teach me to use git 😅

**Comment by michaelspellacy** [comment]
@ericwbailey I can verify later today if you like.

**Comment by ericwbailey** [comment]
That would be great, thank you.

**Comment by michaelspellacy** [comment]
@ericwbailey  Ran another scan! You are all good!  Closing!

Thanks @thebencourt!
