### ISSUE TITLE
Numeronym definition obscures nav

### ISSUE THREAD

**Issue by aardrian** [a11yproject/a11yproject.com#966]
## Summary

On short viewports the box that defines the numeronym obscures the navigation, covering it completely in some cases.

Found when browser in landscape mode in Firefox Preview on Android, confirmed in a short ChromiEdge window.

### Expected result

Navigation would never be obscured.

### Actual result

![Screenshot_20200716-115739](https://user-images.githubusercontent.com/1376607/87695906-1ae09300-c75e-11ea-873b-fdaa36174255.png)
![2020-07-16 (2)](https://user-images.githubusercontent.com/1376607/87695981-32b81700-c75e-11ea-85c1-4c9b0920aa63.png)

### Additional Information

In a very quick test to confirm the issue I found that removing the following fixed it (this is not a recommended fix, just a quick test):

```
.l-hero {
    height: 75vh;
}
```

**Comment by jendowns** [comment]
Hey there, I confirmed this as well & I believe I have a suggested fix. I can propose a PR shortly. 👍

**Comment by ericwbailey** [comment]
@aardrian Could you verify this is fixed?

**Comment by aardrian** [comment]
LGTM

**Comment by ericwbailey** [comment]
Wonderful. Thank you for reporting and confirming.
