### ISSUE TITLE
Bug: Contributing Guidelines reference missing `gh-pages` branch

### ISSUE THREAD

**Issue by danielmatthew** [a11yproject/a11yproject.com#971]
The [Contributing Guidelines](https://www.a11yproject.com/contributing-guidelines/#important-branches) reference the `gh-pages` branch, which [does not appear to be available](https://github.com/a11yproject/a11yproject.com/branches/all). This could be a hold-over from the Jekyll-version of the site, or I have failed with my Git-foo.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/972. Thank you for reporting and fixing the issue 🎉
