### ISSUE TITLE
Photos overlap some text on Team/Authors/Spotlight pages

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#975]
[Issue reported on Twitter](https://twitter.com/wpeditorial/status/1283830085380911110).

At small screen sizes the photo can overlap the person's name if it is long enough. We'll need to:

- [ ] Add a `tiny` photo size to the `$_person-photo` Sass map.
- [ ] Tweak the incorporating breakpoint declarations to incorporate it.
- [ ] Verify using a smartphone.

Also see: https://github.com/a11yproject/a11yproject.com/issues/948

**Comment by beckkramer** [comment]
I can help with this one! Is the goal to make the image just smaller in its current position, or move it out of position where any overlap could happen (maybe centered on the top border?)

![Screenshot_7](https://user-images.githubusercontent.com/2972688/87880022-f7168a80-c9b3-11ea-85df-43a195c3e9d4.png)

**Comment by ericwbailey** [comment]
Ooh, I like the centered treatment at a small size. Let's go with that, thank you!

**Comment by beckkramer** [comment]
Awesome, will do!
